# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config", "simplelaunch_runner")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//clockwork/demo/first_integration:__subpackages__"])

simplelaunch_runner(
    name = "udp_sample_system",
    config = ":democpu.textproto",
)

clk(
    name = "demo_udp_boxes_clk",
    srcs = ["demo_udp_boxes.clk"],
    outs = [
        "demo_udp_boxes_clk_cc.cc",
        "demo_udp_boxes_clk_cc.hh",
        "demo_udp_boxes_clk_cc.inl",
        "demo_udp_boxes_clk_exe.cc",
        "demo_udp_boxes_clk_exe.hh",
        "demo_udp_boxes_clk_exe.inl",
    ],
    cpp_deps = [
        ":just_a_uint32_clk_cc",
        ":ping_pong_clk_cc",
        "//clockwork/io:var_packet_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_exe",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":just_a_uint32_clk",
        ":ping_pong_clk",
        "//clockwork/io:var_packet_clk",
    ],
)

clk(
    name = "demo_udp_system_clk",
    srcs = ["demo_udp_system.clk"],
    outs = [
        "clockwork.clockwork.io.udp_sample_system.demo_udp_system.demo_udp_system.proc.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_channel_allocations.csv",
        "demo_udp_system.demo_udp_system.DemoCpu_channel_spy_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_event_logger_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_metrics_channel_metadata_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_signal_metadata_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_simplelaunch_config.textproto",
        "demo_udp_system.demo_udp_system.DemoCpu_telemetry_logger_config.tachyon",
        "demo_udp_system.demo_udp_system.diagnostics_database_config.tachyon",
        "demo_udp_system.demo_udp_system.logged_channel_metadata.pbbin",
    ],
    deps = [":demo_udp_boxes_clk"],
)

merge_simplelaunch_config(
    name = "democpu.textproto",
    srcs = [
        "demo_udp_system.demo_udp_system.DemoCpu_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.io.udp_sample_system.demo_udp_system.demo_udp_system.proc.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_channel_allocations.csv",
        "demo_udp_system.demo_udp_system.DemoCpu_channel_spy_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_event_logger_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_metrics_channel_metadata_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_signal_metadata_config.tachyon",
        "demo_udp_system.demo_udp_system.DemoCpu_telemetry_logger_config.tachyon",
        "demo_udp_system.demo_udp_system.diagnostics_database_config.tachyon",
        ":demo_udp_boxes_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)

clk(
    name = "just_a_uint32_clk",
    srcs = ["just_a_uint32.clk"],
    outs = [
        "just_a_uint32_clk_cc.cc",
        "just_a_uint32_clk_cc.hh",
        "just_a_uint32_clk_cc.inl",
    ],
    generate = ["cpp"],
)

clk(
    name = "ping_pong_clk",
    srcs = ["ping_pong.clk"],
    outs = [
        "ping_pong_clk_cc.cc",
        "ping_pong_clk_cc.hh",
        "ping_pong_clk_cc.inl",
        "ping_pong_clk_cc_dial.cc",
        "ping_pong_clk_cc_dial.hh",
        "ping_pong_clk_cc_dial.inl",
    ],
    cpp_deps = [
        ":just_a_uint32_clk_cc",
        "//clockwork/io:var_packet_clk_cc",
    ],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [
        ":just_a_uint32_clk",
        "//clockwork/io:var_packet_clk",
    ],
)

cc_library(
    name = "ping_pong_clk_cc_impl",
    srcs = ["ping_pong_clk_cc_impl.cc"],
    deps = [
        ":just_a_uint32_clk_cc",
        ":ping_pong_clk_cc_dial",
        "//clockwork/dial:msg_input",
        "//clockwork/io:var_packet_clk_cc",
        "//clockwork/pinion:publishable",
        "//jewels/container:circular_buffer",
        "//jewels/container/tap:var_array",
        "//jewels/memory:bits",
        "@fmt",
    ],
)
