# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

clk(
    name = "compression_test_schema_clk",
    srcs = ["compression_test_schema.clk"],
    outs = [
        "compression_test_schema_clk_cc.cc",
        "compression_test_schema_clk_cc.hh",
        "compression_test_schema_clk_cc.inl",
        "compression_test_schema_clk_cc_types.cc",
        "compression_test_schema_clk_cc_types.hh",
        "compression_test_schema_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)

cc_library(
    name = "strong_type_factory",
    srcs = ["strong_type_factory.inl"],
    hdrs = ["strong_type_factory.hh"],
)

clk(
    name = "test_schema_v1_clk",
    srcs = ["test_schema_v1.clk"],
    outs = [
        "test_schema_v1_clk_cc.cc",
        "test_schema_v1_clk_cc.hh",
        "test_schema_v1_clk_cc.inl",
        "test_schema_v1_clk_cc_types.cc",
        "test_schema_v1_clk_cc_types.hh",
        "test_schema_v1_clk_cc_types.inl",
        "test_schema_v1_clk_py.py",
    ],
    cpp_deps = [":strong_type_factory"],
    generate = [
        "cpp",
        "py",
    ],
)

clk(
    name = "test_schema_v2_clk",
    srcs = ["test_schema_v2.clk"],
    outs = [
        "test_schema_v2_clk_cc.cc",
        "test_schema_v2_clk_cc.hh",
        "test_schema_v2_clk_cc.inl",
        "test_schema_v2_clk_cc_types.cc",
        "test_schema_v2_clk_cc_types.hh",
        "test_schema_v2_clk_cc_types.inl",
        "test_schema_v2_clk_py.py",
    ],
    cpp_deps = [":strong_type_factory"],
    generate = [
        "cpp",
        "py",
    ],
)

cc_library(
    name = "validate_upgradability",
    srcs = ["validate_upgradability.inl"],
    hdrs = ["validate_upgradability.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/serialization/cpp:tachyon_model",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "@catch2//:catch2_main",
        "@wise_enum",
    ],
)
