# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

clk(
    name = "alignment_type_clk",
    srcs = ["alignment_type.clk"],
    outs = [
        "alignment_type_clk_cc.cc",
        "alignment_type_clk_cc.hh",
        "alignment_type_clk_cc.inl",
    ],
    generate = ["cpp"],
)

cc_library(
    name = "approx_aligner",
    srcs = ["approx_aligner.inl"],
    hdrs = ["approx_aligner.hh"],
    deps = [
        ":alignment_type_clk_cc",
        ":approx_aligner_config_clk_cc",
        "//clockwork:repr_iface",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/time:sync_time",
    ],
)

clk(
    name = "approx_aligner_config_clk",
    srcs = ["approx_aligner_config.clk"],
    outs = [
        "approx_aligner_config_clk_cc.cc",
        "approx_aligner_config_clk_cc.hh",
        "approx_aligner_config_clk_cc.inl",
        "approx_aligner_config_clk_proto.proto",
        "approx_aligner_config_clk_proto_conv.cc",
        "approx_aligner_config_clk_proto_conv.hh",
        "approx_aligner_config_clk_proto_conv.inl",
    ],
    generate = [
        "cpp",
        "proto",
        "proto_conv",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "approx_aligner_policies",
    srcs = ["approx_aligner_policies.inl"],
    hdrs = ["approx_aligner_policies.hh"],
    deps = [":msg_input"],
)

cc_library(
    name = "cond_messages_present",
    srcs = ["cond_messages_present.inl"],
    hdrs = ["cond_messages_present.hh"],
    deps = [":exec_condition"],
)

cc_library(
    name = "cond_time_since_last_exec",
    srcs = ["cond_time_since_last_exec.inl"],
    hdrs = ["cond_time_since_last_exec.hh"],
    deps = [":exec_condition"],
)

cc_library(
    name = "exec_condition",
    srcs = ["exec_condition.inl"],
    hdrs = ["exec_condition.hh"],
)

cc_library(
    name = "include_common",
    hdrs = ["include_common.hh"],
    deps = [
        ":cond_messages_present",
        ":cond_time_since_last_exec",
        ":msg_input",
        ":signal_aggregator",
        "//clockwork:repr_iface",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk_cc",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk_cc",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:publisher_handle",
        "//jewels/callsig:outcome",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "msg_input",
    srcs = ["msg_input.inl"],
    hdrs = ["msg_input.hh"],
    deps = ["//jewels/container:circular_buffer"],
)

cc_library(
    name = "signal_aggregator",
    srcs = ["signal_aggregator.inl"],
    hdrs = ["signal_aggregator.hh"],
)
