# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

exports_files([
    "report.clk",
    "database_config.clk",
])

clk(
    name = "channels_clk",
    srcs = ["channels.clk"],
    generate = ["none"],
    deps = [":report_clk"],
)

clk(
    name = "database_config_clk",
    srcs = ["database_config.clk"],
    outs = [
        "database_config_clk_cc.cc",
        "database_config_clk_cc.hh",
        "database_config_clk_cc.inl",
    ],
    cpp_deps = [":report_clk_cc"],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    deps = [":report_clk"],
)

clk(
    name = "report_clk",
    srcs = ["report.clk"],
    outs = [
        "report_clk_cc.cc",
        "report_clk_cc.hh",
        "report_clk_cc.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

cc_library(
    name = "report_definitions",
    hdrs = ["report_definitions.hh"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "reporter",
    hdrs = ["reporter.hh"],
)
