# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "aligner_test",
    srcs = ["aligner_test.cc"],
    deps = [
        "//jewels/aligner",
        "@catch2//:catch2_main",
    ],
)
