# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "exit_condition_signal_test",
    srcs = ["exit_condition_signal_test.cc"],
    args = ["--order=decl"],
    deps = [
        "//jewels/cli:exit_condition_signal",
        "@catch2//:catch2_main",
    ],
)
