# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")

package(default_visibility = ["//visibility:public"])

clk(
    name = "config_init_boxes_clk",
    srcs = ["config_init_boxes.clk"],
    outs = [
        "config_init_boxes_clk_exe.cc",
        "config_init_boxes_clk_exe.hh",
        "config_init_boxes_clk_exe.inl",
    ],
    cpp_deps = [
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk_cc",
        "//clockwork/tools/metrics_channel_metadata:metrics_channel_metadata_init_clk_cc",
        "//clockwork/tools/signal_metadata:signal_metadata_init_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = ["cpp_exe"],
    deps = [
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk",
        "//clockwork/tools/metrics_channel_metadata:metrics_channel_metadata_init_clk",
        "//clockwork/tools/signal_metadata:signal_metadata_init_clk",
    ],
)
