# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "deterministic_log_writer_test",
    srcs = ["deterministic_log_writer_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/logging:channel_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/logging/readers:offboard_log_reader",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/writers:deterministic_log_writer",
        "//clockwork/logging/writers/tests/support:test_log_writer_config",
        "//clockwork/logging/writers/tests/support:test_publisher",
        "//clockwork/runners:deterministic_channel_handler",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
        "@xxhash",
    ],
)

cc_test(
    name = "log_writer_base_test",
    srcs = ["log_writer_base_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/logging/writers:channel_message_rates_config",
        "//clockwork/logging/writers:log_writer_base",
        "//clockwork/logging/writers:log_writer_state",
        "//clockwork/logging/writers/tests/support:test_log_writer_config",
        "//clockwork/logging/writers/tests/support:test_publisher",
        "//jewels/container:compare",
        "//jewels/filesystem",
        "//jewels/log_cerr",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "logger_test",
    srcs = ["logger_test.cc"],
    deps = [
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/logging/writers:log_writer_state",
        "//clockwork/logging/writers:logger",
        "//clockwork/logging/writers:logger_config",
        "//clockwork/logging/writers:logger_status",
        "//clockwork/logging/writers/tests/support:test_log_writer_config",
        "//clockwork/logging/writers/tests/support:test_publisher",
        "//jewels/filesystem",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:fix_catch2_cerr_nonthreadsafe_redirect",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "message_rate_counter_test",
    srcs = ["message_rate_counter_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging/writers:channel_message_rates_config",
        "//clockwork/logging/writers:message_rate_counter",
        "//clockwork/logging/writers:rate_filter",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "message_writer_test",
    srcs = ["message_writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/logging/writers:logger_config",
        "//clockwork/logging/writers:message_writer",
        "//clockwork/logging/writers/tests/support:test_log_writer_config",
        "//clockwork/logging/writers/tests/support:test_publisher",
        "//jewels/filesystem",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "rate_filter_test",
    srcs = ["rate_filter_test.cc"],
    deps = [
        "//clockwork/logging/writers:rate_filter",
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)
