# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

clk(
    name = "test_message_clk",
    srcs = ["test_message.clk"],
    outs = [
        "test_message_clk_cc.cc",
        "test_message_clk_cc.hh",
        "test_message_clk_cc.inl",
        "test_message_clk_cc_types.cc",
        "test_message_clk_cc_types.hh",
        "test_message_clk_cc_types.inl",
        "test_message_clk_nb.cc",
        "test_message_clk_nb.hh",
        "test_message_clk_nb.inl",
        "test_message_clk_py.py",
    ],
    generate = [
        "cpp",
        "nanobind",
        "py",
    ],
)
