# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Source of truth for common dependencies for autogenerated clk nanobindings."""

# C++ dependencies every clk py_cc_binding shares as deps.
COMMON_CC_DEPS = [
    "@nanobind",
    "//clockwork:repr_iface",
    "//jewels/nanobind/clk_bindings:bind_fixed_array",
    "//jewels/nanobind/clk_bindings:bind_tachyon_serialize",
    "//jewels/nanobind/clk_bindings:bind_var_array",
    "//jewels/nanobind/clk_bindings:cast_maybe_by_reference",
    "//jewels/nanobind/clk_bindings:get_python_type_name",
    "//jewels/nanobind:nb_au",
    "//jewels/nanobind:nb_var_string",
    "//jewels/nanobind:uuid_caster",
]

# Python dependencies every clk py_cc_binding shares as py_deps.
COMMON_PY_DEPS = [
    # for 'get_metadata_from_protobuf' from 'bind_tachyon_constraint_and_metadata':
    "//clockwork/serialization/metadata:tachyon",
    # for the type signature for the 'TachyonMetadata' from 'bind_tachyon_constraint_and_metadata':
    "//clockwork/serialization/metadata:tachyon_model",
    # for 'FieldConstraint' for 'bind_tachyon_constraint_and_metadata':
    "//clockwork/dsl/serialization:tachyon_reg",
    "//jewels/nanobind:nb_sync_time",
]
