# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:package.bzl", "package")

package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "channel_policy.clk",
    "channel_publisher_config.clk",
    "log_writer_config.clk",
])

clk(
    name = "channel_policy_clk",
    srcs = ["channel_policy.clk"],
    generate = ["none"],
    deps = [":channel_type_clk"],
)

clk(
    name = "channel_publisher_config_clk",
    srcs = ["channel_publisher_config.clk"],
    outs = [
        "channel_publisher_config_clk_cc.cc",
        "channel_publisher_config_clk_cc.hh",
        "channel_publisher_config_clk_cc.inl",
        "channel_publisher_config_clk_cc_types.cc",
        "channel_publisher_config_clk_cc_types.hh",
        "channel_publisher_config_clk_cc_types.inl",
        "channel_publisher_config_clk_py.py",
    ],
    cpp_deps = [":log_uuid_tag_clk_cc"],
    generate = [
        "cpp",
        "py",
    ],
    minimize_builtin_deps = True,
    py_deps = [":log_uuid_tag_clk_py"],
    visibility = ["//visibility:public"],
    deps = [
        ":log_uuid_tag_clk",
        "//clockwork/common:constants_clk",
    ],
)

clk(
    name = "channel_type_clk",
    srcs = ["channel_type.clk"],
    outs = [
        "channel_type_clk_cc.cc",
        "channel_type_clk_cc.hh",
        "channel_type_clk_cc.inl",
        "channel_type_clk_cc_types.cc",
        "channel_type_clk_cc_types.hh",
        "channel_type_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

cc_library(
    name = "compression_type",
    srcs = ["compression_type.inl"],
    hdrs = ["compression_type.hh"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "cpp_message_encoding",
    hdrs = ["cpp_message_encoding.hh"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "cpp_schema_encoding",
    hdrs = ["cpp_schema_encoding.hh"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "decompress_option",
    srcs = ["decompress_option.inl"],
    hdrs = ["decompress_option.hh"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "duplicate_message_filter",
    srcs = ["duplicate_message_filter.cc"],
    hdrs = ["duplicate_message_filter.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":log_timestamp",
        "//jewels/container:circular_buffer",
        "//jewels/memory:aligned_storage",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@fmt",
    ],
)

cc_library(
    name = "lite_compressor",
    srcs = ["lite_compressor.cc"],
    hdrs = ["lite_compressor.hh"],
    deps = [
        ":lite_compressor_interface",
        ":log_error",
        ":nolint_helper",
        ":xxh3_checksum",
        "//jewels/aligner",
        "//jewels/callsig:outparam",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/std:expected",
        "@xxhash",
    ],
)

cc_library(
    name = "lite_compressor_interface",
    hdrs = ["lite_compressor_interface.hh"],
    deps = ["//jewels/callsig:outparam"],
)

cc_library(
    name = "log_error",
    srcs = ["log_error.inl"],
    hdrs = ["log_error.hh"],
    deps = [
        "//jewels/callsig:outcome",
        "//jewels/filesystem:error_code",
        "//jewels/std:expected",
        "@aws_sdk//:s3",
        "@wise_enum",
    ],
)

cc_library(
    name = "log_interval",
    srcs = ["log_interval.inl"],
    hdrs = ["log_interval.hh"],
    deps = [
        ":log_timestamp",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "log_timestamp",
    srcs = ["log_timestamp.inl"],
    hdrs = ["log_timestamp.hh"],
    deps = ["//jewels/time:sync_time"],
)

cc_library(
    name = "log_uuid",
    hdrs = ["log_uuid.hh"],
    deps = [
        ":log_uuid_tag_clk_cc",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
    ],
)

clk(
    name = "log_uuid_tag_clk",
    srcs = ["log_uuid_tag.clk"],
    outs = [
        "log_uuid_tag_clk_cc.cc",
        "log_uuid_tag_clk_cc.hh",
        "log_uuid_tag_clk_cc.inl",
        "log_uuid_tag_clk_cc_types.cc",
        "log_uuid_tag_clk_cc_types.hh",
        "log_uuid_tag_clk_cc_types.inl",
        "log_uuid_tag_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
    ],
    minimize_builtin_deps = True,
)

clk(
    name = "log_writer_config_clk",
    srcs = ["log_writer_config.clk"],
    outs = [
        "log_writer_config_clk_cc.cc",
        "log_writer_config_clk_cc.hh",
        "log_writer_config_clk_cc.inl",
        "log_writer_config_clk_cc_types.cc",
        "log_writer_config_clk_cc_types.hh",
        "log_writer_config_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":channel_type_clk_cc",
        ":log_uuid_tag_clk_cc",
        ":message_encoding_clk_cc",
        ":schema_encoding_clk_cc",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    deps = [
        ":channel_type_clk",
        ":log_uuid_tag_clk",
        ":message_encoding_clk",
        ":schema_encoding_clk",
        "//clockwork/common:constants_clk",
    ],
)

clk(
    name = "message_encoding_clk",
    srcs = ["message_encoding.clk"],
    outs = [
        "message_encoding_clk_cc.cc",
        "message_encoding_clk_cc.hh",
        "message_encoding_clk_cc.inl",
        "message_encoding_clk_cc_types.cc",
        "message_encoding_clk_cc_types.hh",
        "message_encoding_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

cc_library(
    name = "nolint_helper",
    srcs = ["nolint_helper.inl"],
    hdrs = ["nolint_helper.hh"],
    deps = [
        ":log_error",
        "//jewels/log_cerr",
        "//jewels/std:expected",
    ],
)

clk(
    name = "schema_encoding_clk",
    srcs = ["schema_encoding.clk"],
    outs = [
        "schema_encoding_clk_cc.cc",
        "schema_encoding_clk_cc.hh",
        "schema_encoding_clk_cc.inl",
        "schema_encoding_clk_cc_types.cc",
        "schema_encoding_clk_cc_types.hh",
        "schema_encoding_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

cc_library(
    name = "wrapping_counter",
    srcs = ["wrapping_counter.inl"],
    hdrs = ["wrapping_counter.hh"],
    deps = ["//jewels/meta:concepts"],
)

cc_library(
    name = "xxh3_checksum",
    srcs = ["xxh3_checksum.cc"],
    hdrs = ["xxh3_checksum.hh"],
    deps = ["@xxhash"],
)

cc_library(
    name = "zstd_helper",
    srcs = ["zstd_helper.cc"],
    hdrs = ["zstd_helper.hh"],
    deps = [
        ":log_error",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@zstd",
    ],
)
