# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

py_test(
    name = "clk_cog_metrics_test",
    srcs = [
        "clk_cog_metrics_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    tags = ["manual"],
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "cog_metrics_event_signals_test",
    srcs = ["cog_metrics_event_signals_test.cc"],
    deps = [
        "//clockwork/cog:include_common",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/cog:ten_nanosecond_type",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc_dial",
        "//clockwork/dsl/cog/tests/support:mock_input_view",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:slot",
        "//jewels/memory:instrumented_pmr_resource",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "cog_metrics_policy_test",
    srcs = [
        "cog_metrics_policy_test.py",
        ":__test__",
    ],
    data = ["//std:cog_metrics_policy.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/cog:cog_metrics_policy",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "cog_metrics_telemetry_signals_test",
    srcs = ["cog_metrics_telemetry_signals_test.cc"],
    deps = [
        "//clockwork/cog:include_common",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/cog:ten_nanosecond_type",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc_dial",
        "//clockwork/dsl/cog/tests/support:mock_input_view",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:slot",
        "//jewels/memory:instrumented_pmr_resource",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "copy_cog_test",
    srcs = ["copy_cog_test.cc"],
    deps = [
        "//clockwork/dsl/cog/tests/support:copy_cog_clk_cc",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "cpp_python_cog_test",
    srcs = [
        "cpp_python_cog_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner.clk",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_cog.clk",
        "//clockwork/python:python_state.clk",
        "//clockwork/python/tests/support:python_cog.clk",
        "//clockwork/python/tests/support:python_cog_multi_output.clk",
        "//clockwork/python/tests/support:test_config.clk",
        "//clockwork/python/tests/support:test_input_message.clk",
        "//clockwork/python/tests/support:test_output_message.clk",
        "//clockwork/python/tests/support:test_state.clk",
        "//std/aligners:state.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/cog:cpp_python_cog",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:py_target",
        "//clockwork/dsl/ir:python_cog_dial",
    ],
)

cc_test(
    name = "cppcog_cpp_test",
    srcs = ["cppcog_cpp_test.cc"],
    deps = [
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/tests/support:clk_hellocog_clk_cc",
        "//clockwork/dsl/tests/support:clk_hellomsg_clk_cc",
        "//clockwork/dsl/tests/support:goodbyecog",
        "//jewels/memory:memory_resource",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "cppdial_cpp_test",
    srcs = ["cppdial_cpp_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/diagnostics:reporter",
        "//clockwork/dsl/tests/support:goodbyecog_dial",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
        "//clockwork/dsl/tests/support:hellocog_dial",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "hellocog_metrics_test",
    srcs = ["hellocog_metrics_test.cc"],
    deps = [
        "//clockwork/cog:cog_statistics",
        "//clockwork/cog:include_common",
        "//clockwork/dial:cond_messages_present",
        "//clockwork/dial:cond_time_since_last_exec",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk_cc",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk_cc",
        "//clockwork/dsl/cog:ten_nanosecond_type",
        "//clockwork/dsl/tests/support:hellocog",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:in_memory_channel",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "metrics_policy_loader_test",
    srcs = [
        "metrics_policy_loader_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/cog:metrics_policy_loader",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "rate_limited_cog_test",
    srcs = ["rate_limited_cog_test.cc"],
    deps = [
        "//clockwork/cog:cog_publishers",
        "//clockwork/dsl/cog/tests/support:rate_limited_cog_clk_cc",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "report_group_policy_test",
    srcs = [
        "report_group_policy_test.py",
        ":__test__",
    ],
    data = ["//std:signals.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/cog:report_group_policy",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
    ],
)

cc_test(
    name = "signal_api_test",
    srcs = ["signal_api_test.cc"],
    deps = [
        "//clockwork/cog:include_common",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/ir/tests/support:report_group_defs_clk_cc",
        "//clockwork/dsl/ir/tests/support:report_group_defs_clk_cc_dial",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container/tap:bitset",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "simple_cog_cog_metrics_signals_test",
    srcs = ["simple_cog_cog_metrics_signals_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog:simple_cog",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:cog_envelope",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc",
        "//clockwork/dsl/cog/tests/support:cog_metrics_test_cog_clk_cc_dial",
        "//clockwork/dsl/tests/support:clk_hellomsg_clk_cc",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer_layout",
        "//clockwork/pinion:error",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:slot_ref",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/std:span",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "skip_cog_test",
    srcs = ["skip_cog_test.cc"],
    deps = [
        "//clockwork/dsl/cog/tests/support:skip_cog_clk_cc",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "ten_nanosecond_type_test",
    srcs = ["ten_nanosecond_type_test.cc"],
    deps = [
        "//clockwork/dsl/cog:ten_nanosecond_type",
        "@catch2//:catch2_main",
    ],
)
