// Copyright 2025 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

package resolver

import (
	"fmt"
	"log"
	"os"
	"slices"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"

	"go.skia.org/infra/go/util"

	common "github.com/stackav-oss/clockwork/tools/gazelle/clk_plugin/common"
)

// gazelleExtensionName is the extension name passed to Gazelle.
//
// This name can be used to enable or disable this Gazelle extension via the --lang flag, e.g.
//
//	$ bazel run gazelle -- update --lang clk
const gazelleExtensionName = "clk"

// Suffix on python imports for the proto python library
const pyProtoImportSuffix = "_proto_pb2"

// Suffix on the build rule for the proto python library
const pyProtoRuleSuffix = "_proto_py_library"

// ClkResolver implements the resolve.Resolver and resolve.CrossResolver interfaces.
//
// Interface documentation:
//
// ClkResolver is an interface that language extensions can implement to resolve
// dependencies in rules they generate.
type ClkResolver struct{}

// Name implements the resolve.Resolver interface.
//
// Interface documentation:
//
// Name returns the name of the language. This should be a prefix of the
// kinds of rules generated by the language, e.g., "go" for the Go extension
// since it generates "go_library" rules.
func (rslv *ClkResolver) Name() string {
	return gazelleExtensionName
}

// Imports implements the resolve.Resolver interface.
func (rslv *ClkResolver) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	if r.AttrStrings("generate") != nil {
		return []resolve.ImportSpec{{
			Lang: "clk",
			Imp:  f.Pkg + ":" + r.Name(),
		}}
	}
	return nil
}

// Embeds implements the resolve.Resolver interface.
func (rslv *ClkResolver) Embeds(*rule.Rule, label.Label) []label.Label { return nil }

// Resolve implements the resolve.Resolver interface.
//
// Resolve takes a (rule, ImportsParsedFromRuleSources) pair generated by Language.GenerateRules()
// and sets the rules attributes from the information parsed from the source clk file.
// The strings in the imports instance are of the form path::to::file::rule_name using the
// conventions used by the clk compiler to name the rules for the outputs generated by the compiler.
//
// For example, entries in the clkImports already have the _clk suffix on their import paths,
// so we can just take aa::bb::cc::file_clk and generate the label //aa/bb/cc:file_clk.
// Likewise for the clkProtoImports, the entries are all aa::bb::cc::file_clk_proto, so we
// can generate the label (//aa/bb/cc:file_clk_proto) for the dependency mechanically.
//
// Gazelle calls this method once for each (rule, ImportsParsedFromRuleSources) pair generated by
// successive calls to Language.GenerateRules().
func (rslv *ClkResolver) Resolve(_ *config.Config, _ *resolve.RuleIndex, _ *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
	importsFromRuleSources, ok := imports.(common.ImportsParsedFromRuleSources)
	if !ok {
		rule_add := ""
		if r != nil {
			rule_add = fmt.Sprintf(" from '%s' as a '%s'", r.AttrStrings("srcs"), r.Kind())
		}
		log.Printf("\n\nGot an unexpected type '%T' resolving imports for %s%s!\n\n"+
			"This is usually caused by a cross-language name collision for files. e.g., my_test.cc and my_test.py.\n"+
			"An easy fix is to rename one of them so their expected target names are different. e.g., my_test.cc -> my_cc_test.cc\n\n", imports, from.String(), rule_add)
		os.Exit(1)
	}
	common.SetGenerateAttr(r, importsFromRuleSources.GetClkGenerates())
	setOutsAttr(r, from, importsFromRuleSources.GetClkGenerates())
	setLabelsAttr(r, "deps", from, importsFromRuleSources.GetClkImports())
	setLabelsAttr(r, "cpp_deps", from, importsFromRuleSources.GetCppImports())
	setLabelsAttr(r, "proto_deps", from, importsFromRuleSources.GetProtoImports())
	setLabelsAttr(r, "py_deps", from, importsFromRuleSources.GetPyImports())
	setLabelsAttr(r, "cpp_exe_deps", from, importsFromRuleSources.GetCppExeImports())
	setStringAttr(r, "go_import_path", importsFromRuleSources.GetGoProtoImportPath())
}

// CrossResolve implements the resolve.Resolver interface.
//
// CrossResolve attempts to resolve an import string to a rule for languages
// other than the implementing extension. lang is the language of the rule
// with the dependency.
func (rslv *ClkResolver) CrossResolve(c *config.Config, ix *resolve.RuleIndex, imp resolve.ImportSpec, lang string) []resolve.FindResult {
	var importSuffix string
	var ruleSuffix string
	var splitToken string
	if lang == "py" {
		splitToken = "."
		if strings.HasSuffix(imp.Imp, common.ClkNanobindRuleSuffix) {
			importSuffix = common.ClkNanobindRuleSuffix
			ruleSuffix = importSuffix
		} else if strings.HasSuffix(imp.Imp, common.ClkPyRuleSuffix) {
			importSuffix = common.ClkPyRuleSuffix
			ruleSuffix = importSuffix
		} else if strings.HasSuffix(imp.Imp, common.ClkPyDialRuleSuffix) {
			importSuffix = common.ClkPyDialRuleSuffix
			ruleSuffix = importSuffix
		} else if strings.HasSuffix(imp.Imp, pyProtoImportSuffix) {
			importSuffix = pyProtoImportSuffix
			ruleSuffix = pyProtoRuleSuffix
		} else {
			return nil
		}
	} else if lang == "protobuf" || lang == "proto" {
		splitToken = "/"
		if strings.HasSuffix(imp.Imp, common.ClkProtoRuleSuffix+".proto") {
			importSuffix = common.ClkProtoRuleSuffix + ".proto"
			ruleSuffix = "_" + imp.Lang
		} else {
			return nil
		}
	} else {
		return nil
	}
	importParts := strings.Split(imp.Imp, splitToken)
	var importPkg string
	var importName string
	if len(importParts) > 1 {
		importPkg = strings.Join(importParts[:len(importParts)-1], "/")
		importName = importParts[len(importParts)-1]
		importName = strings.TrimSuffix(importParts[len(importParts)-1], importSuffix)
	} else {
		importPkg = ""
		importName = strings.TrimSuffix(imp.Imp, importSuffix)
	}
	importSpec := resolve.ImportSpec{
		Lang: "clk",
		Imp:  importPkg + ":" + importName,
	}
	findResult := ix.FindRulesByImportWithConfig(c, importSpec, "clk")
	if len(findResult) > 0 {
		return []resolve.FindResult{{
			Label: label.New("", importPkg, importName+ruleSuffix),
		}}
	}
	return nil
}

func importPathToLabel(clkImport common.ClkImport) label.Label {
	var importPath = strings.Replace(clkImport.ImportPath, "::", "/", -1)
	var pkgName string
	var ruleName string
	idx := strings.LastIndex(importPath, "/")
	if idx < 0 {
		pkgName = ""
		ruleName = importPath
	} else {
		pkgName = importPath[:idx]
		ruleName = importPath[idx+1:]
	}
	return label.Label{
		Repo: clkImport.Repo,
		Pkg:  pkgName,
		Name: ruleName,
	}
}

// Set a rule attribute from a list of ClkImports
func setLabelsAttr(r *rule.Rule, name string, thisLabel label.Label, clkImports []common.ClkImport) {
	r.DelAttr(name)
	labelStrings := clkImportsToLabelStrings(thisLabel, clkImports)
	if len(labelStrings) > 0 {
		slices.Sort(labelStrings)
		r.SetAttr(name, labelStrings)
	}
}

// Set a rule attribute from a string
func setStringAttr(r *rule.Rule, name string, value string) {
	r.DelAttr(name)
	if len(value) != 0 {
		r.SetAttr(name, value)
	}
}

// Generate the outs from the generates strings
func setOutsAttr(r *rule.Rule, thisLabel label.Label, generates []string) {
	const outsAttr = "outs"
	r.DelAttr(outsAttr)
	outs := []string{}
	for _, generate := range generates {
		if generate == common.ClkCppTarget {
			outs = append(outs, thisLabel.Name+"_cc.cc")
			outs = append(outs, thisLabel.Name+"_cc.hh")
			outs = append(outs, thisLabel.Name+"_cc.inl")
		} else if generate == common.ClkCppCogTarget {
			outs = append(outs, thisLabel.Name+"_cc_dial.cc")
			outs = append(outs, thisLabel.Name+"_cc_dial.hh")
			outs = append(outs, thisLabel.Name+"_cc_dial.inl")
		} else if generate == common.ClkCppTestCogTarget {
			outs = append(outs, thisLabel.Name+"_cc_test.cc")
			outs = append(outs, thisLabel.Name+"_cc_test.hh")
			outs = append(outs, thisLabel.Name+"_cc_test.inl")
		} else if generate == common.ClkCppExeTarget || generate == common.ClkPyExeTarget {
			outs = append(outs, thisLabel.Name+"_exe.cc")
			outs = append(outs, thisLabel.Name+"_exe.hh")
			outs = append(outs, thisLabel.Name+"_exe.inl")
		} else if generate == common.ClkNanobindTarget {
			outs = append(outs, thisLabel.Name+"_nb.cc")
			outs = append(outs, thisLabel.Name+"_nb.hh")
			outs = append(outs, thisLabel.Name+"_nb.inl")
		} else if generate == common.ClkProtoTarget {
			outs = append(outs, thisLabel.Name+"_proto.proto")
		} else if generate == common.ClkProtoConvTarget {
			outs = append(outs, thisLabel.Name+"_proto_conv.cc")
			outs = append(outs, thisLabel.Name+"_proto_conv.hh")
			outs = append(outs, thisLabel.Name+"_proto_conv.inl")
		} else if generate == common.ClkPyTarget {
			outs = append(outs, thisLabel.Name+"_py.py")
		} else if generate == common.ClkPyCogTarget {
			outs = append(outs, thisLabel.Name+"_cc_dial.cc")
			outs = append(outs, thisLabel.Name+"_cc_dial.hh")
			outs = append(outs, thisLabel.Name+"_cc_dial.inl")
			outs = append(outs, thisLabel.Name+"_cc_impl.cc")
			outs = append(outs, thisLabel.Name+"_cc_impl.hh")
			outs = append(outs, thisLabel.Name+"_cc_impl.inl")
			outs = append(outs, thisLabel.Name+"_py_dial.py")
		} else if generate == common.ClkGoProtoTarget {
			// No extra outs for go_proto
		} else {
			log.Panic("Invalid clockwork generate target: ", generate)
		}
	}
	if len(outs) != 0 {
		outs = util.SSliceDedup(outs)
		slices.Sort(outs)
		r.SetAttr(outsAttr, outs)
	}
}

// Generate a list of strings from a list of ClkImports
func clkImportsToLabelStrings(thisLabel label.Label, clkImports []common.ClkImport) []string {
	var clkLabelsAsStrings []string
	for _, clkImport := range clkImports {
		clkLabel := importPathToLabel(clkImport)
		// Try to use a relative label if possible
		clkLabel = clkLabel.Rel(thisLabel.Repo, thisLabel.Pkg)
		clkLabelsAsStrings = append(clkLabelsAsStrings, clkLabel.String())
	}
	return clkLabelsAsStrings
}

var _ resolve.Resolver = &ClkResolver{}
var _ resolve.CrossResolver = &ClkResolver{}
