# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//tools/rules:cc.bzl", "cc_binary", "cc_library")
load("//tools/rules:python.bzl", "py_cc_binding")

package(default_visibility = ["//visibility:public"])

exports_files([
    # keep-sorted start
    # Export often-modified Clockwork source file for clangd indexing test
    "clk_type.cc",
    # keep-sorted end
])

cc_library(
    name = "clk_builtin_type",
    srcs = ["clk_builtin_type.cc"],
    hdrs = ["clk_builtin_type.hh"],
    deps = [
        ":clk_schema_type_lib",
        ":clk_type",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/memory:bits",
        "//jewels/memory:pointers",
        "//jewels/uuid",
        "@fmt",
        "@protobuf",
    ],
)

cc_library(
    name = "clk_enum_type",
    srcs = ["clk_enum_type.cc"],
    hdrs = ["clk_enum_type.hh"],
    deps = [
        ":clk_type",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/memory:bits",
        "//jewels/memory:pointers",
        "//jewels/uuid",
        "@fmt",
        "@protobuf",
        "@wise_enum",
    ],
)

cc_library(
    name = "clk_schema_type",
    srcs = ["clk_schema_type.cc"],
    hdrs = ["clk_schema_type.hh"],
    deps = [
        ":clk_schema_type_lib",
        ":clk_type",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/memory:pointers",
    ],
)

cc_library(
    name = "clk_schema_type_lib",
    srcs = ["clk_schema_type_lib.cc"],
    hdrs = ["clk_schema_type_lib.hh"],
    deps = [
        ":clk_type",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/memory:pointers",
        "//jewels/uuid",
        "@fmt",
        "@protobuf",
    ],
)

cc_library(
    name = "clk_type",
    srcs = ["clk_type.cc"],
    hdrs = ["clk_type.hh"],
    deps = [
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/memory:pointers",
        "//jewels/uuid",
        "@fmt",
        "@wise_enum",
    ],
)

py_cc_binding(
    name = "nb_tachyon_upgrader",
    srcs = ["nb_tachyon_upgrader.cc"],
    py_deps = ["//clockwork/serialization/py:create_upgrader"],
    # TODO(OI-3058): use the autogenerated one once cross-workspace shared libraries in nanobindings work properly
    pyi_file = "nb_tachyon_upgrader.pyi",
    deps = [
        ":tachyon_model",
        ":tachyon_python_upgrader",
        ":tachyon_upgrader",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/log_cerr",
        "@nanobind",
        "@wise_enum",
    ],
)

cc_library(
    name = "tachyon_model",
    srcs = [
        "tachyon_model.cc",
        "tachyon_model.inl",
    ],
    hdrs = ["tachyon_model.hh"],
    deps = [
        ":clk_builtin_type",
        ":clk_enum_type",
        ":clk_schema_type",
        ":clk_type",
        "//clockwork:repr_iface",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/hash:md5",
        "//jewels/log_cerr",
        "//jewels/memory:pointers",
        "@fmt",
        "@protobuf",
    ],
)

cc_library(
    name = "tachyon_python_upgrader",
    srcs = [
        "tachyon_python_upgrader.cc",
        "tachyon_python_upgrader.inl",
    ],
    hdrs = ["tachyon_python_upgrader.hh"],
    deps = [
        ":clk_type",
        ":tachyon_model",
        ":tachyon_upgrader",
        "//clockwork:repr_iface",
        "//clockwork/python:gil_lock_guard",
        "//clockwork/python:python_object",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "@wise_enum",
    ],
)

cc_library(
    name = "tachyon_upgrader",
    srcs = [
        "tachyon_upgrader.cc",
        "tachyon_upgrader.inl",
    ],
    hdrs = ["tachyon_upgrader.hh"],
    deps = [
        ":clk_type",
        ":tachyon_model",
        "//clockwork:repr_iface",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/memory:pointers",
        "@fmt",
        "@wise_enum",
    ],
)

cc_binary(
    name = "validate_logged_channel_metadata",
    srcs = ["validate_logged_channel_metadata.cc"],
    deps = [
        ":tachyon_model",
        "//clockwork/serialization/metadata:tachyon_model_cc_library",
        "//jewels/log_cerr",
        "@tclap",
    ],
)

sh_binary(
    name = "validate_logged_channel_metadata_test",
    srcs = ["validate_logged_channel_metadata_test.sh"],
    visibility = ["//visibility:public"],
)
