# Autogenerated .pyi file for nb_cpp_upgrader.
#
# This has to be here because it depends on aws_init.so in the @clockwork bazel workspace,
# which the nanobind stub generator has issues with.
#
# TODO(OI-3058): autogenerate this once cross-workspace shared libraries in nanobindings work properly.

class TachyonCppUpgrader:
    def __init__(
        self,
        current_class_name: str,
        current_metadata: bytes,
        incoming_metadata: bytes,
    ) -> None:
        """Constructor."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def upgrade(
        self,
        src_data: memoryview,
        dest_data: memoryview,
    ) -> None:
        """Upgrade message to the current schema."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def upgrade_required(self) -> bool:
        """Upgrade required."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def upgrader_type(self) -> str:
        """Upgrader type."""  # noqa: PYI021 (Nanobind stubs need docstrings)

class TachyonPythonUpgrader:
    def __init__(
        self,
        current_module_name: str,
        current_source_file_name: str,
        current_class_name: str,
        current_metadata: bytes,
        incoming_metadata: bytes,
        incoming_schema_name: str,
    ) -> None:
        """Constructor."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def upgrade(
        self,
        src_data: memoryview,
        dest_data: memoryview,
    ) -> None:
        """Upgrade message to the current schema."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def upgrade_required(self) -> bool:
        """Upgrade required."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def upgrader_type(self) -> str:
        """Upgrader type."""  # noqa: PYI021 (Nanobind stubs need docstrings)

def validate_logged_channel_metadata(arg0: bytes, arg1: bytes, /) -> bool:
    """Check that the previous logged channel metadata can be upgraded to the current logged channel metadata."""  # noqa: PYI021 (Nanobind stubs need docstrings)
