load("//clockwork:rules.bzl", "clk")

# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//tools/rules:cc.bzl", "cc_binary", "cc_library")
load("//tools/rules:python.bzl", "py_binary", "py_library")

# Export simplelaunch_config_test.sh so it's available for simplelaunch_config_test targets
exports_files([
    "simplelaunch_config_test.sh",
])

cc_binary(
    name = "simplelaunch",
    srcs = ["simplelaunch.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":config",
        ":simplelaunch_impl",
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/common:simplelaunch_runner_config_clk_cc",
        "//jewels/container:compare",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@tclap",
    ],
)

cc_library(
    name = "child_process",
    srcs = ["child_process.cc"],
    hdrs = ["child_process.hh"],
    deps = [
        ":config",
        ":cpu_affinity",
        ":simplelaunch_status_clk_cc",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/simplelaunch/v1:service_cc_library",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@boost.asio",
        "@boost.system",
        "@fmt",
    ],
)

py_binary(
    name = "cli_client",
    srcs = ["cli_client.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":client",
        "//jewels/simplelaunch/v1:service_py_library",
        "@clockwork_pip//click",
        "@clockwork_pip//rich",
    ],
)

py_library(
    name = "client",
    srcs = ["client.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/simplelaunch/v1:service_py_library",
        "@clockwork_pip//requests",
    ],
)

cc_library(
    name = "config",
    srcs = ["config.cc"],
    hdrs = ["config.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/log_cerr",
        "//jewels/simplelaunch/v1:config_cc_library",
        "//jewels/std:expected",
        "@protobuf",
    ],
)

cc_binary(
    name = "config_tool",
    srcs = ["config_tool.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":config",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@protobuf",
        "@tclap",
    ],
)

cc_library(
    name = "cpu_affinity",
    srcs = ["cpu_affinity.cc"],
    hdrs = ["cpu_affinity.hh"],
    deps = ["//jewels/log_cerr"],
)

py_binary(
    name = "dump_system",
    srcs = ["dump_system.py"],
    deps = ["@clockwork_pip//click"],
)

bzl_library(
    name = "rules_bzl",
    srcs = ["rules.bzl"],
    visibility = ["//visibility:public"],
    deps = ["@rules_shell//shell:rules_bzl"],
)

cc_library(
    name = "service",
    srcs = ["service.cc"],
    hdrs = ["service.hh"],
    deps = [
        ":child_process",
        ":config",
        ":simplelaunch_status_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/common:platform_diagnostics_config_clk_cc",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/common:simplelaunch_runner_config_clk_cc",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/diagnostics:reporter",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:abstract_channel_factory",
        "//clockwork/pinion:buffer_layout",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/runners:epoll_manager",
        "//clockwork/scaffolding:channels",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/simplelaunch/v1:service_cc_library",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@abseil-cpp//absl/status",
        "@boost.asio",
        "@boost.beast",
        "@boost.system",
        "@fmt",
        "@protobuf",
        "@wise_enum",
    ],
)

clk(
    name = "simplelaunch_channel_policies_clk",
    srcs = ["simplelaunch_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":simplelaunch_channels_clk",
        "//clockwork/logging:channel_policy_clk",
    ],
)

clk(
    name = "simplelaunch_channels_clk",
    srcs = ["simplelaunch_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [":simplelaunch_status_clk"],
)

sh_binary(
    name = "simplelaunch_config_test",
    srcs = ["simplelaunch_config_test.sh"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "simplelaunch_impl",
    srcs = ["simplelaunch_impl.cc"],
    hdrs = ["simplelaunch_impl.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":config",
        ":simplelaunch_runner",
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/common:simplelaunch_runner_config_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/simplelaunch/v1:config_cc_library",
        "//jewels/std:expected",
        "//jewels/utility:fix_clockwork_path",
        "@boost.fusion",
        "@boost.process",
        "@fmt",
        "@protobuf",
    ],
)

cc_library(
    name = "simplelaunch_runner",
    srcs = ["simplelaunch_runner.cc"],
    hdrs = ["simplelaunch_runner.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":service",
        "//clockwork:repr_iface",
        "//clockwork/common:simplelaunch_runner_config_clk_cc",
        "//clockwork/pinion:abstract_channel_factory",
        "//clockwork/runners:epoll_manager",
        "//jewels/callsig:outcome",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/simplelaunch/v1:config_cc_library",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "@boost.asio",
        "@boost.system",
    ],
)

clk(
    name = "simplelaunch_status_clk",
    srcs = ["simplelaunch_status.clk"],
    outs = [
        "simplelaunch_status_clk_cc.cc",
        "simplelaunch_status_clk_cc.hh",
        "simplelaunch_status_clk_cc.inl",
        "simplelaunch_status_clk_cc_types.cc",
        "simplelaunch_status_clk_cc_types.hh",
        "simplelaunch_status_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    visibility = ["//visibility:public"],
)
