# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "start_lifetime_as_test",
    srcs = ["start_lifetime_as_test.cc"],
    deps = [
        "//clockwork/memory:start_lifetime_as",
        "//jewels/std:span",
        "@catch2//:catch2_main",
    ],
)
