# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "fake_cog",
    hdrs = ["fake_cog.hh"],
    deps = [
        "//clockwork/cog:cog_conditions",
        "//clockwork/cog:cog_configs",
        "//clockwork/cog:cog_diagnostics",
        "//clockwork/cog:cog_infra_diagnostics",
        "//clockwork/cog:cog_inputs",
        "//clockwork/cog:cog_memory_resources",
        "//clockwork/cog:cog_publishers",
        "//clockwork/cog:cog_states",
        "//clockwork/cog:cog_statistics",
        "//clockwork/cog:cog_timers",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/diagnostics:reporter",
        "//jewels/callsig:outcome",
        "//jewels/meta:integer_sequence",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@gsl//:util",
    ],
)

clk(
    name = "mock_metrics_schemas_clk",
    srcs = ["mock_metrics_schemas.clk"],
    outs = [
        "mock_metrics_schemas_clk_cc.cc",
        "mock_metrics_schemas_clk_cc.hh",
        "mock_metrics_schemas_clk_cc.inl",
        "mock_metrics_schemas_clk_cc_types.cc",
        "mock_metrics_schemas_clk_cc_types.hh",
        "mock_metrics_schemas_clk_cc_types.inl",
    ],
    cpp_deps = [
        "//clockwork/dsl/cog:common_cog_event_metrics_clk_cc",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk_cc",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    deps = [
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
    ],
)

cc_library(
    name = "unit_test_cxx_state",
    hdrs = ["unit_test_cxx_state.hh"],
    deps = ["//jewels/memory:memory_resource"],
)

clk(
    name = "unit_test_states_clk",
    srcs = ["unit_test_states.clk"],
    outs = [
        "unit_test_states_clk_cc.cc",
        "unit_test_states_clk_cc.hh",
        "unit_test_states_clk_cc.inl",
        "unit_test_states_clk_cc_types.cc",
        "unit_test_states_clk_cc_types.hh",
        "unit_test_states_clk_cc_types.inl",
    ],
    cpp_deps = [":unit_test_cxx_state"],
    generate = ["cpp"],
)
