# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/demo_system:__subpackages__"],
)

clk(
    name = "localization_channel_policies_clk",
    srcs = ["localization_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":localization_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "localization_channels_clk",
    srcs = ["localization_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [":pose_message_clk"],
)

clk(
    name = "localization_clk",
    srcs = ["localization.clk"],
    outs = [
        "localization_clk_cc.cc",
        "localization_clk_cc.hh",
        "localization_clk_cc.inl",
        "localization_clk_cc_cog.cc",
        "localization_clk_cc_cog.hh",
        "localization_clk_cc_cog.inl",
        "localization_clk_cc_dial.cc",
        "localization_clk_cc_dial.hh",
        "localization_clk_cc_dial.inl",
        "localization_clk_cc_types.cc",
        "localization_clk_cc_types.hh",
        "localization_clk_cc_types.inl",
        "localization_clk_exe.cc",
        "localization_clk_exe.hh",
        "localization_clk_exe.inl",
    ],
    cpp_deps = [
        ":localization_state_clk_cc",
        ":pose_message_clk_cc",
        "//clockwork/examples/demo_system/gps:gps_message_clk_cc",
        "//clockwork/examples/demo_system/imu:imu_message_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [
        ":localization_channels_clk",
        ":localization_state_clk",
        ":pose_message_clk",
        "//clockwork/examples/demo_system:cpu_domain_clk",
        "//clockwork/examples/demo_system/gps:gps_channels_clk",
        "//clockwork/examples/demo_system/gps:gps_message_clk",
        "//clockwork/examples/demo_system/imu:imu_channels_clk",
        "//clockwork/examples/demo_system/imu:imu_message_clk",
    ],
)

cc_library(
    name = "localization_clk_cc_impl",
    srcs = ["localization_clk_cc_impl.cc"],
    deps = [
        ":localization_clk_cc_dial",
        ":localization_state_clk_cc",
        ":pose_message_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/examples/demo_system/gps:gps_message_clk_cc",
        "//clockwork/examples/demo_system/imu:imu_message_clk_cc",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/uuid",
    ],
)

clk(
    name = "localization_state_clk",
    srcs = ["localization_state.clk"],
    outs = [
        "localization_state_clk_cc.cc",
        "localization_state_clk_cc.hh",
        "localization_state_clk_cc.inl",
        "localization_state_clk_cc_types.cc",
        "localization_state_clk_cc_types.hh",
        "localization_state_clk_cc_types.inl",
    ],
    cpp_deps = [":pose_message_clk_cc"],
    generate = ["cpp"],
    deps = [":pose_message_clk"],
)

cc_library(
    name = "pose_filter",
    srcs = [
        "pose_filter.cc",
        "pose_filter.inl",
    ],
    hdrs = ["pose_filter.hh"],
    deps = [
        ":pose_message_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/dial:msg_input",
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
        "@fmt",
    ],
)

clk(
    name = "pose_message_clk",
    srcs = ["pose_message.clk"],
    outs = [
        "pose_message_clk_cc.cc",
        "pose_message_clk_cc.hh",
        "pose_message_clk_cc.inl",
        "pose_message_clk_cc_types.cc",
        "pose_message_clk_cc_types.hh",
        "pose_message_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)
