# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/demo_system:__subpackages__"],
)

clk(
    name = "camera_clk",
    srcs = ["camera.clk"],
    outs = [
        "camera_clk_cc.cc",
        "camera_clk_cc.hh",
        "camera_clk_cc.inl",
        "camera_clk_cc_cog.cc",
        "camera_clk_cc_cog.hh",
        "camera_clk_cc_cog.inl",
        "camera_clk_cc_dial.cc",
        "camera_clk_cc_dial.hh",
        "camera_clk_cc_dial.inl",
        "camera_clk_cc_types.cc",
        "camera_clk_cc_types.hh",
        "camera_clk_cc_types.inl",
        "camera_clk_exe.cc",
        "camera_clk_exe.hh",
        "camera_clk_exe.inl",
    ],
    cpp_deps = [
        ":camera_state",
        ":video_message_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [
        ":video_channels_clk",
        ":video_message_clk",
        "//clockwork/examples/demo_system:cpu_domain_clk",
    ],
)

cc_library(
    name = "camera_clk_cc_impl",
    srcs = ["camera_clk_cc_impl.cc"],
    deps = [
        ":camera_clk_cc_dial",
        ":video_message_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "camera_state",
    srcs = ["camera_state.cc"],
    hdrs = ["camera_state.hh"],
    deps = ["//jewels/memory:memory_resource"],
)

clk(
    name = "video_channel_policies_clk",
    srcs = ["video_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":video_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "video_channels_clk",
    srcs = ["video_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [":video_message_clk"],
)

clk(
    name = "video_message_clk",
    srcs = ["video_message.clk"],
    outs = [
        "video_message_clk_cc.cc",
        "video_message_clk_cc.hh",
        "video_message_clk_cc.inl",
        "video_message_clk_cc_types.cc",
        "video_message_clk_cc_types.hh",
        "video_message_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)
