# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

clk(
    name = "approx_aligner_cog_clk",
    srcs = ["approx_aligner_cog.clk"],
    outs = [
        "approx_aligner_cog_clk_cc.cc",
        "approx_aligner_cog_clk_cc.hh",
        "approx_aligner_cog_clk_cc.inl",
        "approx_aligner_cog_clk_cc_dial.cc",
        "approx_aligner_cog_clk_cc_dial.hh",
        "approx_aligner_cog_clk_cc_dial.inl",
    ],
    cpp_deps = [
        ":approx_aligner_msgs_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_cc",
    ],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [
        ":approx_aligner_msgs_clk",
        "//clockwork/dial:approx_aligner_config_clk",
    ],
)

cc_library(
    name = "approx_aligner_cog_clk_cc_impl",
    srcs = ["approx_aligner_cog_clk_cc_impl.cc"],
    deps = [
        ":approx_aligner_cog_clk_cc_dial",
        ":approx_aligner_msgs_clk_cc",
        "//clockwork/dial:alignment_type_clk_cc",
        "//clockwork/dial:approx_aligner",
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/dial:approx_aligner_policies",
        "//clockwork/pinion:publishable",
        "//jewels/container:circular_buffer",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "@boost//:iterator",
    ],
)

clk(
    name = "approx_aligner_msgs_clk",
    srcs = ["approx_aligner_msgs.clk"],
    outs = [
        "approx_aligner_msgs_clk_cc.cc",
        "approx_aligner_msgs_clk_cc.hh",
        "approx_aligner_msgs_clk_cc.inl",
    ],
    cpp_deps = ["//clockwork/dial:approx_aligner_config_clk_cc"],
    generate = ["cpp"],
    deps = ["//clockwork/dial:approx_aligner_config_clk"],
)
