# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "casing_test",
    srcs = ["casing_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/common:process_description",
        "//clockwork/diagnostics:report",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_subscriber",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/pinion/tests/support:tmp_shm_namespace",
        "//clockwork/scaffolding",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:casing",
        "//clockwork/scaffolding/tests/support:runtime_tools",
        "//clockwork/scaffolding/tests/support:test_cogs",
        "//clockwork/scaffolding/tests/support:test_cogs_impl",  # keep
        "//clockwork/scaffolding/tests/support:test_io_connections",
        "//clockwork/scaffolding/tests/support:test_msgs",
        "//clockwork/scaffolding/tests/support:test_msgs_proto_cc_library",
        "//clockwork/scaffolding/tests/support:test_msgs_proto_conv",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
        "@xxhash",
    ],
)

cc_test(
    name = "channels_test",
    srcs = ["channels_test.cc"],
    linkopts = ["-lpthread"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//clockwork/pinion:shm_subscriber",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/pinion/tests/support:tmp_shm_namespace",
        "//clockwork/runners:epoll_manager",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:channels",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:monitor_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@trompeloeil",
        "@xxhash",
    ],
)

cc_test(
    name = "cog_test",
    srcs = ["cog_test.cc"],
    deps = [
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:process_description",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:cog",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@trompeloeil",
    ],
)

cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    deps = [
        "//clockwork:tags",
        "//clockwork/common:process_description",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:config",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:file",
        "//jewels/memory:memory_resource",
        "//jewels/memory:monitor_resource",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@trompeloeil",
    ],
)

cc_test(
    name = "deterministic_logging_config_test",
    srcs = ["deterministic_logging_config_test.cc"],
    deps = [
        "//clockwork/common:exec_tools",
        "//clockwork/logging:channel_publisher_config",
        "//clockwork/logging:channel_type",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging/offboard:types",
        "//clockwork/logging/offboard:writer",
        "//clockwork/scaffolding:deterministic_logging_config",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:file",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@tclap",
    ],
)

cc_test(
    name = "memory_test",
    srcs = ["memory_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:memory",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:monitor_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@trompeloeil",
        "@xxhash",
    ],
)

cc_test(
    name = "scaffolding_test",
    srcs = ["scaffolding_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description",
        "//clockwork/common/tests/support:fake_cog",
        "//clockwork/io:network_var_packet",
        "//clockwork/io:var_packet",
        "//clockwork/logging:channel_publisher_config",
        "//clockwork/logging:log_writer_config",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:incoming_udp",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:outgoing_udp",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:sock_opt",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/detail:socket_payload",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/pinion/tests/support:sockets",
        "//clockwork/pinion/tests/support:tmp_shm_namespace",
        "//clockwork/scaffolding",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:end_process_exception",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//clockwork/scaffolding/tests/support:runtime_tools",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:error_code",
        "//jewels/memory:bits",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
        "@trompeloeil",
    ],
)

cc_test(
    name = "state_test",
    srcs = ["state_test.cc"],
    deps = [
        "//clockwork:tags",
        "//clockwork/common:process_description",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion/tests/support:tmp_shm_namespace",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:memory",
        "//clockwork/scaffolding:state",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//clockwork/scaffolding/tests/support:runtime_tools",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/memory:monitor_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@trompeloeil",
        "@xxhash",
    ],
)

cc_test(
    name = "timer_test",
    srcs = ["timer_test.cc"],
    deps = [
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description",
        "//clockwork/pinion:observer",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/runners:epoll_manager",
        "//clockwork/runners:timerfd_timer",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:timer",
        "//clockwork/scaffolding/tests/support:mock_casing",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@trompeloeil",
        "@xxhash",
    ],
)
