# Copyright 2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Infrastructure report group generation for aligner execution metrics.

Generates two report groups per aligner cog (mirroring cog metrics):
- cog_event_metrics_group (batched): per-execution event data
- cog_telemetry_metrics_group (post-aggregated): aggregated telemetry data

Generation is controlled via AlignerEventMetricsPolicy and
AlignerTelemetryMetricsPolicy, which share the same schema as the
corresponding cog metric policies.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from clockwork.dsl.cog import aligner_metrics_policy
from clockwork.dsl.ir import node, policy, typesys
from clockwork.dsl.ir.cog_metrics_report_groups import (
    EVENT_METRICS_GROUP_NAME,
    TELEMETRY_METRICS_GROUP_NAME,
    build_event_config,
    build_event_metrics_report_group,
    build_telemetry_config,
    build_telemetry_metrics_report_group,
    load_signals,
    resolve_policy_config,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

    from clockwork.dsl.ir.report_group import ReportGroupDef


def generate_aligner_metrics_report_groups(  # noqa: PLR0913 mitigated by use of kwargs
    *,
    module: node.Module,
    parent_scope: node.Scope,
    aligner: typesys.NamedValue,
    input_names: Sequence[str],
    output_names: Sequence[str],
    condition_names: Sequence[str],
) -> dict[str, ReportGroupDef]:
    """Generate infrastructure cog metrics report groups for an aligner.

    Both event and telemetry report groups are generated by default for all
    aligners.  Generation is controlled via AlignerEventMetricsPolicy and
    AlignerTelemetryMetricsPolicy.  A policy with ``enabled = false``
    suppresses the corresponding group.

    Returns an empty dict when the policy system is unavailable (e.g. no
    filesystem importer in tests).

    Args:
        module: The module containing the aligner.
        parent_scope: The scope under which report groups are defined (the
            synthetic cog's inner scope).
        aligner: The Aligner IR node, used as the policy lookup target.
        input_names: Names of the aligner inputs to generate per-input signals.
        output_names: Names of the aligner outputs (typically ``["alignment"]``).
        condition_names: Names of execution conditions on the synthetic cog.

    Returns:
        A dict mapping group name to ReportGroupDef for each enabled group.
    """
    try:
        event_metrics_policy = aligner_metrics_policy.get_aligner_event_metrics_policy(module.context)
        telemetry_metrics_policy = aligner_metrics_policy.get_aligner_telemetry_metrics_policy(module.context)
    except (TypeError, RuntimeError, FileNotFoundError):
        # Policy system unavailable (e.g. non-filesystem importer in tests).
        return {}

    event_pd = policy.lookup_policy(module, event_metrics_policy, aligner)
    telemetry_pd = policy.lookup_policy(module, telemetry_metrics_policy, aligner)

    result: dict[str, ReportGroupDef] = {}

    event_enabled, event_config = resolve_policy_config(event_pd, build_event_config)
    telemetry_enabled, telemetry_config = resolve_policy_config(telemetry_pd, build_telemetry_config)

    if not event_enabled and not telemetry_enabled:
        return result

    sigs = load_signals(module)

    if event_enabled:
        event_rg = build_event_metrics_report_group(
            cog_name=aligner.name,
            module=module,
            scope=parent_scope,
            signals=sigs,
            input_names=input_names,
            output_names=output_names,
            condition_names=condition_names,
            memory_resource_names=[],
            config=event_config,
        )
        parent_scope.define(event_rg.name, event_rg, module.terminals)
        result[EVENT_METRICS_GROUP_NAME] = event_rg

    if telemetry_enabled:
        telemetry_rg = build_telemetry_metrics_report_group(
            cog_name=aligner.name,
            module=module,
            scope=parent_scope,
            signals=sigs,
            input_names=input_names,
            output_names=output_names,
            condition_names=condition_names,
            memory_resource_names=[],
            config=telemetry_config,
        )
        parent_scope.define(telemetry_rg.name, telemetry_rg, module.terminals)
        result[TELEMETRY_METRICS_GROUP_NAME] = telemetry_rg

    return result
