# Copyright 2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Infrastructure report group generation for cog execution metrics.

Generates two report groups per non-init cog:
- cog_event_metrics_group (batched): per-execution event data
- cog_telemetry_metrics_group (post_aggregated): aggregated telemetry data
"""

from __future__ import annotations

import uuid
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING

from clockwork.dsl.cog import cog_metrics_policy
from clockwork.dsl.ir import clkbuiltins, node, policy, primitive, signal, typesys, units
from clockwork.dsl.ir import schema as schema_mod
from clockwork.dsl.ir.importer_registry import IMPORTER_REGISTRY_KEY
from clockwork.dsl.ir.module_id import CLK_REPO, ModuleID
from clockwork.dsl.ir.report_group import (
    ReportGroupConfig,
    ReportGroupDef,
    ReportGroupEntry,
    ReportGroupLogType,
    ReportingStrategy,
    extract_duration_value,
    extract_int_value,
)
from clockwork.dsl.serialization import tachyon_layout, tachyon_layout_reg, tachyon_reg

if TYPE_CHECKING:
    from collections.abc import Callable, Mapping, Sequence

_SIGNALS_MODULE_PATH = Path("clockwork/dsl/cog/cog_execution_metrics_signals.clk")

EVENT_METRICS_GROUP_NAME = "cog_event_metrics_group"
TELEMETRY_METRICS_GROUP_NAME = "cog_telemetry_metrics_group"

# Prefix applied to shared signal entry names in the telemetry group to avoid
# identifier collisions with the event group in the generated signal API.
TELEMETRY_SIGNAL_PREFIX = "agg_"

_DEFAULT_EVENT_BATCH_SIZE = 10

# Global (per-cog) signals
_GLOBAL_SIGNALS = (
    "cog_exec_duration",
    "execute_cog_wall_duration",
    "execute_cog_thread_cpu_duration",
    "execute_cog_thread_user_duration",
    "execute_cog_thread_system_duration",
    "cog_ready_to_exec_latency",
    "cog_attempt_to_exec_latency",
    "cog_requeue_count",
)

_TELEMETRY_METRICS_ONLY_SIGNALS = ("cog_exec_period",)

_EVENT_METRICS_ONLY_SIGNALS = ("cog_dial_start_time", "cog_exec_start_time")

# Per-input signals: (signal_name, alias_suffix)
_PER_INPUT_SIGNALS = (
    ("input_unseen_messages", "unseen_messages"),
    ("input_staleness", "staleness"),
    ("input_dropped_messages", "dropped_messages"),
)

# Per-output signals: (signal_name, alias_suffix)
_PER_OUTPUT_SIGNALS = (("output_num_messages", "num_messages"),)
_PER_OUTPUT_SEQUENCE_NUMBER_SIGNALS = (("output_first_sequence_number", "first_sequence_number"),)

# Per-condition signals: (signal_name, alias_suffix)
_PER_CONDITION_SIGNALS_EVENT = (("execution_condition_active", "active"),)
_PER_CONDITION_SIGNALS_TELEMETRY = (("execution_condition_active_count", "active_count"),)

# Per-memory resource signals: (signal_name, alias_suffix)
_PER_MEMORY_RESOURCE_SIGNALS_EVENT = (
    ("memory_resource_peak_allocated", "peak_allocated"),
    ("memory_resource_current_allocated", "current_allocated"),
    ("memory_resource_total_allocated", "total_allocated"),
    ("memory_resource_total_deallocated", "total_deallocated"),
)
_PER_MEMORY_RESOURCE_SIGNALS_TELEMETRY = (("memory_resource_peak_allocated", "peak_allocated"),)

_TELEMETRY_POST_AGGREGATION = frozenset(
    {
        signal.AggregationType.MIN,
        signal.AggregationType.MAX,
        signal.AggregationType.MEAN,
    }
)

_CONDITION_COUNT_POST_AGGREGATION = frozenset(
    {
        signal.AggregationType.VALUE,
    }
)

_ONE_SECOND = primitive.UnitValue.make(Decimal(1), units.SECONDS)


def resolve_policy_config(
    pd: policy.PolicyData | None,
    config_builder: Callable[[dict[str, typesys.Value]], ReportGroupConfig],
) -> tuple[bool, ReportGroupConfig | None]:
    """Resolve enabled state and optional config from a policy data instance.

    Returns ``(True, None)`` when no policy is applied (default enabled, no
    custom config).  Returns ``(False, None)`` when the policy explicitly
    disables the group.  Otherwise returns ``(True, config)``.
    """
    if pd is None:
        return True, None
    schema_data = pd.data.data
    enabled = primitive.value_to_bool(schema_data["enabled"])
    if not enabled:
        return False, None
    return True, config_builder(schema_data)


def generate_cog_metrics_report_groups(  # noqa: PLR0913 Too many args mitigated by kwonly args
    *,
    is_init: bool,
    module: node.Module,
    parent_scope: node.Scope,
    cog: typesys.NamedValue,
    input_names: Sequence[str],
    output_names: Sequence[str],
    condition_names: Sequence[str],
    memory_resource_names: Sequence[str],
    input_view_sizes: Mapping[str, int] | None = None,
) -> dict[str, ReportGroupDef]:
    """Generate infrastructure cog metrics report groups for a cog.

    Both event and telemetry report groups are generated by default for all
    non-init cogs.  Signal-based report groups are controlled independently
    of the legacy ``metrics_options`` block via ``CogEventMetricsPolicy`` and
    ``CogTelemetryMetricsPolicy``.  A policy with ``enabled = false``
    suppresses the corresponding group.

    Returns an empty dict when the cog is an init cog or when the policy
    system is unavailable (e.g. no filesystem importer in tests).

    Policy uniqueness per cog is enforced by the policy registration system;
    duplicate policies for the same cog raise a compiler error at registration
    time.
    """
    if is_init:
        return {}

    try:
        event_metrics_policy = cog_metrics_policy.get_cog_event_metrics_policy(module.context)
        telemetry_metrics_policy = cog_metrics_policy.get_cog_telemetry_metrics_policy(module.context)
    except (TypeError, RuntimeError, FileNotFoundError):
        # Policy system unavailable (e.g. non-filesystem importer in tests).
        return {}
    event_pd = policy.lookup_policy(module, event_metrics_policy, cog)
    telemetry_pd = policy.lookup_policy(module, telemetry_metrics_policy, cog)

    result: dict[str, ReportGroupDef] = {}

    event_enabled, event_config = resolve_policy_config(event_pd, build_event_config)
    telemetry_enabled, telemetry_config = resolve_policy_config(telemetry_pd, build_telemetry_config)

    if not event_enabled and not telemetry_enabled:
        return result

    # Determine whether sequence numbers metadata should be emitted (default: True).
    emit_seqno = True
    if event_pd is not None:
        emit_seqno_val = event_pd.data.data.get("emit_sequence_numbers")
        if emit_seqno_val is not None:
            emit_seqno = primitive.value_to_bool(emit_seqno_val)

    sigs = load_signals(module)

    if event_enabled:
        event_metrics_report_group = build_event_metrics_report_group(
            cog_name=cog.name,
            module=module,
            scope=parent_scope,
            signals=sigs,
            input_names=input_names,
            output_names=output_names,
            condition_names=condition_names,
            memory_resource_names=memory_resource_names,
            config=event_config,
            input_view_sizes=input_view_sizes if emit_seqno else None,
        )
        parent_scope.define(event_metrics_report_group.name, event_metrics_report_group, module.terminals)
        result[EVENT_METRICS_GROUP_NAME] = event_metrics_report_group

    if telemetry_enabled:
        telemetry_metrics_report_group = build_telemetry_metrics_report_group(
            cog_name=cog.name,
            module=module,
            scope=parent_scope,
            signals=sigs,
            input_names=input_names,
            output_names=output_names,
            condition_names=condition_names,
            memory_resource_names=memory_resource_names,
            config=telemetry_config,
        )
        parent_scope.define(telemetry_metrics_report_group.name, telemetry_metrics_report_group, module.terminals)
        result[TELEMETRY_METRICS_GROUP_NAME] = telemetry_metrics_report_group

    return result


def build_event_config(schema_data: dict[str, typesys.Value]) -> ReportGroupConfig:
    """Build a ReportGroupConfig for event metrics from policy schema data."""
    batch_size = extract_int_value(schema_data, "batch_size")
    return ReportGroupConfig(
        reporting_strategy=ReportingStrategy.BATCHED,
        log_type=ReportGroupLogType.EVENT,
        min_observations=None,
        max_observations=batch_size if batch_size is not None else _DEFAULT_EVENT_BATCH_SIZE,
        min_duration=extract_duration_value(schema_data, "min_duration"),
        max_duration=extract_duration_value(schema_data, "max_duration") or _ONE_SECOND,
    )


def build_telemetry_config(schema_data: dict[str, typesys.Value]) -> ReportGroupConfig:
    """Build a ReportGroupConfig for telemetry metrics from policy schema data."""
    return ReportGroupConfig(
        reporting_strategy=ReportingStrategy.POST_AGGREGATED,
        log_type=ReportGroupLogType.NON_REDUNDANT_TELEMETRY,
        min_observations=extract_int_value(schema_data, "min_observations"),
        max_observations=extract_int_value(schema_data, "max_observations"),
        min_duration=extract_duration_value(schema_data, "min_duration"),
        max_duration=extract_duration_value(schema_data, "max_duration") or _ONE_SECOND,
    )


def load_signals(module: node.Module) -> dict[str, signal.Signal]:
    """Load signal definitions from the cog execution metrics signals module."""
    registry = module.context[IMPORTER_REGISTRY_KEY]
    if registry.importer is None:
        msg = "No importer registered in compiler context"
        raise RuntimeError(msg)

    import_repo = "" if module.module_id.repo == CLK_REPO else CLK_REPO
    signals_module_id = ModuleID.from_path(CLK_REPO, _SIGNALS_MODULE_PATH)
    signals_mod = registry.importer.try_cached_load(signals_module_id)
    if signals_mod is None:
        use_result = node.Module.UseResult(
            repo=import_repo,
            path=("clockwork", "dsl", "cog", "cog_execution_metrics_signals"),
            alias=None,
            use_targets=None,
            use_type=node.UseResultType.module,
            cst_node=None,
        )
        spec = registry.importer.resolve_import(module, use_result)
        signals_mod, _ = registry.importer.execute_import(spec, module, use_result)

    # Merge the signals module's compiler context into the calling module's
    # context so that type registries (tachyon layout, signal registry, etc.)
    # are available. This must run on every call, not just the first compile,
    # because each calling module needs the registrations in its own context.
    module.context.import_from(signals_mod.context)

    result: dict[str, signal.Signal] = {}
    all_signal_names = (
        list(_GLOBAL_SIGNALS)
        + list(_EVENT_METRICS_ONLY_SIGNALS)
        + list(_TELEMETRY_METRICS_ONLY_SIGNALS)
        + [name for name, _ in _PER_INPUT_SIGNALS]
        + [name for name, _ in _PER_OUTPUT_SIGNALS]
        + [name for name, _ in _PER_OUTPUT_SEQUENCE_NUMBER_SIGNALS]
        + [name for name, _ in _PER_CONDITION_SIGNALS_EVENT]
        + [name for name, _ in _PER_CONDITION_SIGNALS_TELEMETRY]
        + [name for name, _ in _PER_MEMORY_RESOURCE_SIGNALS_EVENT]
        + [name for name, _ in _PER_MEMORY_RESOURCE_SIGNALS_TELEMETRY]
    )
    for name in all_signal_names:
        sig = signals_mod.inner_scope.lookup(name)
        if sig is None:
            msg = f"Signal '{name}' not found in cog_execution_metrics_signals module"
            raise ValueError(msg)
        if not isinstance(sig, signal.Signal):
            msg = f"Expected Signal '{name}' to be a Signal, but got {type(sig).__name__}"
            raise TypeError(msg)
        sig.resolve()
        result[name] = sig
    return result


def _register_metadata_schema(module: node.Module, inst: schema_mod.InstantiatedSchema) -> None:
    """Register a generated metadata schema's tachyon layout if needed."""
    if tachyon_reg.constraint_for_type(module.context, inst) is None:
        layout = tachyon_layout.layout_schema(module.context, inst)
        tachyon_layout_reg.register_structured_type(module.context, inst, layout)


def _make_input_seqno_metadata(
    *, cog_name: str, input_name: str, view_size: int, module: node.Module
) -> schema_mod.InstantiatedSchema:
    """Create a bespoke sequence-numbers metadata schema for a single cog input.

    Each cog input gets its own dedicated schema whose ``message_sequence_numbers``
    array is sized to that input's view size.  Generating a unique schema per
    input (rather than sharing a single parameterized ``InputViewSequenceNumbers``
    instantiation across cogs) avoids ODR violations that arise when the same
    parameterized type is instantiated with differing view sizes in different
    translation units.

    The schema's tachyon layout is registered so that report group schema
    generation can compute field sizes.
    """
    schema_name = f"{cog_name}_{input_name}_SequenceNumbers"
    message_sequence_numbers_type = typesys.Instantiation(
        type_info=clkbuiltins.TYPE_TYPE,
        instantiates=clkbuiltins.VAR_ARRAY,
        arguments={
            "type": clkbuiltins.UINT64,
            "max_size": primitive.DecimalValue(clkbuiltins.UINT64, Decimal(view_size)),
        },
    )
    fields = [
        schema_mod.make_field(
            module,
            1,
            "message_sequence_numbers",
            message_sequence_numbers_type,
            doc="Sequence numbers for messages",
        ),
        schema_mod.make_field(
            module,
            2,
            "cursor_position",
            clkbuiltins.UINT64,
            doc="Cursor position for the input view. Represents the position of the first new message in the view.",
        ),
    ]
    inst = schema_mod.make_schema_class(
        name=schema_name,
        module=module,
        fields=fields,
        doc="Sequence numbers of messages visible in a cog input view",
        uuid=uuid.uuid3(clkbuiltins.CLOCKWORK_NAMESPACE_UUID, schema_name),
    )

    _register_metadata_schema(module, inst)

    return inst


def _make_entry(  # noqa: PLR0913 mitigated by keyword-only arguments
    *,
    name: str,
    sig: signal.Signal,
    module: node.Module,
    scope: node.Scope,
    instance_name: str | None = None,
    post_aggregation: frozenset[signal.AggregationType] | None = None,
    metadata_override: typesys.TypeVal | None = None,
) -> ReportGroupEntry:
    return ReportGroupEntry(
        scope=scope,
        name=name,
        module=module,
        cst_node=None,
        doc=None,
        signal=sig,
        cog_private=False,
        instance_name=instance_name,
        post_aggregation=set(post_aggregation) if post_aggregation else set(),
        post_aggregation_text=None,
        metadata_override=metadata_override,
    )


def _create_entries(  # noqa: C901, PLR0913 mitigated by helper closures and keyword-only arguments
    *,
    module: node.Module,
    scope: node.Scope,
    signals: dict[str, signal.Signal],
    input_names: Sequence[str],
    output_names: Sequence[str],
    condition_names: Sequence[str],
    memory_resource_names: Sequence[str],
    post_aggregation: frozenset[signal.AggregationType] | None = None,
    condition_post_aggregation: frozenset[signal.AggregationType] | None = None,
    shared_signal_prefix: str = "",
    input_view_sizes: Mapping[str, int] | None = None,
    cog_name: str = "",
) -> dict[str, ReportGroupEntry]:
    entries: dict[str, ReportGroupEntry] = {}

    def _add_signal_entries(
        signal_names: Sequence[str],
        override_post_agg: frozenset[signal.AggregationType] | None = None,
        name_prefix: str = "",
    ) -> None:
        """Add entries for direct signals without aliases."""
        effective_post_agg = override_post_agg or post_aggregation
        for sig_name in signal_names:
            entry_name = f"{name_prefix}{sig_name}"
            entries[entry_name] = _make_entry(
                name=entry_name,
                sig=signals[sig_name],
                module=module,
                scope=scope,
                post_aggregation=effective_post_agg,
            )

    def _add_indexed_entries(
        names: Sequence[str],
        sig_tuples: tuple[tuple[str, str], ...],
        override_post_agg: frozenset[signal.AggregationType] | None = None,
        name_prefix: str = "",
        metadata_by_name: Mapping[str, Mapping[str, typesys.TypeVal]] | None = None,
    ) -> None:
        """Add entries for indexed signals (per-input/output/condition with aliases).

        Args:
            names: The instance names (e.g., input names).
            sig_tuples: Tuples of (signal_name, alias_suffix).
            override_post_agg: Override post-aggregation for all entries.
            name_prefix: Prefix for entry names.
            metadata_by_name: Mapping of instance_name -> {signal_name: metadata_type}.
        """
        effective_post_agg = override_post_agg if override_post_agg is not None else post_aggregation
        for name in names:
            for sig_name, alias_suffix in sig_tuples:
                entry_name = f"{name_prefix}{name}_{alias_suffix}"
                entry_metadata: typesys.TypeVal | None = None
                if metadata_by_name and name in metadata_by_name:
                    entry_metadata = metadata_by_name[name].get(sig_name)
                entries[entry_name] = _make_entry(
                    name=entry_name,
                    sig=signals[sig_name],
                    module=module,
                    scope=scope,
                    instance_name=name,
                    post_aggregation=effective_post_agg,
                    metadata_override=entry_metadata,
                )

    # Add global signals (shared signals get prefixed to avoid collisions)
    _add_signal_entries(_GLOBAL_SIGNALS, name_prefix=shared_signal_prefix)

    # Add strategy-specific signals (unique to each group, no prefix needed)
    if post_aggregation:
        _add_signal_entries(_TELEMETRY_METRICS_ONLY_SIGNALS)
    else:
        _add_signal_entries(_EVENT_METRICS_ONLY_SIGNALS)

    # Build per-input metadata for input_unseen_messages when view sizes are available.
    input_metadata: Mapping[str, Mapping[str, typesys.TypeVal]] | None = None
    if input_view_sizes is not None:
        input_metadata = {
            input_name: {
                "input_unseen_messages": _make_input_seqno_metadata(
                    cog_name=cog_name,
                    input_name=input_name,
                    view_size=input_view_sizes.get(input_name, 1),
                    module=module,
                ),
            }
            for input_name in input_names
        }

    # Add indexed signals (shared signals get prefixed)
    _add_indexed_entries(
        input_names, _PER_INPUT_SIGNALS, name_prefix=shared_signal_prefix, metadata_by_name=input_metadata
    )
    output_signals = _PER_OUTPUT_SIGNALS
    if not post_aggregation:
        output_signals += _PER_OUTPUT_SEQUENCE_NUMBER_SIGNALS
    _add_indexed_entries(output_names, output_signals, name_prefix=shared_signal_prefix)
    if post_aggregation:
        _add_indexed_entries(
            condition_names, _PER_CONDITION_SIGNALS_TELEMETRY, override_post_agg=condition_post_aggregation
        )
        _add_indexed_entries(
            memory_resource_names,
            _PER_MEMORY_RESOURCE_SIGNALS_TELEMETRY,
            override_post_agg=condition_post_aggregation,
            name_prefix=shared_signal_prefix,
        )

    else:
        _add_indexed_entries(condition_names, _PER_CONDITION_SIGNALS_EVENT)
        _add_indexed_entries(memory_resource_names, _PER_MEMORY_RESOURCE_SIGNALS_EVENT)

    return entries


def build_event_metrics_report_group(  # noqa: PLR0913 mitigated by keyword-only arguments
    *,
    cog_name: str,
    module: node.Module,
    scope: node.Scope,
    signals: dict[str, signal.Signal],
    input_names: Sequence[str],
    output_names: Sequence[str],
    condition_names: Sequence[str],
    memory_resource_names: Sequence[str],
    config: ReportGroupConfig | None = None,
    input_view_sizes: Mapping[str, int] | None = None,
) -> ReportGroupDef:
    """Build the cog_event_metrics_group report group (batched strategy)."""
    entries = _create_entries(
        module=module,
        scope=scope,
        signals=signals,
        input_names=input_names,
        output_names=output_names,
        memory_resource_names=memory_resource_names,
        condition_names=condition_names,
        input_view_sizes=input_view_sizes,
        cog_name=cog_name,
    )

    final_config = config or ReportGroupConfig(
        reporting_strategy=ReportingStrategy.BATCHED,
        log_type=ReportGroupLogType.EVENT,
        min_observations=None,
        max_observations=_DEFAULT_EVENT_BATCH_SIZE,
        min_duration=None,
        max_duration=_ONE_SECOND,
    )

    # fmt: off
    rg = ReportGroupDef(
        type_info=clkbuiltins.REPORT_GROUP_TYPE,
        # pyrefly: ignore[unexpected-keyword] # TODO(DX-3792): Address pyrefly errors ignored to migrate from pyright
        scope=scope,
        # pyrefly: ignore[unexpected-keyword] # TODO(DX-3792): Address pyrefly errors ignored to migrate from pyright
        name=EVENT_METRICS_GROUP_NAME,
        module=module,
        cst_node=None,
        doc=None,
        entries=entries,
        report_group_config=final_config,
        qualify_entry_instance_names=True,
    )
    # fmt: on
    rg.parent_cog_name = cog_name
    return rg


def build_telemetry_metrics_report_group(  # noqa: PLR0913 mitigated by keyword-only arguments
    *,
    cog_name: str,
    module: node.Module,
    scope: node.Scope,
    signals: dict[str, signal.Signal],
    input_names: Sequence[str],
    output_names: Sequence[str],
    condition_names: Sequence[str],
    memory_resource_names: Sequence[str],
    config: ReportGroupConfig | None = None,
) -> ReportGroupDef:
    """Build the cog_telemetry_metrics_group report group (post_aggregated strategy)."""
    entries = _create_entries(
        module=module,
        scope=scope,
        signals=signals,
        input_names=input_names,
        output_names=output_names,
        condition_names=condition_names,
        memory_resource_names=memory_resource_names,
        post_aggregation=_TELEMETRY_POST_AGGREGATION,
        condition_post_aggregation=_CONDITION_COUNT_POST_AGGREGATION,
        shared_signal_prefix=TELEMETRY_SIGNAL_PREFIX,
    )

    final_config = config or ReportGroupConfig(
        reporting_strategy=ReportingStrategy.POST_AGGREGATED,
        log_type=ReportGroupLogType.NON_REDUNDANT_TELEMETRY,
        min_observations=None,
        max_observations=None,
        min_duration=None,
        max_duration=_ONE_SECOND,
    )

    # fmt: off
    rg = ReportGroupDef(
        type_info=clkbuiltins.REPORT_GROUP_TYPE,
        # pyrefly: ignore[unexpected-keyword] # TODO(DX-3792): Address pyrefly errors ignored to migrate from pyright
        scope=scope,
        # pyrefly: ignore[unexpected-keyword] # TODO(DX-3792): Address pyrefly errors ignored to migrate from pyright
        name=TELEMETRY_METRICS_GROUP_NAME,
        module=module,
        cst_node=None,
        doc=None,
        entries=entries,
        report_group_config=final_config,
        qualify_entry_instance_names=True,
    )
    # fmt: on
    rg.parent_cog_name = cog_name
    return rg
