# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Common utilities used for converting between dsl representations."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePath
from typing import TYPE_CHECKING

from clockwork.dsl.compiler_context import CompilerContext
from clockwork.dsl.cpp.context import Header
from clockwork.dsl.cpp.types import CppType
from clockwork.dsl.ir import clkbuiltins, expr, schema, schema_reg, typesys
from clockwork.dsl.proto import proto_typereg

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable

    from clockwork.dsl.compiler_context import CompilerContext
    from clockwork.dsl.ir import node


@dataclass
class ConversionRegistration:
    """Info used for registering converters. This is a associated with a schema/schema instantitation."""

    # Don't use CppTarget directly here to prevent circular dependency.
    parent_target: node.NamedEntity
    conversion_type: typesys.Instantiation
    include_location: Header
    namespace: str


@dataclass
class ConversionParams:
    """Aggregate of params needed to generate the conversions."""

    compiler_context: CompilerContext
    source_name: str
    destination_name: str
    field_type: typesys.Value
    field_name: str
    enclosing_namespace: str
    is_optional: bool = False

    @property
    def proto_field_name(self) -> str:
        """Get the protobuf version of the field name."""
        return self.field_name.lower()

    @property
    def proto_getter(self) -> str:
        """The text of the getter function generated by the protobuf compiler."""
        return f"{self.source_name}.{self.proto_field_name}()"


@dataclass
class ValidationParams:
    """Aggregate of params needed to generate the validation method."""

    source_name: str
    field_type: typesys.Value
    field_name: str
    enclosing_namespace: str

    @property
    def proto_field_name(self) -> str:
        """Get the protobuf version of the field name."""
        return self.field_name.lower()

    @property
    def proto_getter(self) -> str:
        """The text of the getter function generated by the protobuf compiler."""
        return f"{self.source_name}.{self.proto_field_name}()"


@dataclass
class ValidationInfo:
    """The text used to generate the validation for a single field."""

    conversion_generator: Callable[[ValidationParams], list[str]]
    required_includes: Iterable[Header]


@dataclass
class ConversionInfo:
    """The text used to generate the conversion for a single field."""

    conversion_generator: Callable[[ConversionParams], list[str]]
    required_includes: list[Header]


@dataclass
class ConverterRegistry:
    """Object for managing the converter registry for a specific type of conversion. e.g. TAP to proto."""

    registry_dict: dict[str, ConversionRegistration]

    def in_converter_registry(self, clk_type: typesys.Value) -> bool:
        """Checks whether a schema instantiation is registered in the conversion registry."""
        return clk_type.value_key() in self.registry_dict

    def get_conversion_registration(self, clk_type: typesys.Value) -> ConversionRegistration:
        """Obtains the conversion registration for a specific schema type."""
        try:
            return self.registry_dict[clk_type.value_key()]
        except KeyError:
            msg = (
                f"No converter type registered for Clockwork type {clk_type}.\nt might be missing from a `cpp_target`."
            )
            raise TypeError(msg) from None

    def register_schema_conversion(self, clk_type: typesys.Value, conversion_info: ConversionRegistration) -> None:
        """Register a converter in the registry.

        This allows other converters to know that a conversion exists for a specific schema and to obtain its namespace.
        """
        if clk_type.value_key() in self.registry_dict:
            msg = f"Type {clk_type} already registered"
            raise ValueError(msg)

        self.registry_dict[clk_type.value_key()] = conversion_info


def to_schema_instantiation(typespec: typesys.Instantiation) -> schema.Schema | typesys.Instantiation:
    """Extract the instantiated schema type from a Protobuf instantiation."""
    if typespec.instantiates is clkbuiltins.PROTOBUF:
        schema_ir = typespec.arguments["schema"]
        if isinstance(schema_ir, schema.Schema | typesys.Instantiation):
            return schema_ir
        msg = f"Unexpected type for schema: {type(schema_ir)}"
        raise TypeError(msg)
    msg = f"Expected an instantiation of Protobuf Received: {type(typespec)}"
    raise TypeError(msg)


def to_schema(typespec: typesys.Instantiation | schema.Schema) -> schema.Schema:
    """Get the underlying schema from either a schema or a schema instantiation."""
    if isinstance(typespec, schema.Schema):
        return typespec
    if isinstance(typespec.instantiates, schema.Schema):
        return typespec.instantiates
    msg = f"Expected schema or schema instantiation: {type(typespec)}"
    raise TypeError(msg)


def protobuf_repr_to_cpp_type(proto_rep: schema_reg.RepresentationInfo, compiler_context: CompilerContext) -> CppType:
    """Creates a CppType that corresponds to the provided Representation."""
    proto_ir = proto_rep.representation_ir
    if isinstance(proto_ir.typespec, expr.Expr):
        msg = "Attempted to render an unresolved converter"
        raise TypeError(msg)
    proto_name = proto_ir.name if proto_ir.name else proto_ir.schema_ir.schema_name
    proto_type = proto_typereg.get_protobuf_type(proto_ir.schema_ir, compiler_context)
    schema_ir = to_schema_instantiation(proto_ir.typespec)
    if not isinstance(proto_type, proto_typereg.DefinedProtobufType):
        msg = "Expected a DefinedProtobufType for instantiation"
        raise TypeError(msg)
    if not proto_type.import_location:
        msg = f"Expected the proto message {proto_type.type_name} to have a defined import location"
        raise ValueError(msg)
    repo = to_schema(schema_ir).module.module_id.repo
    proto_header = Header(repo, PurePath(proto_type.import_location).with_suffix(".pb.h"))
    proto_namespace = proto_type.package_name.replace(".", "::")
    return CppType(
        includes=[proto_header],
        type_name=proto_name,
        cpp_namespace=proto_namespace,
    )
