# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

cc_library(
    name = "log_cerr",
    srcs = [
        "log_cerr.cc",
        "log_cerr.inl",
    ],
    hdrs = ["log_cerr.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":detect_log_color_mode",
        ":detect_log_threshold",
        ":log_level",
        ":log_time",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/rate_limiter:time_bucket",
        "//jewels/time:sync_time",
        "@fmt",
    ],
)

cc_library(
    name = "detect_log_color_mode",
    srcs = ["detect_log_color_mode.cc"],
    hdrs = ["detect_log_color_mode.hh"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "detect_log_threshold",
    srcs = ["detect_log_threshold.cc"],
    hdrs = ["detect_log_threshold.hh"],
    visibility = ["//visibility:private"],
    deps = [
        ":log_level",
        "@wise_enum",
    ],
)

cc_library(
    name = "log_level",
    hdrs = ["log_level.hh"],
    visibility = ["//visibility:public"],
    deps = ["@wise_enum"],
)

cc_library(
    name = "log_time",
    hdrs = ["log_time.hh"],
    visibility = ["//visibility:public"],
)
