# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/dsl/cog/tests:__subpackages__"],
)

cc_library(
    name = "copy_cog",
    srcs = [
        "copy_cog.cc",
        "copy_cog.inl",
    ],
    hdrs = ["copy_cog.hh"],
    data = [":copy_cog_clk"],
    deps = [
        ":copy_cog_dial",
        ":copy_cog_impl",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:cog_event_metrics_cpp",
        "//clockwork/dsl/cog:cog_telemetry_metrics_cpp",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
)

clk(
    name = "copy_cog_clk",
    srcs = ["copy_cog.clk"],
    outs = [
        "copy_cog.cc",
        "copy_cog.hh",
        "copy_cog.inl",
        "copy_cog_dial.cc",
        "copy_cog_dial.hh",
        "copy_cog_dial.inl",
    ],
    deps = [
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
        "//clockwork/dsl/tests/support:hellomsg_clk",
    ],
)

cc_library(
    name = "copy_cog_dial",
    srcs = [
        "copy_cog_dial.cc",
        "copy_cog_dial.inl",
    ],
    hdrs = ["copy_cog_dial.hh"],
    data = [":copy_cog_clk"],
    deps = [
        "//clockwork/dial:include_common",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
    ],
)

cc_library(
    name = "copy_cog_impl",
    srcs = ["copy_cog_impl.cc"],
    deps = [":copy_cog_dial"],
)

cc_library(
    name = "rate_limited_cog",
    srcs = [
        "rate_limited_cog.cc",
        "rate_limited_cog.inl",
    ],
    hdrs = ["rate_limited_cog.hh"],
    data = [":rate_limited_cog_clk"],
    deps = [
        ":rate_limited_cog_dial",
        ":rate_limited_cog_impl",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:cog_event_metrics_cpp",
        "//clockwork/dsl/cog:cog_telemetry_metrics_cpp",
        "//clockwork/dsl/cog:min_max_mean_cpp",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
)

clk(
    name = "rate_limited_cog_clk",
    srcs = ["rate_limited_cog.clk"],
    outs = [
        "rate_limited_cog.cc",
        "rate_limited_cog.hh",
        "rate_limited_cog.inl",
        "rate_limited_cog_dial.cc",
        "rate_limited_cog_dial.hh",
        "rate_limited_cog_dial.inl",
    ],
    deps = [
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
        "//clockwork/dsl/tests/support:hellomsg_clk",
    ],
)

cc_library(
    name = "rate_limited_cog_dial",
    srcs = [
        "rate_limited_cog_dial.cc",
        "rate_limited_cog_dial.inl",
    ],
    hdrs = ["rate_limited_cog_dial.hh"],
    data = [":rate_limited_cog_clk"],
    deps = [
        "//clockwork/dial:include_common",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
    ],
)

cc_library(
    name = "rate_limited_cog_impl",
    srcs = ["rate_limited_cog_impl.cc"],
    deps = [":rate_limited_cog_dial"],
)

cc_library(
    name = "skip_cog",
    srcs = [
        "skip_cog.cc",
        "skip_cog.inl",
    ],
    hdrs = ["skip_cog.hh"],
    data = [":skip_cog_clk"],
    deps = [
        ":skip_cog_dial",
        ":skip_cog_impl",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:cog_event_metrics_cpp",
        "//clockwork/dsl/cog:cog_telemetry_metrics_cpp",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
)

clk(
    name = "skip_cog_clk",
    srcs = ["skip_cog.clk"],
    outs = [
        "skip_cog.cc",
        "skip_cog.hh",
        "skip_cog.inl",
        "skip_cog_dial.cc",
        "skip_cog_dial.hh",
        "skip_cog_dial.inl",
    ],
    deps = [
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
        "//clockwork/dsl/tests/support:hellomsg_clk",
    ],
)

cc_library(
    name = "skip_cog_dial",
    srcs = [
        "skip_cog_dial.cc",
        "skip_cog_dial.inl",
    ],
    hdrs = ["skip_cog_dial.hh"],
    data = [":skip_cog_clk"],
    deps = [
        "//clockwork/dial:include_common",
        "//clockwork/dsl/tests/support:hello_msg_onboard",
    ],
)

cc_library(
    name = "skip_cog_impl",
    srcs = ["skip_cog_impl.cc"],
    deps = [":skip_cog_dial"],
)
