# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/dsl/cog/tests:__subpackages__"],
)

clk(
    name = "copy_cog_clk",
    srcs = ["copy_cog.clk"],
    outs = [
        "copy_cog_clk_cc.cc",
        "copy_cog_clk_cc.hh",
        "copy_cog_clk_cc.inl",
        "copy_cog_clk_cc_dial.cc",
        "copy_cog_clk_cc_dial.hh",
        "copy_cog_clk_cc_dial.inl",
    ],
    cpp_deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk_cc"],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk"],
)

cc_library(
    name = "copy_cog_clk_cc_impl",
    srcs = ["copy_cog_clk_cc_impl.cc"],
    deps = [":copy_cog_clk_cc_dial"],
)

clk(
    name = "rate_limited_cog_clk",
    srcs = ["rate_limited_cog.clk"],
    outs = [
        "rate_limited_cog_clk_cc.cc",
        "rate_limited_cog_clk_cc.hh",
        "rate_limited_cog_clk_cc.inl",
        "rate_limited_cog_clk_cc_dial.cc",
        "rate_limited_cog_clk_cc_dial.hh",
        "rate_limited_cog_clk_cc_dial.inl",
    ],
    cpp_deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk_cc"],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk"],
)

cc_library(
    name = "rate_limited_cog_clk_cc_impl",
    srcs = ["rate_limited_cog_clk_cc_impl.cc"],
    deps = [":rate_limited_cog_clk_cc_dial"],
)

clk(
    name = "skip_cog_clk",
    srcs = ["skip_cog.clk"],
    outs = [
        "skip_cog_clk_cc.cc",
        "skip_cog_clk_cc.hh",
        "skip_cog_clk_cc.inl",
        "skip_cog_clk_cc_dial.cc",
        "skip_cog_clk_cc_dial.hh",
        "skip_cog_clk_cc_dial.inl",
    ],
    cpp_deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk_cc"],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = ["//clockwork/dsl/tests/support:clk_hellomsg_clk"],
)

cc_library(
    name = "skip_cog_clk_cc_impl",
    srcs = ["skip_cog_clk_cc_impl.cc"],
    deps = [":skip_cog_clk_cc_dial"],
)
