# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scaffolding",
    srcs = ["scaffolding.cc"],
    hdrs = ["scaffolding.hh"],
    deps = [
        ":abstract_casing",
        ":channels",
        ":cog",
        ":config",
        ":data_source_loader",
        ":io_connection",
        ":memory",
        ":snapshots",
        ":state",
        ":timer",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/runners:epoll_manager",
        "//clockwork/runners:online_cog_queue",
        "//clockwork/runners:online_runner",
        "//clockwork/runners:thread_pool",
        "//jewels/callsig:outcome",
        "//jewels/cli:exit_condition",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "@gsl//:util",
    ],
)

cc_library(
    name = "abstract_casing",
    hdrs = ["abstract_casing.hh"],
    deps = [
        "//clockwork:tags",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:forward",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/callsig:outcome",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@wise_enum",
    ],
)

cc_library(
    name = "casing",
    srcs = ["casing.inl"],
    hdrs = ["casing.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:cog_configs",
        "//clockwork/cog:cog_state",
        "//clockwork/cog:factory",
        "//clockwork/cog:interface",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:forward",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/callsig:outcome",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@protobuf",
    ],
)

cc_library(
    name = "channels",
    srcs = ["channels.cc"],
    hdrs = ["channels.hh"],
    linkopts = ["-pthread"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//clockwork/pinion:shm_subscriber",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@wise_enum",
        "@xxhash",
    ],
)

cc_library(
    name = "cog",
    srcs = ["cog.cc"],
    hdrs = ["cog.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:cog_execution_error_clk_cc",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@xxhash",
    ],
)

cc_library(
    name = "config",
    srcs = ["config.cc"],
    hdrs = ["config.hh"],
    deps = [
        ":abstract_casing",
        ":data_source_loader",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "data_source_loader",
    srcs = ["data_source_loader.cc"],
    hdrs = ["data_source_loader.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/utility:fix_clockwork_path",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "deterministic_logging_config",
    srcs = ["deterministic_logging_config.cc"],
    hdrs = ["deterministic_logging_config.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging/readers:log_reader",
        "//clockwork/logging/readers:types",
        "//clockwork/tools/metrics_channel_metadata:metrics_channel_metadata_config_clk_cc",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "deterministic_runner_setup",
    srcs = [
        "deterministic_runner_setup.cc",
        "deterministic_runner_setup.inl",
    ],
    hdrs = ["deterministic_runner_setup.hh"],
    deps = [
        ":channels",
        ":deterministic_logging_config",
        ":timer",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:cog_gpu_assignment_config_clk_cc",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/writers:deterministic_log_writer",
        "//clockwork/pinion:shm_publisher",
        "//clockwork/runners:channel_publisher",
        "//clockwork/runners:deterministic_channel_handler",
        "//clockwork/runners:deterministic_runner",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@xxhash",
    ],
)

cc_library(
    name = "end_process_exception",
    srcs = ["end_process_exception.cc"],
    hdrs = ["end_process_exception.hh"],
)

cc_library(
    name = "first_message_cache",
    srcs = ["first_message_cache.cc"],
    hdrs = ["first_message_cache.hh"],
    deps = [
        ":data_source_loader",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/runners:channel_publisher",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
    ],
)

cc_library(
    name = "io_connection",
    srcs = ["io_connection.cc"],
    hdrs = ["io_connection.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "main_impl",
    srcs = ["main_impl.cc"],
    hdrs = ["main_impl.hh"],
    deps = [
        ":abstract_casing",
        ":end_process_exception",
        ":scaffolding",
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/cli:exit_condition",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@tclap",
    ],
)

cc_library(
    name = "memory",
    srcs = ["memory.cc"],
    hdrs = ["memory.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:monitor_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@xxhash",
    ],
)

cc_library(
    name = "offline_main",
    srcs = ["offline_main.cc"],
    deps = [
        ":main_impl",
        ":offline_scaffolding",
        "//jewels/cli:exit_condition_signal",
    ],
)

cc_library(
    name = "offline_scaffolding",
    srcs = ["offline_scaffolding.cc"],
    hdrs = ["offline_scaffolding.hh"],
    deps = [
        ":abstract_casing",
        ":deterministic_runner_setup",
        ":scaffolding_offline_impl",
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging/log_playback:log_message_fetcher",
        "//clockwork/pinion:shm_channel_factory",
        "//jewels/cli:exit_condition",
        "//jewels/container:compare",
        "//jewels/memory:pointers",
    ],
    alwayslink = True,
)

cc_library(
    name = "online_main",
    srcs = ["online_main.cc"],
    deps = [
        ":main_impl",
        ":online_scaffolding",
        "//jewels/cli:exit_condition_signal",
    ],
)

cc_library(
    name = "online_scaffolding",
    srcs = ["online_scaffolding.cc"],
    hdrs = ["online_scaffolding.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:shm_channel_factory",
        "//jewels/cli:exit_condition",
        "//jewels/container:compare",
        "//jewels/log_cerr",
    ],
    alwayslink = True,
)

cc_library(
    name = "python_offline_main",
    srcs = ["python_offline_main.cc"],
    deps = [
        ":main_impl",
        ":offline_scaffolding",
        "//clockwork/python:python_init",
        "//jewels/cli:exit_condition_signal",
    ],
)

cc_library(
    name = "python_online_main",
    srcs = ["python_online_main.cc"],
    deps = [
        ":main_impl",
        ":online_scaffolding",
        "//clockwork/python:python_init",
        "//jewels/cli:exit_condition_signal",
    ],
)

cc_library(
    name = "scaffolding_offline_impl",
    srcs = ["scaffolding_offline_impl.inl"],
    hdrs = ["scaffolding_offline_impl.hh"],
    deps = [
        ":abstract_casing",
        ":channels",
        ":cog",
        ":config",
        ":data_source_loader",
        ":deterministic_logging_config",
        ":deterministic_runner_setup",
        ":first_message_cache",
        ":io_connection",
        ":memory",
        ":snapshots",
        ":state",
        ":timer",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/runners:channel_publisher",
        "//clockwork/runners:deterministic_cog_queue",
        "//clockwork/runners:deterministic_runner",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/cli:exit_condition",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@gsl//:util",
    ],
)

cc_library(
    name = "snapshots",
    srcs = ["snapshots.cc"],
    hdrs = ["snapshots.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//jewels/callsig:outcome",
    ],
)

cc_library(
    name = "state",
    srcs = ["state.cc"],
    hdrs = ["state.hh"],
    deps = [
        ":abstract_casing",
        ":data_source_loader",
        ":memory",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@wise_enum",
        "@xxhash",
    ],
)

cc_library(
    name = "timer",
    srcs = ["timer.cc"],
    hdrs = ["timer.hh"],
    deps = [
        ":abstract_casing",
        "//clockwork:repr_iface",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:exec_tools",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:observer",
        "//clockwork/runners:deterministic_timer",
        "//clockwork/runners:timerfd_timer",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
        "@xxhash",
    ],
)
