# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "mcap_converter",
    srcs = ["mcap_converter.cc"],
    deps = [
        ":convert_to_mcap",
        "@tclap",
    ],
)

cc_library(
    name = "convert_to_mcap",
    srcs = ["convert_to_mcap.cc"],
    hdrs = ["convert_to_mcap.hh"],
    deps = [
        ":mcap_channel_registry",
        ":mcap_util",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/readers:abstract_log_reader",
        "//clockwork/logging/readers:log_reader_factory",
        "//clockwork/logging/readers:types",
        "//jewels/log_cerr",
        "//jewels/std:expected",
        "@fmt",
        "@mcap",
    ],
)

cc_library(
    name = "mcap_channel_registry",
    srcs = ["mcap_channel_registry.cc"],
    hdrs = ["mcap_channel_registry.hh"],
    deps = [
        "//clockwork/logging/onboard:types",
        "//jewels/std:expected",
        "@mcap",
        "@wise_enum",
    ],
)

cc_library(
    name = "mcap_util",
    srcs = ["mcap_util.cc"],
    hdrs = ["mcap_util.hh"],
    deps = ["@mcap"],
)
