# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "aligned_pointer_test",
    srcs = ["aligned_pointer_test.cc"],
    deps = [
        "//clockwork/pinion:aligned_pointer",
        "//jewels/math:power_of_two",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "api_test",
    srcs = ["api_test.cc"],
    deps = [
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:error",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "bidirectional_udp_test",
    srcs = ["bidirectional_udp_test.cc"],
    deps = [
        "//clockwork/io:var_packet",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:bidirectional_udp",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:error",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:sock_opt",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/detail:socket_payload",
        "//clockwork/pinion/tests/support:sockets",
        "//clockwork/pinion/tests/support:udp_payloads",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/memory:bits",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "buffer_test",
    srcs = ["buffer_test.cc"],
    deps = [
        "//clockwork/pinion:aligned_pointer",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:buffer_index",
        "//clockwork/pinion:error",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//clockwork/pinion/tests/support:mock_slot",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "incoming_udp_test",
    srcs = ["incoming_udp_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/io:network_var_packet",
        "//clockwork/io:var_packet",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:error",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:incoming_udp",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:sock_opt",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/detail:socket_payload",
        "//clockwork/pinion/tests/support:sockets",
        "//clockwork/pinion/tests/support:udp_payloads",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "io_connection_test",
    srcs = ["io_connection_test.cc"],
    deps = [
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "multicast_udp_test",
    srcs = ["multicast_udp_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/io:var_packet",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:bidirectional_udp",
        "//clockwork/pinion:error",
        "//clockwork/pinion:incoming_udp",
        "//clockwork/pinion:outgoing_udp",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:sock_opt",
        "//clockwork/pinion/detail:socket_payload",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "outgoing_udp_test",
    srcs = ["outgoing_udp_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/io:network_var_packet",
        "//clockwork/io:var_packet",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion:outgoing_udp",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:sock_opt",
        "//clockwork/pinion/detail:socket_payload",
        "//clockwork/pinion/tests/support:sockets",
        "//clockwork/pinion/tests/support:udp_payloads",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/memory:bits",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "publisher_handle_test",
    srcs = ["publisher_handle_test.cc"],
    deps = [
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:buffer_index",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//clockwork/pinion/tests/support:pub_sub",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/time:sync_time",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "shm_channel_test",
    srcs = ["shm_channel_test.cc"],
    deps = [
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//clockwork/pinion:shm_subscriber",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/detail:mmap_region",
        "//clockwork/pinion/tests/support:epoll_snooper",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/pinion/tests/support:tmp_shm_namespace",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "slot_test",
    srcs = ["slot_test.cc"],
    deps = [
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:aligned_pointer",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_slot",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "sock_opt_test",
    srcs = ["sock_opt_test.cc"],
    deps = [
        "//clockwork/pinion:sock_opt",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/networking:sock_opt",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "subscriber_handle_test",
    srcs = ["subscriber_handle_test.cc"],
    deps = [
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:buffer_index",
        "//clockwork/pinion:error",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//clockwork/pinion/tests/support:mock_slot",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "tcp_bridge_client_test",
    srcs = ["tcp_bridge_client_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/common/tests/support:fake_epoll_mananger",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging/onboard:types",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion:tcp_bridge_client",
        "//clockwork/pinion:tcp_bridge_common",
        "//clockwork/pinion:tcp_bridge_config",
        "//clockwork/pinion/detail:socket_common",
        "//clockwork/pinion/detail:tcp_socket",
        "//clockwork/pinion/tests/support:pub_sub",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "tcp_bridge_common_test",
    srcs = ["tcp_bridge_common_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/pinion:bridge_status",
        "//clockwork/pinion:tcp_bridge_common",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "tcp_bridge_server_test",
    srcs = ["tcp_bridge_server_test.cc"],
    deps = [
        "//clockwork/common:process_description",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging/onboard:types",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:tcp_bridge_common",
        "//clockwork/pinion:tcp_bridge_config",
        "//clockwork/pinion:tcp_bridge_server",
        "//clockwork/pinion/detail:socket_common",
        "//clockwork/pinion/detail:tcp_socket",
        "//clockwork/pinion/tests/support:epoll_snooper",
        "//clockwork/pinion/tests/support:pub_sub",
        "//jewels/container/tap:var_string",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
    ],
)
