# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config", "simplelaunch_runner")
load("//tools/rules:python.bzl", "py_library")

package(
    default_testonly = True,
)

exports_files(["example_cog.clk"])

simplelaunch_runner(
    name = "example",
    config = ":localhost.textproto",
)

clk(
    name = "example_channel_policies_clk",
    srcs = ["example_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":example_channels_clk",
        "//clockwork/logging:channel_policy_clk",
    ],
)

clk(
    name = "example_channels_clk",
    srcs = ["example_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/python/tests/support:test_input_message_clk",
        "//clockwork/python/tests/support:test_output_message_clk",
    ],
)

clk(
    name = "example_clk",
    srcs = ["example.clk"],
    outs = [
        "example_clk_exe.cc",
        "example_clk_exe.hh",
        "example_clk_exe.inl",
    ],
    cpp_deps = [
        ":example_cog_clk_cc",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging/writers:channel_message_rates_config_clk_cc",
        "//clockwork/logging/writers:channel_message_rates_config_clk_proto_conv",
        "//clockwork/logging/writers:logger_clk_cc",
        "//clockwork/logging/writers:logger_config_clk_cc",
        "//clockwork/logging/writers:logger_config_clk_proto_conv",
        "//clockwork/logging/writers:logger_status_clk_cc",
        "//clockwork/python:python_state_clk_cc",
        "//clockwork/python/tests/support:test_config_clk_cc",
        "//clockwork/python/tests/support:test_config_clk_proto_conv",
        "//clockwork/python/tests/support:test_input_message_clk_cc",
        "//clockwork/python/tests/support:test_output_message_clk_cc",
        "//clockwork/python/tests/support:test_state_clk_cc",
        "//clockwork/tools/channel_spy:channel_spy_config_clk_cc",
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:python_online_main"],
    data = [
        "clockwork.clockwork.python.example.example_sys.example_sys.proc.tachyon",
        "example_sys.example_sys.LocalHost_channel_spy_config.tachyon",
        "example_sys.example_sys.LocalHost_telemetry_logger_config.tachyon",
        "//clockwork/python/example/resources:channel_rates_config.pbtxt",
        "//clockwork/python/example/resources:input1_config.pbtxt",
        "//clockwork/python/example/resources:input2_config.pbtxt",
        "//clockwork/python/example/resources:logger_config.pbtxt",
    ],
    generate = ["py_exe"],
    proto_deps = [
        "//clockwork/logging/writers:channel_message_rates_config_clk_proto",
        "//clockwork/logging/writers:logger_config_clk_proto",
        "//clockwork/python/tests/support:test_config_clk_proto",
    ],
    py_deps = [
        ":example_cog_clk_py_dial",
        ":example_cog_clk_py_impl",
    ],
    deps = [
        ":example_channel_policies_clk",
        ":example_channels_clk",
        ":example_cog_clk",
        "//clockwork/logging:log_writer_config_clk",
        "//clockwork/logging/writers:channel_message_rates_config_clk",
        "//clockwork/logging/writers:logger_channel_policies_clk",
        "//clockwork/logging/writers:logger_channels_clk",
        "//clockwork/logging/writers:logger_clk",
        "//clockwork/logging/writers:logger_config_clk",
        "//clockwork/logging/writers:logger_status_clk",
        "//clockwork/python:python_state_clk",
        "//clockwork/python/tests/support:test_config_clk",
        "//clockwork/python/tests/support:test_input_message_clk",
        "//clockwork/python/tests/support:test_output_message_clk",
        "//clockwork/python/tests/support:test_state_clk",
        "//clockwork/tools/channel_spy:channel_spy_config_clk",
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk",
    ],
)

clk(
    name = "example_cog_clk",
    srcs = ["example_cog.clk"],
    outs = [
        "example_cog_clk_cc.cc",
        "example_cog_clk_cc.hh",
        "example_cog_clk_cc.inl",
        "example_cog_clk_cc_cog.cc",
        "example_cog_clk_cc_cog.hh",
        "example_cog_clk_cc_cog.inl",
        "example_cog_clk_cc_dial.cc",
        "example_cog_clk_cc_dial.hh",
        "example_cog_clk_cc_dial.inl",
        "example_cog_clk_cc_impl.cc",
        "example_cog_clk_cc_impl.hh",
        "example_cog_clk_cc_impl.inl",
        "example_cog_clk_cc_types.cc",
        "example_cog_clk_cc_types.hh",
        "example_cog_clk_cc_types.inl",
        "example_cog_clk_py_dial.py",
    ],
    cpp_deps = [
        "//clockwork/python:python_state_clk_cc",
        "//clockwork/python/tests/support:test_config_clk_cc",
        "//clockwork/python/tests/support:test_input_message_clk_cc",
        "//clockwork/python/tests/support:test_output_message_clk_cc",
        "//clockwork/python/tests/support:test_state_clk_cc",
    ],
    generate = [
        "cpp",
        "py_cog",
    ],
    py_deps = [
        "//clockwork/python/tests/support:test_config_clk_nb",
        "//clockwork/python/tests/support:test_input_message_clk_nb",
        "//clockwork/python/tests/support:test_output_message_clk_nb",
        "//clockwork/python/tests/support:test_state_clk_nb",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/python:python_state_clk",
        "//clockwork/python/tests/support:test_config_clk",
        "//clockwork/python/tests/support:test_input_message_clk",
        "//clockwork/python/tests/support:test_output_message_clk",
        "//clockwork/python/tests/support:test_state_clk",
    ],
)

py_library(
    name = "example_cog_clk_py_impl",
    srcs = ["example_cog_clk_py_impl.py"],
    deps = [
        ":example_cog_clk_py_dial",
        "//clockwork/python/tests/support:test_input_message_clk_nb",
        "//clockwork/python/tests/support:test_output_message_clk_nb",
        "//jewels/nanobind:nb_sync_time",
    ],
)

clk(
    name = "example_sys_clk",
    srcs = ["example_sys.clk"],
    outs = [
        "clockwork.clockwork.python.example.example_sys.example_sys.proc.tachyon",
        "example_sys.example_sys.LocalHost_channel_allocations.csv",
        "example_sys.example_sys.LocalHost_channel_spy_config.tachyon",
        "example_sys.example_sys.LocalHost_event_logger_config.tachyon",
        "example_sys.example_sys.LocalHost_journal_topology.tachyon",
        "example_sys.example_sys.LocalHost_metrics_channel_metadata_config.tachyon",
        "example_sys.example_sys.LocalHost_signal_metadata_config.tachyon",
        "example_sys.example_sys.LocalHost_simplelaunch_config.textproto",
        "example_sys.example_sys.LocalHost_system_metadata.tachyon",
        "example_sys.example_sys.LocalHost_telemetry_logger_config.tachyon",
        "example_sys.example_sys.diagnostics_database_config.tachyon",
        "example_sys.example_sys.logged_channel_metadata.pbbin",
    ],
    deps = [":example_clk"],
)

merge_simplelaunch_config(
    name = "localhost.textproto",
    srcs = [
        "example_sys.example_sys.LocalHost_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.python.example.example_sys.example_sys.proc.tachyon",
        "example_sys.example_sys.LocalHost_channel_allocations.csv",
        "example_sys.example_sys.LocalHost_channel_spy_config.tachyon",
        "example_sys.example_sys.LocalHost_event_logger_config.tachyon",
        "example_sys.example_sys.LocalHost_journal_topology.tachyon",
        "example_sys.example_sys.LocalHost_metrics_channel_metadata_config.tachyon",
        "example_sys.example_sys.LocalHost_signal_metadata_config.tachyon",
        "example_sys.example_sys.LocalHost_system_metadata.tachyon",
        "example_sys.example_sys.LocalHost_telemetry_logger_config.tachyon",
        "example_sys.example_sys.diagnostics_database_config.tachyon",
        ":example_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)
