# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config", "simplelaunch_runner")

package(
    default_testonly = True,
)

simplelaunch_runner(
    name = "standalone_logger",
    config = ":localhost.textproto",
)

merge_simplelaunch_config(
    name = "localhost.textproto",
    srcs = [
        "standalone_logger_sys.standalone_logger_sys.LocalHost_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.logging.writers.standalone_logger.standalone_logger_sys.standalone_logger_sys.standalone_logger.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_channel_allocations.csv",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_channel_spy_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_event_logger_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_journal_topology.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_metrics_channel_metadata_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_signal_metadata_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_simplelaunch_runner_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_system_metadata.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_telemetry_logger_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.diagnostics_database_config.tachyon",
        ":standalone_logger_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)

clk(
    name = "standalone_logger_clk",
    srcs = ["standalone_logger.clk"],
    outs = [
        "standalone_logger_clk_exe.cc",
        "standalone_logger_clk_exe.hh",
        "standalone_logger_clk_exe.inl",
    ],
    cpp_deps = [
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging/writers:channel_message_rates_config_clk_cc",
        "//clockwork/logging/writers:channel_message_rates_config_clk_proto_conv",
        "//clockwork/logging/writers:logger_clk_cc",
        "//clockwork/logging/writers:logger_config_clk_cc",
        "//clockwork/logging/writers:logger_config_clk_proto_conv",
        "//clockwork/logging/writers:logger_status_clk_cc",
        "//clockwork/tools/channel_spy:channel_spy_config_clk_cc",
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    data = [
        "//clockwork/logging/writers/standalone_logger/resources:channel_rates_config.pbtxt",
        "//clockwork/logging/writers/standalone_logger/resources:logger_config.pbtxt",
    ],
    generate = ["cpp_exe"],
    proto_deps = [
        "//clockwork/logging/writers:channel_message_rates_config_clk_proto",
        "//clockwork/logging/writers:logger_config_clk_proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/logging:log_writer_config_clk",
        "//clockwork/logging/writers:channel_message_rates_config_clk",
        "//clockwork/logging/writers:logger_channel_policies_clk",
        "//clockwork/logging/writers:logger_channels_clk",
        "//clockwork/logging/writers:logger_clk",
        "//clockwork/logging/writers:logger_config_clk",
        "//clockwork/logging/writers:logger_status_clk",
        "//clockwork/tools/channel_spy:channel_spy_config_clk",
        "//clockwork/tools/channel_spy:channel_spy_config_init_clk",
    ],
)

clk(
    name = "standalone_logger_sys_clk",
    srcs = ["standalone_logger_sys.clk"],
    outs = [
        "clockwork.clockwork.logging.writers.standalone_logger.standalone_logger_sys.standalone_logger_sys.standalone_logger.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_channel_allocations.csv",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_channel_spy_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_event_logger_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_journal_topology.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_metrics_channel_metadata_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_signal_metadata_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_simplelaunch_config.textproto",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_simplelaunch_runner_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_system_metadata.tachyon",
        "standalone_logger_sys.standalone_logger_sys.LocalHost_telemetry_logger_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.diagnostics_database_config.tachyon",
        "standalone_logger_sys.standalone_logger_sys.logged_channel_metadata.pbbin",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":standalone_logger_clk",
        "//jewels/simplelaunch:simplelaunch_channel_policies_clk",
        "//jewels/simplelaunch:simplelaunch_channels_clk",
    ],
)
