# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_binary")

cc_binary(
    name = "merge_logs",
    srcs = ["merge_logs.cc"],
    deps = [
        "//clockwork/logging:log_error",
        "//clockwork/logging/offboard:merge_logs",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@tclap",
    ],
)
