# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@build_stack_rules_proto//rules:proto_compile.bzl", "proto_compile")
load("@build_stack_rules_proto//rules/cc:proto_cc_library.bzl", "proto_cc_library")
load("@build_stack_rules_proto//rules/py:proto_py_library.bzl", "proto_py_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_cc_binding", "py_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/python:__subpackages__"],
)

exports_files([
    "python_cog.clk",
    "test_config.clk",
    "test_input_message.clk",
    "test_state.clk",
    "test_output_message.clk",
])

py_library(
    name = "py_python_cog_dial",
    srcs = ["py_python_cog_dial.py"],
    data = [":python_cog_clk"],
    deps = [
        ":py_test_config",
        ":py_test_input_message",
        ":py_test_output_message",
        ":test_input_message_clk_nb",
        ":test_output_message_clk_nb",
        ":test_state_clk_nb",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "py_python_cog_impl",
    srcs = ["py_python_cog_impl.py"],
    deps = [
        ":py_python_cog_dial",
        ":py_test_output_message",
        ":test_output_message_clk_nb",
        "//jewels/nanobind:nb_sync_time",
    ],
)

py_library(
    name = "py_test_config",
    srcs = ["py_test_config.py"],
    data = [":test_config_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "py_test_input_message",
    srcs = ["py_test_input_message.py"],
    data = [":test_input_message_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "py_test_output_message",
    srcs = ["py_test_output_message.py"],
    data = [":test_output_message_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

cc_library(
    name = "python_cog",
    srcs = [
        "python_cog.cc",
        "python_cog.inl",
    ],
    hdrs = ["python_cog.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":python_cog_dial",
        ":python_cog_impl",
        ":test_input_message",
        ":test_output_message",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:cog_event_metrics_cpp",
        "//clockwork/dsl/cog:cog_telemetry_metrics_cpp",
        "//clockwork/dsl/cog:min_max_mean_cpp",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
)

clk(
    name = "python_cog_clk",
    srcs = ["python_cog.clk"],
    outs = [
        "py_python_cog_dial.py",
        "python_cog.cc",
        "python_cog.hh",
        "python_cog.inl",
        "python_cog_dial.cc",
        "python_cog_dial.hh",
        "python_cog_dial.inl",
        "python_cog_impl.cc",
        "python_cog_impl.hh",
        "python_cog_impl.inl",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":test_config_clk",
        ":test_input_message_clk",
        ":test_output_message_clk",
        ":test_state_clk",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
        "//clockwork/python:python_state_clk",
    ],
)

cc_library(
    name = "python_cog_dial",
    srcs = [
        "python_cog_dial.cc",
        "python_cog_dial.inl",
    ],
    hdrs = ["python_cog_dial.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":test_config",
        ":test_input_message",
        ":test_output_message",
        ":test_state",
        "//clockwork/dial:include_common",
        "//clockwork/python:python_state",
    ],
)

cc_library(
    name = "python_cog_impl",
    srcs = [
        "python_cog_impl.cc",
        "python_cog_impl.inl",
    ],
    hdrs = ["python_cog_impl.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":python_cog_dial",
        "//clockwork/python:gil_lock_guard",
        "//clockwork/python:python_init",
        "//clockwork/python:python_object",
        "//jewels/log_cerr",
    ],
)

py_library(
    name = "python_object_test_helper",
    srcs = ["python_object_test_helper.py"],
)

cc_library(
    name = "test_config",
    srcs = [
        "test_config.cc",
        "test_config.inl",
    ],
    hdrs = ["test_config.hh"],
    data = [":test_config_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_config_clk",
    srcs = ["test_config.clk"],
    outs = [
        "py_test_config.py",
        "test_config.cc",
        "test_config.hh",
        "test_config.inl",
        "test_config_proto.proto",
        "test_config_proto_conv.cc",
        "test_config_proto_conv.hh",
        "test_config_proto_conv.inl",
    ],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "test_config_proto",
    srcs = ["test_config_proto.proto"],
)

proto_cc_library(
    name = "test_config_proto_cc_library",
    srcs = ["test_config_proto.pb.cc"],
    hdrs = ["test_config_proto.pb.h"],
    deps = ["@protobuf"],
)

proto_compile(
    name = "test_config_proto_compile",
    outputs = [
        "test_config_proto.pb.h",
        "test_config_proto.pb.cc",
        "test_config_proto_pb2.py",
        "test_config_proto_pb2.pyi",
    ],
    plugins = [
        "@build_stack_rules_proto//plugin/builtin:cpp",
        "@build_stack_rules_proto//plugin/builtin:pyi",
        "@build_stack_rules_proto//plugin/builtin:python",
        "@clockwork//tools/gazelle:protoc-gen-nolint",
    ],
    proto = "test_config_proto",
)

cc_library(
    name = "test_config_proto_conv",
    srcs = [
        "test_config_proto_conv.cc",
        "test_config_proto_conv.inl",
    ],
    hdrs = ["test_config_proto_conv.hh"],
    data = [":test_config_clk"],
    deps = [
        ":test_config",
        ":test_config_proto_cc_library",
        "//clockwork:repr_iface",
        "//jewels/container/tap:protobuf_to_tap",
    ],
)

proto_py_library(
    name = "test_config_proto_py_library",
    srcs = ["test_config_proto_pb2.py"],
    data = ["test_config_proto_pb2.pyi"],
    deps = ["@protobuf//:protobuf_python"],
)

cc_library(
    name = "test_input_message",
    srcs = [
        "test_input_message.cc",
        "test_input_message.inl",
    ],
    hdrs = ["test_input_message.hh"],
    data = [":test_input_message_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_input_message_clk",
    srcs = ["test_input_message.clk"],
    outs = [
        "py_test_input_message.py",
        "test_input_message.cc",
        "test_input_message.hh",
        "test_input_message.inl",
        "test_input_message_clk_nb.cc",
        "test_input_message_clk_nb.hh",
        "test_input_message_clk_nb.inl",
    ],
    visibility = ["//visibility:public"],
)

py_cc_binding(
    name = "test_input_message_clk_nb",
    srcs = [
        "test_input_message_clk_nb.cc",
        "test_input_message_clk_nb.hh",
        "test_input_message_clk_nb.inl",
    ],
    data = [":test_input_message_clk"],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    deps = [
        ":test_input_message",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)

cc_library(
    name = "test_output_message",
    srcs = [
        "test_output_message.cc",
        "test_output_message.inl",
    ],
    hdrs = ["test_output_message.hh"],
    data = [":test_output_message_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/time:sync_time",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_output_message_clk",
    srcs = ["test_output_message.clk"],
    outs = [
        "py_test_output_message.py",
        "test_output_message.cc",
        "test_output_message.hh",
        "test_output_message.inl",
        "test_output_message_clk_nb.cc",
        "test_output_message_clk_nb.hh",
        "test_output_message_clk_nb.inl",
    ],
    visibility = ["//visibility:public"],
)

py_cc_binding(
    name = "test_output_message_clk_nb",
    srcs = [
        "test_output_message_clk_nb.cc",
        "test_output_message_clk_nb.hh",
        "test_output_message_clk_nb.inl",
    ],
    data = [":test_output_message_clk"],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    visibility = ["//visibility:public"],
    deps = [
        ":test_output_message",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)

cc_library(
    name = "test_state",
    srcs = [
        "test_state.cc",
        "test_state.inl",
    ],
    hdrs = ["test_state.hh"],
    data = [":test_state_clk"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_state_clk",
    srcs = ["test_state.clk"],
    outs = [
        "test_state.cc",
        "test_state.hh",
        "test_state.inl",
        "test_state_clk_nb.cc",
        "test_state_clk_nb.hh",
        "test_state_clk_nb.inl",
    ],
    visibility = ["//visibility:public"],
)

py_cc_binding(
    name = "test_state_clk_nb",
    srcs = [
        "test_state_clk_nb.cc",
        "test_state_clk_nb.hh",
        "test_state_clk_nb.inl",
    ],
    data = [":test_state_clk"],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    visibility = ["//visibility:public"],
    deps = [
        ":test_state",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)
