# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/python:__subpackages__"],
)

exports_files([
    "clk_python_cog.clk",
    "python_cog.clk",
    "test_config.clk",
    "test_input_message.clk",
    "test_state.clk",
    "test_output_message.clk",
])

clk(
    name = "clk_python_cog_clk",
    srcs = ["clk_python_cog.clk"],
    outs = [
        "clk_python_cog_clk_cc.cc",
        "clk_python_cog_clk_cc.hh",
        "clk_python_cog_clk_cc.inl",
        "clk_python_cog_clk_cc_dial.cc",
        "clk_python_cog_clk_cc_dial.hh",
        "clk_python_cog_clk_cc_dial.inl",
        "clk_python_cog_clk_cc_impl.cc",
        "clk_python_cog_clk_cc_impl.hh",
        "clk_python_cog_clk_cc_impl.inl",
        "clk_python_cog_clk_py_dial.py",
    ],
    cpp_deps = [
        ":test_config_clk_cc",
        ":test_input_message_clk_cc",
        ":test_output_message_clk_cc",
        ":test_state_clk_cc",
        "//clockwork/python:python_state_clk_cc",
    ],
    generate = [
        "cpp",
        "py_cog",
    ],
    py_deps = [
        ":test_config_clk_nb",
        ":test_input_message_clk_nb",
        ":test_output_message_clk_nb",
        ":test_state_clk_nb",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":test_config_clk",
        ":test_input_message_clk",
        ":test_output_message_clk",
        ":test_state_clk",
        "//clockwork/python:python_state_clk",
    ],
)

py_library(
    name = "clk_python_cog_clk_py_impl",
    srcs = ["clk_python_cog_clk_py_impl.py"],
    deps = [
        ":clk_python_cog_clk_py_dial",
        ":test_output_message_clk_nb",
        "//jewels/nanobind:nb_sync_time",
    ],
)

py_library(
    name = "py_python_cog_dial",
    srcs = ["py_python_cog_dial.py"],
    data = [":python_cog_clk"],
    deps = [
        ":test_config_clk_py",
        ":test_input_message_clk_nb",
        ":test_input_message_clk_py",
        ":test_output_message_clk_nb",
        ":test_output_message_clk_py",
        ":test_state_clk_nb",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "py_python_cog_impl",
    srcs = ["py_python_cog_impl.py"],
    deps = [
        ":py_python_cog_dial",
        ":test_output_message_clk_nb",
        ":test_output_message_clk_py",
        "//jewels/nanobind:nb_sync_time",
    ],
)

cc_library(
    name = "python_cog",
    srcs = [
        "python_cog.cc",
        "python_cog.inl",
    ],
    hdrs = ["python_cog.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":python_cog_dial",
        ":python_cog_impl",
        ":test_input_message_clk_cc",
        ":test_output_message_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk_cc",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk_cc",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
    alwayslink = True,
)

clk(
    name = "python_cog_clk",
    srcs = ["python_cog.clk"],
    outs = [
        "py_python_cog_dial.py",
        "python_cog.cc",
        "python_cog.hh",
        "python_cog.inl",
        "python_cog_dial.cc",
        "python_cog_dial.hh",
        "python_cog_dial.inl",
        "python_cog_impl.cc",
        "python_cog_impl.hh",
        "python_cog_impl.inl",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":test_config_clk",
        ":test_input_message_clk",
        ":test_output_message_clk",
        ":test_state_clk",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
        "//clockwork/python:python_state_clk",
    ],
)

cc_library(
    name = "python_cog_dial",
    srcs = [
        "python_cog_dial.cc",
        "python_cog_dial.inl",
    ],
    hdrs = ["python_cog_dial.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":test_config_clk_cc",
        ":test_input_message_clk_cc",
        ":test_output_message_clk_cc",
        ":test_state_clk_cc",
        "//clockwork/dial:include_common",
        "//clockwork/python:python_state",
    ],
)

cc_library(
    name = "python_cog_impl",
    srcs = [
        "python_cog_impl.cc",
        "python_cog_impl.inl",
    ],
    hdrs = ["python_cog_impl.hh"],
    data = [":python_cog_clk"],
    deps = [
        ":python_cog_dial",
        "//clockwork/python:gil_lock_guard",
        "//clockwork/python:python_init",
        "//clockwork/python:python_object",
        "//jewels/log_cerr",
    ],
    alwayslink = True,
)

py_library(
    name = "python_object_test_helper",
    srcs = ["python_object_test_helper.py"],
)

clk(
    name = "test_config_clk",
    srcs = ["test_config.clk"],
    outs = [
        "test_config_clk_cc.cc",
        "test_config_clk_cc.hh",
        "test_config_clk_cc.inl",
        "test_config_clk_nb.cc",
        "test_config_clk_nb.hh",
        "test_config_clk_nb.inl",
        "test_config_clk_proto.proto",
        "test_config_clk_proto_conv.cc",
        "test_config_clk_proto_conv.hh",
        "test_config_clk_proto_conv.inl",
        "test_config_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
        "nanobind",
        "proto",
        "proto_conv",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "test_input_message_clk",
    srcs = ["test_input_message.clk"],
    outs = [
        "test_input_message_clk_cc.cc",
        "test_input_message_clk_cc.hh",
        "test_input_message_clk_cc.inl",
        "test_input_message_clk_nb.cc",
        "test_input_message_clk_nb.hh",
        "test_input_message_clk_nb.inl",
        "test_input_message_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
        "nanobind",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "test_output_message_clk",
    srcs = ["test_output_message.clk"],
    outs = [
        "test_output_message_clk_cc.cc",
        "test_output_message_clk_cc.hh",
        "test_output_message_clk_cc.inl",
        "test_output_message_clk_nb.cc",
        "test_output_message_clk_nb.hh",
        "test_output_message_clk_nb.inl",
        "test_output_message_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
        "nanobind",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "test_state_clk",
    srcs = ["test_state.clk"],
    outs = [
        "test_state_clk_cc.cc",
        "test_state_clk_cc.hh",
        "test_state_clk_cc.inl",
        "test_state_clk_nb.cc",
        "test_state_clk_nb.hh",
        "test_state_clk_nb.inl",
    ],
    generate = [
        "cpp",
        "nanobind",
    ],
    visibility = ["//visibility:public"],
)
