# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_library")

# Top-level library
py_library(
    name = "clockwork",
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/common:cog_gpu_assignment_config_clk_py",
        "//clockwork/common:constants_clk_py",
        "//clockwork/common:process_description_clk_py",
        "//clockwork/common:system_metadata_clk_py",
        "//clockwork/dsl/aligner/gen:aligner_cog",
        "//clockwork/dsl/aligner/gen:alignment_schema",
        "//clockwork/dsl/aligner/gen:codegen_plan",
        "//clockwork/dsl/aligner/gen:search_codegen",
        "//clockwork/dsl/aligner:direction_analysis",
        "//clockwork/dsl/aligner:extract_specs",
        "//clockwork/dsl/aligner:join_plan",
        "//clockwork/dsl/aligner:objective_analysis",
        "//clockwork/dsl/aligner:partition_plan",
        "//clockwork/dsl/aligner:partition_types",
        "//clockwork/dsl/aligner:pipeline",
        "//clockwork/dsl/aligner:presence",
        "//clockwork/dsl/aligner:stn",
        "//clockwork/dsl/aligner:type_check",
        "//clockwork/dsl/bazel:cc_targets",
        "//clockwork/dsl/bazel:clk_targets",
        "//clockwork/dsl/bazel:extract_targets",
        "//clockwork/dsl/bazel:nanobind_targets",
        "//clockwork/dsl/bazel:proto_targets",
        "//clockwork/dsl/bazel:py_targets",
        "//clockwork/dsl/bazel:simple_launch_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/cog:aligner_metrics_policy",
        "//clockwork/dsl/cog:clk_cog_metrics",
        "//clockwork/dsl/cog:codegen_helpers",
        "//clockwork/dsl/cog:cog_metrics_policy",
        "//clockwork/dsl/cog:cog_metrics_policy_proto",
        "//clockwork/dsl/cog:cpp_python_cog",
        "//clockwork/dsl/cog:cpp_test_cog",
        "//clockwork/dsl/cog:cppcog",
        "//clockwork/dsl/cog:cppdial",
        "//clockwork/dsl/cog:cppdial_signals",
        "//clockwork/dsl/cog:metrics_policy_loader",
        "//clockwork/dsl/cog:pycog",
        "//clockwork/dsl/cog:report_group_policy",
        "//clockwork/dsl/cog:report_group_policy_proto",
        "//clockwork/dsl/composition:aligned_input",
        "//clockwork/dsl/composition:bridgegen",
        "//clockwork/dsl/composition:channel_config",
        "//clockwork/dsl/composition:channel_config_proto",
        "//clockwork/dsl/composition:channel_spy_config",
        "//clockwork/dsl/composition:channel_spy_config_proto",
        "//clockwork/dsl/composition:constants",
        "//clockwork/dsl/composition:diagnostics_config",
        "//clockwork/dsl/composition:diagnostics_config_proto",
        "//clockwork/dsl/composition:gen_channel_allocation_report",
        "//clockwork/dsl/composition:gen_channel_spy_configs",
        "//clockwork/dsl/composition:gen_diagnostics_configs",
        "//clockwork/dsl/composition:gen_logger_configs",
        "//clockwork/dsl/composition:gen_metrics_channel_metadata_configs",
        "//clockwork/dsl/composition:gen_multi_subscriber_configs",
        "//clockwork/dsl/composition:gen_signal_metadata_configs",
        "//clockwork/dsl/composition:genpd",
        "//clockwork/dsl/composition:graphir",
        "//clockwork/dsl/composition:journal_topology",
        "//clockwork/dsl/composition:journal_topology_file_config",
        "//clockwork/dsl/composition:journal_topology_file_config_proto",
        "//clockwork/dsl/composition:launchgen",
        "//clockwork/dsl/composition:logger_config",
        "//clockwork/dsl/composition:logger_config_proto",
        "//clockwork/dsl/composition:metrics_channel_metadata_config",
        "//clockwork/dsl/composition:metrics_channel_metadata_config_proto",
        "//clockwork/dsl/composition:multi_subscriber_config",
        "//clockwork/dsl/composition:multi_subscriber_config_proto",
        "//clockwork/dsl/composition:pdf",
        "//clockwork/dsl/composition:pdfproto",
        "//clockwork/dsl/composition:platform_diagnostics_config",
        "//clockwork/dsl/composition:platform_diagnostics_config_proto",
        "//clockwork/dsl/composition:publisher_config",
        "//clockwork/dsl/composition:publisher_config_proto",
        "//clockwork/dsl/composition:realtime_playback_config",
        "//clockwork/dsl/composition:realtime_playback_generation",
        "//clockwork/dsl/composition:signal_metadata_config",
        "//clockwork/dsl/composition:signal_metadata_config_proto",
        "//clockwork/dsl/composition:simplelaunch_runner_config",
        "//clockwork/dsl/composition:simplelaunch_runner_config_proto",
        "//clockwork/dsl/composition:snapshot_config",
        "//clockwork/dsl/composition:str_manip",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/composition:system_metadata",
        "//clockwork/dsl/composition:system_metadata_proto",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/composition:tcp_bridge_config",
        "//clockwork/dsl/composition:tcp_bridge_config_proto",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/cpp:literal",
        "//clockwork/dsl/cpp:typereg",
        "//clockwork/dsl/cpp:types",
        "//clockwork/dsl/cpp:values",
        "//clockwork/dsl/ir:aligner",
        "//clockwork/dsl/ir:aligner_builtins",
        "//clockwork/dsl/ir:aligner_metrics_report_groups",
        "//clockwork/dsl/ir:audio",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_components",
        "//clockwork/dsl/ir:cog_metrics_report_groups",
        "//clockwork/dsl/ir:cog_metrics_schema_generation",
        "//clockwork/dsl/ir:cog_parameters",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:conversion_utils",
        "//clockwork/dsl/ir:converter",
        "//clockwork/dsl/ir:cpp_executable",
        "//clockwork/dsl/ir:cpp_extern",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:cst_util",
        "//clockwork/dsl/ir:dfl",
        "//clockwork/dsl/ir:dfl_analysis",
        "//clockwork/dsl/ir:dfl_traits",
        "//clockwork/dsl/ir:dfl_types",
        "//clockwork/dsl/ir:diagnostics",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:extern_type",
        "//clockwork/dsl/ir:fmt_string",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:interface",
        "//clockwork/dsl/ir:memres",
        "//clockwork/dsl/ir:message_type",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:nanobind_binding",
        "//clockwork/dsl/ir:nanobind_target",
        "//clockwork/dsl/ir:nanobind_target_render",
        "//clockwork/dsl/ir:nanobind_type_casters",
        "//clockwork/dsl/ir:nanobinding_registry",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:proto_target",
        "//clockwork/dsl/ir:proto_to_tap",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:py_target",
        "//clockwork/dsl/ir:python_cog_dial",
        "//clockwork/dsl/ir:report_group",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:signal_policy_validation",
        "//clockwork/dsl/ir:signal_registry",
        "//clockwork/dsl/ir:statement",
        "//clockwork/dsl/ir:strongtypes",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:tap_to_proto",
        "//clockwork/dsl/ir:tensor_builtins",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "//clockwork/dsl/ir:units",
        "//clockwork/dsl/ir:uuid_reg",
        "//clockwork/dsl/proto:proto_typereg",
        "//clockwork/dsl/python:py_context",
        "//clockwork/dsl/python:typereg",
        "//clockwork/dsl/serialization:pod",
        "//clockwork/dsl/serialization:protobuf_clk",
        "//clockwork/dsl/serialization:pytap",
        "//clockwork/dsl/serialization:soa",
        "//clockwork/dsl/serialization:tachyon_layout",
        "//clockwork/dsl/serialization:tachyon_layout_reg",
        "//clockwork/dsl/serialization:tachyon_reg",
        "//clockwork/dsl/serialization:tap",
        "//clockwork/dsl/serialization:tap_render",
        "//clockwork/dsl:clockwork_cst",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:clockwork_parser",
        "//clockwork/dsl:clockwork_py_cst",
        "//clockwork/dsl:clockwork_py_parser",
        "//clockwork/dsl:clockwork_unparser",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl:fmt_lib",
        "//clockwork/dsl:parser_backend",
        "//clockwork/io:var_packet_clk_nb",
        "//clockwork/journal/replay:execution_stats_clk_nb",
        "//clockwork/journal:journal_py_library",
        "//clockwork/journal:journal_topology_file_config_clk_py",
        "//clockwork/journal:journal_topology_py_library",
        "//clockwork/logging/log_playback:end_of_log_clk_nb",
        "//clockwork/logging/offboard/v1:log_amendment_py_library",
        "//clockwork/logging/offboard/v1:log_metadata_py_library",
        "//clockwork/logging/offboard/v1:log_union_py_library",
        "//clockwork/logging/offboard/v1:writer_config_py_library",
        "//clockwork/logging/offboard:nb_copy_log",
        "//clockwork/logging/offboard:nb_log_writer_impl",
        "//clockwork/logging/offboard:nb_types",
        "//clockwork/logging/offboard:py_log_writer",
        "//clockwork/logging/readers:nb_log_processor",
        "//clockwork/logging/readers:nb_log_reader",
        "//clockwork/logging/readers:nb_types",
        "//clockwork/logging/readers:py_log_processor",
        "//clockwork/logging/readers:py_log_reader",
        "//clockwork/logging/readers:py_types",
        "//clockwork/logging/realtime_playback/v1:realtime_playback_converter_manifest_py_library",
        "//clockwork/logging/realtime_playback:nb_xxh3_checksum",
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_py",
        "//clockwork/logging/realtime_playback:realtime_playback_stream_kind_clk_py",
        "//clockwork/logging/tools/upgrade_log:upgrade_lib",
        "//clockwork/logging:channel_publisher_config_clk_py",
        "//clockwork/logging:log_uuid_tag_clk_py",
        "//clockwork/pinion:bridge_status_clk_nb",
        "//clockwork/pinion:channel_config_clk_py",
        "//clockwork/serialization/cpp:nb_tachyon_upgrader",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/metadata:tachyon_model",
        "//clockwork/serialization/metadata:tachyon_model_py_library",
        "//clockwork/serialization/py:common",
        "//clockwork/serialization/py:compatibility",
        "//clockwork/serialization/py:create_upgrader",
        "//clockwork/serialization/py:protocol",
        "//clockwork/serialization/py:tachyon_dyn",
        "//clockwork/serialization/py:tachyon_dyn_from_metadata",
        "//clockwork/tools/channel_spy:nb_channel_spy",
        "//clockwork/tools/channel_spy:py_channel_spy",
        "//clockwork/tools/journal_file_generator:alignment",
        "//clockwork/tools/journal_file_generator:alignment_message",
        "//clockwork/tools/journal_file_generator:channel_summary",
        "//clockwork/tools/journal_file_generator:cog_channel",
        "//clockwork/tools/journal_file_generator:execution_extractor",
        "//clockwork/tools/journal_file_generator:generator",
        "//clockwork/tools/journal_file_generator:instance_discovery",
        "//clockwork/tools/journal_file_generator:journal_metadata",
        "//clockwork/tools/journal_file_generator:log_index",
        "//clockwork/tools/journal_file_generator:message_index",
        "//clockwork/tools/journal_file_generator:readiness",
        "//clockwork/tools/journal_file_generator:request",
        "//clockwork/tools/journal_file_generator:scope",
        "//clockwork/tools/journal_file_generator:snapshot_selector",
        "//clockwork/tools/journal_file_generator:topology_file",
        "//clockwork/tools/journal_file_generator:writer",
        "//clockwork/tools/journal_report:anomalies",
        "//clockwork/tools/journal_report:reader",
        "//clockwork/tools/journal_report:renderer",
        "//clockwork/tools/journal_report:request",
        "//clockwork/tools/journal_report:server",
        "//clockwork/tools/journal_report:view_model",
        "//clockwork/tools/signal_extractor",
        "//clockwork/tools/signal_extractor:report_group_decoder",
        "//clockwork/tools/topology",
        "//clockwork/tools/topology:topology_file",
        "//clockwork:logical_system_interface",
        # [[[end]]]
    ],
)

py_library(
    name = "logical_system_interface",
    srcs = ["logical_system_interface.py"],
    data = [
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/composition:graphir",
        "//clockwork/dsl/composition:logger_config",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_components",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "//clockwork/dsl/ir:uuid_reg",
    ],
)

cc_library(
    name = "repr_iface",
    hdrs = ["repr_iface.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/logging:cpp_message_encoding",
        "//clockwork/logging:cpp_schema_encoding",
    ],
)

bzl_library(
    name = "rules_bzl",
    srcs = ["rules.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//tools/rules:cc_bzl",
        "//tools/rules:python_bzl",
        "@bazel_lib//lib:write_source_files",
        "@bazel_skylib//lib:paths",
        "@bazel_tools//tools/cpp:toolchain_utils.bzl",
        "@build_stack_rules_proto//rules:proto_compile",
        "@build_stack_rules_proto//rules/cc:proto_cc_library",
        "@build_stack_rules_proto//rules/go:proto_go_library",
        "@build_stack_rules_proto//rules/py:proto_py_library",
        "@rules_cc//cc/common",
        "@rules_cc//cc/toolchains:toolchain_rules",
        "@rules_python//python:defs_bzl",
        "@rules_python//python:pip_bzl",
    ],
)

cc_library(
    name = "serializable",
    hdrs = ["serializable.hh"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tags",
    hdrs = ["tags.hh"],
    visibility = ["//visibility:public"],
)
