# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "tdigest_test",
    srcs = ["tdigest_test.cc"],
    deps = [
        "//jewels/math/estimation:tdigest",
        "@catch2//:catch2_main",
    ],
)
