# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_cc_binding", "py_library")

package(default_testonly = True)

clk(
    name = "bind_array_msg_clk",
    srcs = ["bind_array_msg.clk"],
    outs = [
        "bind_array_msg_clk_cc.cc",
        "bind_array_msg_clk_cc.hh",
        "bind_array_msg_clk_cc.inl",
        "bind_array_msg_clk_cc_types.cc",
        "bind_array_msg_clk_cc_types.hh",
        "bind_array_msg_clk_cc_types.inl",
        "bind_array_msg_clk_nb.cc",
        "bind_array_msg_clk_nb.hh",
        "bind_array_msg_clk_nb.inl",
    ],
    visibility = ["//jewels/nanobind/clk_bindings/tests:__subpackages__"],
)

cc_library(
    name = "bind_array_msg_clk_cc",
    srcs = [
        "bind_array_msg_clk_cc.cc",
        "bind_array_msg_clk_cc.inl",
    ],
    hdrs = ["bind_array_msg_clk_cc.hh"],
    data = [":bind_array_msg_clk"],
    visibility = ["//jewels/nanobind/tests:__subpackages__"],
    deps = [":bind_array_msg_clk_cc_types"],
)

cc_library(
    name = "bind_array_msg_clk_cc_types",
    srcs = [
        "bind_array_msg_clk_cc_types.cc",
        "bind_array_msg_clk_cc_types.inl",
    ],
    hdrs = ["bind_array_msg_clk_cc_types.hh"],
    data = [":bind_array_msg_clk"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

py_cc_binding(
    name = "bind_array_msg_clk_nb",
    srcs = [
        "bind_array_msg_clk_nb.cc",
        "bind_array_msg_clk_nb.hh",
        "bind_array_msg_clk_nb.inl",
    ],
    data = [":bind_array_msg_clk"],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    visibility = ["//jewels/nanobind/clk_bindings/tests:__subpackages__"],
    deps = [
        ":bind_array_msg_clk_cc",
        "//jewels/nanobind:nb_byte_array",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)

clk(
    name = "foo_clk",
    srcs = ["foo.clk"],
    outs = [
        "foo_clk_cc.cc",
        "foo_clk_cc.hh",
        "foo_clk_cc.inl",
        "foo_clk_cc_types.cc",
        "foo_clk_cc_types.hh",
        "foo_clk_cc_types.inl",
        "foo_clk_nb.cc",
        "foo_clk_nb.hh",
        "foo_clk_nb.inl",
        "foo_clk_py.py",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "foo_clk_cc",
    srcs = [
        "foo_clk_cc.cc",
        "foo_clk_cc.inl",
    ],
    hdrs = ["foo_clk_cc.hh"],
    data = [":foo_clk"],
    visibility = ["//visibility:public"],
    deps = [":foo_clk_cc_types"],
)

cc_library(
    name = "foo_clk_cc_types",
    srcs = [
        "foo_clk_cc_types.cc",
        "foo_clk_cc_types.inl",
    ],
    hdrs = ["foo_clk_cc_types.hh"],
    data = [":foo_clk"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

py_cc_binding(
    name = "foo_clk_nb",
    srcs = [
        "foo_clk_nb.cc",
        "foo_clk_nb.hh",
        "foo_clk_nb.inl",
    ],
    data = [":foo_clk"],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    visibility = ["//jewels/nanobind/clk_bindings/tests:__subpackages__"],
    deps = [
        ":foo_clk_cc",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)

py_library(
    name = "foo_clk_py",
    srcs = ["foo_clk_py.py"],
    data = [":foo_clk"],
    visibility = ["//jewels/nanobind/clk_bindings/tests:__subpackages__"],
    deps = [
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_cc_binding(
    name = "nb_get_python_type_name_test",
    srcs = ["nb_get_python_type_name_test.cc"],
    visibility = ["//jewels/nanobind/clk_bindings/tests:__subpackages__"],
    deps = [
        "//jewels/nanobind/clk_bindings:get_python_type_name",
        "@nanobind",
    ],
)
