# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "log_message_fetcher_test",
    srcs = ["log_message_fetcher_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_uuid",
        "//clockwork/logging/log_playback:end_of_log_clk_cc",
        "//clockwork/logging/log_playback:log_message_fetcher",
        "//clockwork/logging/offboard:writer",
        "//clockwork/logging/writers/tests/support:test_log_writer_config",
        "//clockwork/runners:channel_publisher",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_cc",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)
