# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "cxx_state",
    hdrs = ["cxx_state.hh"],
    deps = ["//jewels/memory:memory_resource"],
)

cc_library(
    name = "mock_casing",
    hdrs = ["mock_casing.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:forward",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:observer",
        "//clockwork/scaffolding:abstract_casing",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@trompeloeil",
    ],
)

cc_library(
    name = "runtime_tools",
    hdrs = ["runtime_tools.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:abstract_channel_factory",
        "//clockwork/pinion:buffer_layout",
        "//jewels/cli:exit_condition",
        "//jewels/cli/tests/support:simple_exit_condition",
        "//jewels/container:compare",
        "//jewels/filesystem:file",
        "//jewels/filesystem:path",
        "//jewels/std:span",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@protobuf",
    ],
)

cc_library(
    name = "test_cogs",
    srcs = [
        "test_cogs.cc",
        "test_cogs.inl",
    ],
    hdrs = ["test_cogs.hh"],
    data = [":test_cogs_clk"],
    deps = [
        ":test_cogs_cog",
        ":test_cogs_diags",
        ":test_cogs_dial",
        ":test_cogs_impl",
        ":test_cogs_types",
        "//clockwork/cog:include_common",
    ],
    alwayslink = True,
)

clk(
    name = "test_cogs_clk",
    srcs = ["test_cogs.clk"],
    outs = [
        "test_cogs.cc",
        "test_cogs.hh",
        "test_cogs.inl",
        "test_cogs_cog.cc",
        "test_cogs_cog.hh",
        "test_cogs_cog.inl",
        "test_cogs_dial.cc",
        "test_cogs_dial.hh",
        "test_cogs_dial.inl",
        "test_cogs_types.cc",
        "test_cogs_types.hh",
        "test_cogs_types.inl",
    ],
    deps = [
        ":test_msgs_clk",
        "//clockwork/diagnostics:report_clk",
        "//std:cog_metrics_policy_clk",
    ],
)

cc_library(
    name = "test_cogs_cog",
    srcs = [
        "test_cogs_cog.cc",
        "test_cogs_cog.inl",
    ],
    hdrs = ["test_cogs_cog.hh"],
    data = [":test_cogs_clk"],
    deps = [
        ":test_cogs_dial",
        ":test_msgs_clk_cc",
        "//clockwork/cog:include_common",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/diagnostics:reporter",
    ],
    alwayslink = True,
)

cc_library(
    name = "test_cogs_diags",
    hdrs = ["test_cogs_diags.hh"],
)

cc_library(
    name = "test_cogs_dial",
    srcs = [
        "test_cogs_dial.cc",
        "test_cogs_dial.inl",
    ],
    hdrs = ["test_cogs_dial.hh"],
    data = [":test_cogs_clk"],
    deps = [
        ":cxx_state",
        ":test_cogs_diags",
        ":test_msgs_clk_cc",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/diagnostics:reporter",
        "//clockwork/dial:include_common",
    ],
)

cc_library(
    name = "test_cogs_impl",
    srcs = ["test_cogs_impl.cc"],
    deps = [
        ":test_cogs_dial",
        ":test_msgs_clk_cc",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "test_cogs_types",
    srcs = [
        "test_cogs_types.cc",
        "test_cogs_types.inl",
    ],
    hdrs = ["test_cogs_types.hh"],
    data = [":test_cogs_clk"],
    deps = [":cxx_state"],
)

cc_library(
    name = "test_io_connections",
    srcs = ["test_io_connections.cc"],
    hdrs = ["test_io_connections.hh"],
    deps = [
        "//clockwork/common:abstract_epoll_manager",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:io_connection",
        "//clockwork/pinion/tests/support:pub_sub",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@gsl//:util",
        "@wise_enum",
    ],
)

clk(
    name = "test_msgs_clk",
    srcs = ["test_msgs.clk"],
    outs = [
        "test_msgs_clk_cc.cc",
        "test_msgs_clk_cc.hh",
        "test_msgs_clk_cc.inl",
        "test_msgs_clk_cc_types.cc",
        "test_msgs_clk_cc_types.hh",
        "test_msgs_clk_cc_types.inl",
        "test_msgs_clk_proto.proto",
        "test_msgs_clk_proto_conv.cc",
        "test_msgs_clk_proto_conv.hh",
        "test_msgs_clk_proto_conv.inl",
    ],
    generate = [
        "cpp",
        "proto",
        "proto_conv",
    ],
)
