# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

py_test(
    name = "aligner_metrics_report_groups_test",
    srcs = [
        "aligner_metrics_report_groups_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/cog:cog_execution_metrics_signals.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//std:aligner_metrics_policy.clk",
        "//std:cog_metrics_policy.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:aligner",
        "//clockwork/dsl/ir:aligner_metrics_report_groups",
        "//clockwork/dsl/ir:cog_metrics_report_groups",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:report_group",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "aligner_test",
    srcs = [
        "aligner_test.py",
        ":__test__",
    ],
    data = ["//std:aligner_metrics_policy.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:aligner",
        "//clockwork/dsl/ir:aligner_builtins",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:dfl",
        "//clockwork/dsl/ir:dfl_types",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "box_test",
    srcs = [
        "box_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:clk_hellobox.clk",
        "//clockwork/dsl/tests/support:clk_hellocog.clk",
        "//clockwork/dsl/tests/support:clk_hellomod.clk",
        "//clockwork/dsl/tests/support:clk_hellomsg.clk",
        "//clockwork/dsl/tests/support:clk_parameterized_box.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomod.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/dsl/tests/support:parameterized_types.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//clockwork/io:var_packet.clk",
        "//std:signals.clk",
        "//std:traits.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:signal_registry",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "clkenum_history_test",
    srcs = [
        "clkenum_history_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "clkenum_test",
    srcs = [
        "clkenum_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomsg.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "cog_metrics_report_groups_test",
    srcs = [
        "cog_metrics_report_groups_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:cog_execution_metrics_signals.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//std:cog_metrics_policy.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_metrics_report_groups",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:report_group",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:units",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "cog_metrics_schema_generation_test",
    srcs = [
        "cog_metrics_schema_generation_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:clk_hellocog.clk",
        "//clockwork/dsl/tests/support:clk_hellomsg.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_metrics_schema_generation",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
    ],
)

py_test(
    name = "cog_test",
    srcs = [
        "cog_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:cog_execution_metrics_signals.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:clk_hellocog.clk",
        "//clockwork/dsl/tests/support:clk_hellomsg.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/dsl/tests/support:parameterized_box.clk",
        "//clockwork/dsl/tests/support:parameterized_types.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//std:cog_metrics_policy.clk",
        "//std:traits.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:aligner",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_components",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "compiler_test",
    srcs = [
        "compiler_test.py",
        ":__test__",
    ],
    data = [],
    main = ":__test__.py",
    deps = [
        ":__test__",
        ":node_test",
        "//clockwork/dsl/bazel:clk_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/cpp:typereg",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:strongtypes",
        "//clockwork/dsl/ir:uuid_reg",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "constants_test",
    srcs = [
        "constants_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/tests/support:clk_constants.clk",
        "//clockwork/dsl/tests/support:constants.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:py_target",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:statement",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "conversion_utils_test",
    srcs = [
        "conversion_utils_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:conversion_utils",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:interface",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "cpp_executable_test",
    srcs = [
        "cpp_executable_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/ir/tests/support:clk_parametrized_box.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:cc_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_executable",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "cpp_extern_test",
    srcs = [
        "cpp_extern_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/cpp:typereg",
        "//clockwork/dsl/cpp:types",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:strongtypes",
        "//clockwork/dsl/serialization:tap",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "cpp_target_test",
    srcs = [
        "cpp_target_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:clk_hellocog.clk",
        "//clockwork/dsl/tests/support:clk_hellomod.clk",
        "//clockwork/dsl/tests/support:clk_hellomsg.clk",
        "//clockwork/dsl/tests/support:clk_protomsg.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomod.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/dsl/tests/support:nanobind_type_casters.clk",
        "//clockwork/dsl/tests/support:protomsg.clk",
        "//clockwork/io:var_packet.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:cc_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/cpp:typereg",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_executable",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:interface",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:nanobind_type_casters",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "dfl_analysis_test",
    srcs = [
        "dfl_analysis_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:clockwork_parser",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:dfl",
        "//clockwork/dsl/ir:dfl_analysis",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:primitive",
        "@fltk",
    ],
)

py_test(
    name = "dfl_integration_test",
    srcs = [
        "dfl_integration_test.py",
        ":__test__",
    ],
    data = ["//std:traits.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:clockwork_parser",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:dfl",
        "//clockwork/dsl/ir:dfl_analysis",
        "//clockwork/dsl/ir:dfl_types",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
        "@clockwork_pip//typing_extensions",
        "@fltk",
    ],
)

py_test(
    name = "dfl_test",
    srcs = [
        "dfl_test.py",
        ":__test__",
    ],
    data = ["//std:traits.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:clockwork_parser",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:dfl",
        "//clockwork/dsl/ir:dfl_types",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:units",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
        "@clockwork_pip//typing_extensions",
        "@fltk",
    ],
)

py_test(
    name = "dfl_traits_test",
    srcs = [
        "dfl_traits_test.py",
        ":__test__",
    ],
    data = ["//std:traits.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:dfl_traits",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "dfl_types_test",
    srcs = [
        "dfl_types_test.py",
        ":__test__",
    ],
    data = ["//std:traits.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:dfl_types",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "diagnostics_test",
    srcs = [
        "diagnostics_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:diagnostics",
    ],
)

py_test(
    name = "expr_test",
    srcs = [
        "expr_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl:clockwork_parser",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
        "@fltk",
    ],
)

py_test(
    name = "extern_type_test",
    srcs = [
        "extern_type_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/cpp:context",
        "//clockwork/dsl/cpp:typereg",
        "//clockwork/dsl/cpp:types",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_extern",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:extern_type",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "fmt_string_test",
    srcs = [
        "fmt_string_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:fmt_string",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:statement",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "hardware_test",
    srcs = [
        "hardware_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/tests/support:clk_cpu_domains_clk",
        "//clockwork/dsl/tests/support:hellomod_clk",
        "//std:pcie.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:pubsub",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "importer_test",
    srcs = [
        "importer_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:schema",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "module_id_test",
    srcs = [
        "module_id_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "nanobind_target_test",
    srcs = [
        "nanobind_target_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomsg.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:nanobind_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:nanobind_binding",
        "//clockwork/dsl/ir:nanobind_target",
        "//clockwork/dsl/ir:nanobind_target_render",
        "//clockwork/dsl/ir:nanobinding_registry",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:statement",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "node_test",
    srcs = [
        "node_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "@clockwork_pip//pytest",
        "@clockwork_pip//typing_extensions",
    ],
)

py_test(
    name = "path_resolver_test",
    srcs = [
        "path_resolver_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:path_resolver",
    ],
)

py_test(
    name = "policy_test",
    srcs = [
        "policy_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/tests/support:test_logging_policy_clk",
        "//clockwork/dsl/tests/support:testpolicy.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:logger_config",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "primitive_test",
    srcs = [
        "primitive_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomsg_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:units",
        "@clockwork_pip//pytest",
        "@clockwork_pip//typing_extensions",
    ],
)

py_test(
    name = "proto_target_test",
    srcs = [
        "proto_target_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/tests/support:clk_protomsg.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/dsl/tests/support:protomsg.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:proto_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:proto_target",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/proto:proto_typereg",
        "//clockwork/dsl/serialization:protobuf_clk",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "pubsub_test",
    srcs = [
        "pubsub_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:hellocog.clk",
        "//clockwork/dsl/tests/support:hellomod.clk",
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/io:var_packet.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "py_target_test",
    srcs = [
        "py_target_test.py",
        ":__test__",
    ],
    data = ["//jewels/units/clk:au_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:py_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:py_target",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "py_target_v2_test",
    srcs = [
        "py_target_v2_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/python:typereg",
        "//clockwork/dsl/serialization:pytap",
        "//clockwork/dsl/tests/support:py_bindings_v2_clk_py",
        "//clockwork/dsl/tests/support:py_bindings_v2_ext_clk_py",
        "//jewels/container/tap:py_var_array",
        "//jewels/container/tap:value_serdes",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "report_group_schema_generation_test",
    srcs = [
        "report_group_schema_generation_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//std:signals.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "report_group_schema_test",
    srcs = ["report_group_schema_test.cc"],
    deps = [
        "//clockwork/dial:include_common",
        "//clockwork/dsl/ir/tests/support:report_group_defs_clk_cc_dial",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "report_group_test",
    srcs = [
        "report_group_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//std:signals.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_components",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:report_group",
        "//clockwork/dsl/ir:signal",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "representation_test",
    srcs = [
        "representation_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomsg.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:schema_reg",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "schema_test",
    srcs = [
        "schema_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomsg.clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:clockwork_cst_protocol",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:parse",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:strongtypes",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/tests/support:py_test_utils",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "signal_policy_validation_test",
    srcs = [
        "signal_policy_validation_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:signal_policy_validation",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "snapshot_test",
    srcs = [
        "snapshot_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:test_snapshot_policy_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:pdf",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:pubsub",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "strongtypes_test",
    srcs = [
        "strongtypes_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:strongtypes",
    ],
)

py_test(
    name = "system_test",
    srcs = [
        "system_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/logging:channel_policy_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:uuid_reg",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tensor_test",
    srcs = [
        "tensor_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:strongtypes",
        "//clockwork/dsl/ir:tensor_builtins",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "typesys_test",
    srcs = [
        "typesys_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:statement",
        "//clockwork/dsl/ir:typesys",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "udp_test",
    srcs = [
        "udp_test.py",
        ":__test__",
    ],
    data = ["//clockwork/io:var_packet_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "uuid_reg_test",
    srcs = [
        "uuid_reg_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:uuid_reg",
        "@clockwork_pip//pytest",
    ],
)
