# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "aligned_storage",
    srcs = ["aligned_storage.inl"],
    hdrs = ["aligned_storage.hh"],
)

cc_library(
    name = "allocator_deleter",
    srcs = ["allocator_deleter.inl"],
    hdrs = ["allocator_deleter.hh"],
)

cc_library(
    name = "bits",
    srcs = ["bits.inl"],
    hdrs = ["bits.hh"],
)

cc_library(
    name = "default_memory_resource",
    srcs = ["default_memory_resource.cc"],
    hdrs = ["default_memory_resource.hh"],
    deps = [":memory_resource"],
)

cc_library(
    name = "error",
    srcs = ["error.cc"],
    hdrs = ["error.hh"],
)

cc_library(
    name = "fields",
    srcs = ["fields.inl"],
    hdrs = ["fields.hh"],
    deps = [
        ":bits",
        "//jewels/meta:concepts",
        "//jewels/meta:types",
        "//jewels/std:functional",
        "@boost.iterator",
    ],
)

cc_library(
    name = "instrumented_pmr_resource",
    srcs = ["instrumented_pmr_resource.cc"],
    hdrs = ["instrumented_pmr_resource.hh"],
    deps = [
        "//jewels/callsig:outparam",
        "//jewels/container:bounded_string",
    ],
)

cc_library(
    name = "memory_resource",
    srcs = ["memory_resource.inl"],
    hdrs = ["memory_resource.hh"],
    deps = [
        ":instrumented_pmr_resource",
        ":pointers",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
    ],
)

cc_library(
    name = "new_delete_memory_resource",
    srcs = ["new_delete_memory_resource.cc"],
    hdrs = ["new_delete_memory_resource.hh"],
    deps = [
        ":instrumented_pmr_resource",
        "//jewels/callsig:outparam",
        "//jewels/log_cerr",
        "//jewels/std:atomic",
    ],
)

cc_library(
    name = "pmr_shared_ptr",
    srcs = ["pmr_shared_ptr.inl"],
    hdrs = ["pmr_shared_ptr.hh"],
    deps = [":memory_resource"],
)

cc_library(
    name = "pmr_unique_ptr",
    srcs = ["pmr_unique_ptr.inl"],
    hdrs = ["pmr_unique_ptr.hh"],
    deps = [":allocator_deleter"],
)

cc_library(
    name = "pointers",
    srcs = ["pointers.inl"],
    hdrs = ["pointers.hh"],
    deps = [
        ":error",
        ":pmr_unique_ptr",
        "//jewels/std:expected",
        "@gsl//:pointers",
    ],
)

py_library(
    name = "py_bytes",
    srcs = ["py_bytes.py"],
    imports = ["../.."],
)

cc_library(
    name = "unique_object",
    srcs = ["unique_object.inl"],
    hdrs = ["unique_object.hh"],
    deps = [
        "//jewels/meta:call",
        "//jewels/meta:type_traits",
    ],
)
