# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_cc_binding", "py_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "abstract_log_reader",
    srcs = ["abstract_log_reader.cc"],
    hdrs = ["abstract_log_reader.hh"],
    deps = [
        ":types",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "log_processor",
    srcs = [
        "log_processor.cc",
        "log_processor.inl",
    ],
    hdrs = ["log_processor.hh"],
    deps = [
        ":abstract_log_reader",
        ":log_reader",
        ":serialization",
        ":types",
        "//clockwork:repr_iface",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/serialization/cpp:tachyon_upgrader",
        "//jewels/log_cerr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@wise_enum",
    ],
)

cc_library(
    name = "log_reader",
    srcs = ["log_reader.cc"],
    hdrs = ["log_reader.hh"],
    deps = [
        ":abstract_log_reader",
        ":log_reader_factory",
        ":types",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//jewels/log_cerr",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "log_reader_factory",
    srcs = ["log_reader_factory.cc"],
    hdrs = ["log_reader_factory.hh"],
    deps = [
        ":abstract_log_reader",
        ":mcap_log_reader",
        ":offboard_log_reader",
        ":onboard_log_reader",
        ":types",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging/offboard:chunk_reader_writer_factory",
        "//clockwork/logging/offboard:log_format",
        "//clockwork/logging/offboard:log_uri",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:offboard_buffered_reader",
        "//jewels/container:circular_buffer",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "@fmt",
        "@gsl//:util",
    ],
)

cc_library(
    name = "mcap_log_reader",
    srcs = ["mcap_log_reader.cc"],
    hdrs = ["mcap_log_reader.hh"],
    deps = [
        ":abstract_log_reader",
        ":types",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//jewels/log_cerr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "@mcap",
        "@wise_enum",
    ],
)

py_cc_binding(
    name = "nb_log_processor",
    srcs = ["nb_log_processor.cc"],
    py_deps = [":nb_types"],
    # TODO(OI-3058): use the autogenerated one once cross-workspace shared libraries in nanobindings work properly
    pyi_file = "nb_log_processor.pyi",
    deps = [
        ":log_processor",
        ":types",
        "//clockwork/logging:log_timestamp",
        "//jewels/std:expected",
        "@nanobind",
    ],
)

py_cc_binding(
    name = "nb_log_reader",
    srcs = ["nb_log_reader.cc"],
    py_deps = [":nb_types"],
    # TODO(OI-3058): use the autogenerated one once cross-workspace shared libraries in nanobindings work properly
    pyi_file = "nb_log_reader.pyi",
    deps = [
        ":log_reader",
        ":types",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/offboard:chunk_reader_writer_factory",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:span",
        "@fmt",
        "@nanobind",
    ],
)

py_cc_binding(
    name = "nb_types",
    srcs = ["nb_types.cc"],
    imports = ["../../.."],
    deps = [
        ":types",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging:schema_encoding_clk_cc",
        "@fmt",
        "@nanobind",
        "@wise_enum",
    ],
)

cc_library(
    name = "offboard_log_reader",
    srcs = ["offboard_log_reader.cc"],
    hdrs = ["offboard_log_reader.hh"],
    deps = [
        ":abstract_log_reader",
        ":types",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/offboard:chunk_reader_writer_factory",
        "//clockwork/logging/offboard:reader",
        "//clockwork/logging/offboard:types",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "onboard_log_reader",
    srcs = ["onboard_log_reader.inl"],
    hdrs = ["onboard_log_reader.hh"],
    deps = [
        ":abstract_log_reader",
        ":types",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/offboard:s3_utils",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:offboard_buffered_reader",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//jewels/filesystem",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
    ],
)

py_library(
    name = "py_log_processor",
    srcs = ["py_log_processor.py"],
    deps = [
        ":nb_log_processor",
        ":nb_types",
        "//clockwork/dsl:compiler_context",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/py:compatibility",
        "//clockwork/serialization/py:protocol",
        "//clockwork/serialization/py:tachyon_dyn_from_metadata",
    ],
)

py_library(
    name = "py_log_reader",
    srcs = ["py_log_reader.py"],
    deps = [
        ":nb_log_reader",
        ":nb_types",
        "//clockwork/dsl:compiler_context",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/py:compatibility",
        "//clockwork/serialization/py:protocol",
        "//clockwork/serialization/py:tachyon_dyn_from_metadata",
    ],
)

py_library(
    name = "py_types",
    srcs = ["py_types.py"],
    deps = [":nb_types"],
)

cc_library(
    name = "serialization",
    hdrs = ["serialization.hh"],
    deps = [
        "//clockwork:repr_iface",
        "@boost.core",
        "@fmt",
    ],
)

cc_library(
    name = "types",
    hdrs = ["types.hh"],
    deps = [
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
    ],
)
