# Autogenerated .pyi file for nb_log_processor.
#
# This has to be here because it depends on aws_init.so in the @clockwork bazel workspace,
# which the nanobind stub generator has issues with.
#
# TODO(OI-3058): autogenerate this once cross-workspace shared libraries in nanobindings work properly.

from collections.abc import Callable

import clockwork.logging.readers.nb_types

class LogProcessor:
    def __init__(self, config: clockwork.logging.readers.nb_types.LogReaderConfig) -> None:
        """Constructor."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def add_raw_msg_callback(
        self, topic: str, callback: Callable[[clockwork.logging.readers.nb_types.LoggedMessage], None]
    ) -> None:
        """Add raw message callback."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def try_get_topic_metadata(self, topic: str) -> clockwork.logging.readers.nb_types.TopicMetadata | None:
        """Get topic metadata."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def try_get_metrics(self) -> clockwork.logging.readers.nb_types.LogMetrics | None:
        """Get log metrics."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def process(self) -> bool:
        """Process the log."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def next(self) -> clockwork.logging.readers.nb_types.LoggedMessage | None:
        """Advance to the next message."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def abort(self) -> None:
        """Abort log processing."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def start_time(self) -> clockwork.logging.readers.nb_types.LogTimestamp | None:
        """Log start time."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def end_time(self) -> clockwork.logging.readers.nb_types.LogTimestamp | None:
        """Log end time."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def topics(self) -> list[clockwork.logging.readers.nb_types.TopicMetadata]:
        """Logged topics."""  # noqa: PYI021 (Nanobind stubs need docstrings)
