# Autogenerated .pyi file for nb_log_reader.
#
# This has to be here because it depends on aws_init.so in the @clockwork bazel workspace,
# which the nanobind stub generator has issues with.
#
# TODO(OI-3058): autogenerate this once cross-workspace shared libraries in nanobindings work properly.

from collections.abc import Callable, Iterator

import clockwork.logging.readers.nb_types

class LogReader:
    def __init__(
        self,
        log_uri: str,
        maybe_log_interval: clockwork.logging.readers.nb_types.LogInterval | None = None,
        maybe_relative_interval: clockwork.logging.readers.nb_types.RelativeInterval | None = None,
    ) -> None:
        """Constructor."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def raw_messages(
        self, topic_filter: Callable[[str], bool] | None = None
    ) -> Iterator[clockwork.logging.readers.nb_types.LoggedMessage]:
        """Logged message iterator."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def try_get_topic_metadata(self, topic: str) -> clockwork.logging.readers.nb_types.TopicMetadata | None:
        """Get topic metadata."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def try_get_metrics(self) -> clockwork.logging.readers.nb_types.LogMetrics | None:
        """Get log metrics."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def start_time(self) -> clockwork.logging.readers.nb_types.LogTimestamp | None:
        """Log start time."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def end_time(self) -> clockwork.logging.readers.nb_types.LogTimestamp | None:
        """Log end time."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    @property
    def metadata(self) -> list[clockwork.logging.readers.nb_types.TopicMetadata]:
        """Logged topic metadata."""  # noqa: PYI021 (Nanobind stubs need docstrings)
