# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

cc_test(
    name = "deterministic_runner_periodic_test",
    srcs = ["deterministic_runner_periodic_test.cc"],
    data = ["//clockwork/tests/support:clockwork.clockwork.tests.support.test_periodic_system.test_periodic_system.proc.tachyon"],
    deps = [
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:test_periodic_system_lib",  # keep
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "logical_system_interface_test",
    srcs = [
        "logical_system_interface_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/tests/resources:restore_test_config.textproto",
        "//clockwork/tests/resources:snapshot_test_config.textproto",
        "//clockwork/tests/support:logical_system_interface_test_system_clk",
        "//clockwork/tests/support:restore_log_config_system_clk",
        "//clockwork/tests/support:test_system_description_2_clk",
        "//clockwork/tests/support:test_system_description_clk",
        "//clockwork/tests/support:test_system_multi_node_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork:logical_system_interface",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "process_test",
    srcs = ["process_test.cc"],
    data = ["//clockwork/tests/support:clockwork.clockwork.tests.support.test_system.test_system.proc.tachyon"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_subscriber",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:slot_ref",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/pinion/tests/support:pub_sub",
        "//clockwork/scaffolding:end_process_exception",
        "//clockwork/scaffolding:main_impl",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/scaffolding/tests/support:runtime_tools",
        "//clockwork/scaffolding/tests/support:test_cogs_dial",
        "//clockwork/scaffolding/tests/support:test_msgs_clk_cc",
        "//clockwork/tests/support:test_system_exe_library",  # keep
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/utility:fix_clockwork_path",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "restore_log_config_test",
    srcs = ["restore_log_config_test.cc"],
    data = [
        "//clockwork/tests/resources:restore_test_config.textproto",
        "//clockwork/tests/support:clockwork.clockwork.tests.support.restore_log_config_system.restore_log_config_system.proc.tachyon",
        "//clockwork/tests/support:restore_log_config_system.restore_log_config_system.RestoreLogConfigCpu_channel_publisher_config.tachyon",
        "//clockwork/tests/support:restore_log_config_system.restore_log_config_system.RestoreLogConfigCpu_telemetry_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/runners:channel_publisher",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:exec_time",
        "//clockwork/tests/support:restore_log_config_system_lib",  # keep
        "//clockwork/tests/support:snapshot_test_messages",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "restore_log_state_default_test",
    srcs = ["restore_log_state_default_test.cc"],
    data = [
        "//clockwork/tests/resources:snapshot_test_config.textproto",
        "//clockwork/tests/support:clockwork.clockwork.tests.support.restore_log_state_default_system.restore_log_state_default_system.proc.tachyon",
        "//clockwork/tests/support:restore_log_state_default_system.restore_log_state_default_system.RestoreLogStateDefaultCpu_channel_publisher_config.tachyon",
        "//clockwork/tests/support:restore_log_state_default_system.restore_log_state_default_system.RestoreLogStateDefaultCpu_telemetry_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/runners:channel_publisher",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:exec_time",
        "//clockwork/tests/support:restore_log_state_default_system_lib",  # keep
        "//clockwork/tests/support:snapshot_test_messages",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "restore_log_state_test",
    srcs = ["restore_log_state_test.cc"],
    data = [
        "//clockwork/tests/resources:snapshot_test_config.textproto",
        "//clockwork/tests/support:clockwork.clockwork.tests.support.restore_log_state_system.restore_log_state_system.proc.tachyon",
        "//clockwork/tests/support:restore_log_state_system.restore_log_state_system.RestoreLogStateCpu_channel_publisher_config.tachyon",
        "//clockwork/tests/support:restore_log_state_system.restore_log_state_system.RestoreLogStateCpu_telemetry_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/runners:channel_publisher",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:exec_time",
        "//clockwork/tests/support:restore_log_state_system_lib",  # keep
        "//clockwork/tests/support:snapshot_test_messages",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "restore_protobuf_state_test",
    srcs = ["restore_protobuf_state_test.cc"],
    data = [
        "//clockwork/tests/resources:restore_test_state.textproto",
        "//clockwork/tests/resources:snapshot_test_config.textproto",
        "//clockwork/tests/support:clockwork.clockwork.tests.support.restore_protobuf_state_system.restore_protobuf_state_system.proc.tachyon",
        "//clockwork/tests/support:restore_protobuf_state_system.restore_protobuf_state_system.RestoreProtobufStateCpu_channel_publisher_config.tachyon",
        "//clockwork/tests/support:restore_protobuf_state_system.restore_protobuf_state_system.RestoreProtobufStateCpu_telemetry_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/runners:channel_publisher",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:exec_time",
        "//clockwork/tests/support:restore_protobuf_state_system_lib",  # keep
        "//clockwork/tests/support:snapshot_test_messages",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "signal_report_group_test",
    srcs = ["signal_report_group_test.cc"],
    data = [
        "//clockwork/tests/support:clockwork.clockwork.tests.support.signal_test_system.signal_test_system.proc.tachyon",
        "//clockwork/tests/support:signal_test_system.signal_test_system.SignalTestCpu_event_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_interval",
        "//clockwork/logging/readers:offboard_log_reader",
        "//clockwork/logging/readers:types",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:signal_cog_clk_cc",
        "//clockwork/tests/support:signal_cog_clk_cc_dial",
        "//clockwork/tests/support:signal_test_box_clk_exe_lib",  # keep
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/filesystem:path",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "//jewels/uuid",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "snapshot_test",
    srcs = ["snapshot_test.cc"],
    data = [
        "//clockwork/tests/resources:snapshot_test_config.textproto",
        "//clockwork/tests/support:clockwork.clockwork.tests.support.snapshot_test_system.snapshot_test_system.proc.tachyon",
        "//clockwork/tests/support:snapshot_test_system.snapshot_test_system.SnapshotTestCpu_channel_publisher_config.tachyon",
        "//clockwork/tests/support:snapshot_test_system.snapshot_test_system.SnapshotTestCpu_telemetry_logger_config.tachyon",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/runners:channel_publisher",
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//clockwork/tests/support:exec_time",
        "//clockwork/tests/support:snapshot_test_messages",
        "//clockwork/tests/support:snapshot_test_system_lib",  # keep
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)
