# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "log_cerr_test",
    srcs = ["log_cerr_test.cc"],
    deps = [
        "//jewels/log_cerr",
        "@catch2//:catch2_main",
        "@fmt",
    ],
)

# Smoke test - prints all levels, always returns success.
cc_test(
    name = "log_cerr_threshold_test",
    srcs = ["log_cerr_threshold_test.cc"],
    deps = [
        "//jewels/log_cerr",
        "@catch2//:catch2_main",
    ],
)
