# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

cc_library(
    name = "ifaddrs",
    srcs = ["ifaddrs.cc"],
    hdrs = ["ifaddrs.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/filesystem:error_code",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "sock_opt",
    srcs = [
        "sock_opt.cc",
        "sock_opt.inl",
    ],
    hdrs = ["sock_opt.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":ifaddrs",
        "//jewels/filesystem:error_code",
        "//jewels/meta:overloaded",
        "//jewels/std:expected",
        "@wise_enum",
    ],
)

cc_library(
    name = "socket_address",
    srcs = [
        "socket_address.cc",
        "socket_address.inl",
    ],
    hdrs = ["socket_address.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/filesystem:error_code",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "socket_endpoint",
    srcs = [
        "socket_endpoint.cc",
        "socket_endpoint.inl",
    ],
    hdrs = ["socket_endpoint.hh"],
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)

cc_library(
    name = "sockets",
    srcs = ["sockets.cc"],
    hdrs = ["sockets.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/std:expected",
    ],
)
