# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config")
load("//tools/rules:cc.bzl", "cc_binary", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "bridge_test_support",
    srcs = [
        "bridge_test_support.cc",
        "bridge_test_support.inl",
    ],
    hdrs = ["bridge_test_support.hh"],
    deps = [
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:xxh3_checksum",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/pinion:tcp_bridge_common",
        "//clockwork/pinion:tcp_bridge_server",
        "//clockwork/pinion/detail:socket_common",
        "//clockwork/pinion/detail:tcp_socket",
        "//jewels/callsig:outparam",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/memory:memory_resource",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_library(
    name = "epoll_snooper",
    srcs = ["epoll_snooper.cc"],
    hdrs = ["epoll_snooper.hh"],
    deps = [
        "//clockwork/common:abstract_epoll_manager",
        "//jewels/filesystem:error_code",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "mock_buffer",
    hdrs = ["mock_buffer.hh"],
    deps = [
        ":mock_slot",
        "//clockwork/pinion:buffer",
        "//jewels/std:span",
    ],
)

cc_library(
    name = "mock_slot",
    hdrs = ["mock_slot.hh"],
    deps = ["//clockwork/pinion:slot"],
)

clk(
    name = "optional_connected_test_system_clk",
    srcs = ["optional_connected_test_system.clk"],
    outs = [
        "clockwork.clockwork.pinion.tests.support.optional_connected_test_system.optionally_connected_system.proc.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_channel_allocations.csv",
        "optional_connected_test_system.optionally_connected_system.SimCpu_channel_spy_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_event_logger_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_metrics_channel_metadata_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_signal_metadata_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_simplelaunch_config.textproto",
        "optional_connected_test_system.optionally_connected_system.SimCpu_telemetry_logger_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.diagnostics_database_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.logged_channel_metadata.pbbin",
        "optionally_connected_cog.cc",
        "optionally_connected_cog.hh",
        "optionally_connected_cog.inl",
        "optionally_connected_cog_dial.cc",
        "optionally_connected_cog_dial.hh",
        "optionally_connected_cog_dial.inl",
        "optionally_connected_system_exe.cc",
        "optionally_connected_system_exe.hh",
        "optionally_connected_system_exe.inl",
    ],
    deps = [
        ":test_message_clk",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk",
    ],
)

cc_library(
    name = "optionally_connected_cog",
    srcs = [
        "optionally_connected_cog.cc",
        "optionally_connected_cog.inl",
    ],
    hdrs = ["optionally_connected_cog.hh"],
    data = [":optional_connected_test_system_clk"],
    deps = [
        ":optionally_connected_cog_dial",
        ":optionally_connected_cog_impl",
        ":test_message",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/cog:include_common",
        "//clockwork/dsl/cog:common_cog_event_metrics_clk_cc",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics_clk_cc",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/utility:enum_flags",
        "@wise_enum",
    ],
    alwayslink = True,
)

cc_library(
    name = "optionally_connected_cog_dial",
    srcs = [
        "optionally_connected_cog_dial.cc",
        "optionally_connected_cog_dial.inl",
    ],
    hdrs = ["optionally_connected_cog_dial.hh"],
    data = [":optional_connected_test_system_clk"],
    deps = [
        ":test_message",
        "//clockwork/dial:include_common",
    ],
)

cc_library(
    name = "optionally_connected_cog_impl",
    srcs = ["optionally_connected_cog_impl.cc"],
    deps = [
        ":optionally_connected_cog_dial",
        "//clockwork/dial:msg_input",
        "//clockwork/pinion:publishable",
        "@catch2//:catch2_main",
    ],
)

cc_binary(
    name = "optionally_connected_system_exe",
    srcs = [
        "optionally_connected_system_exe.cc",
        "optionally_connected_system_exe.hh",
        "optionally_connected_system_exe.inl",
    ],
    deps = [
        ":optionally_connected_cog",
        ":test_message",
        "//clockwork:repr_iface",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:casing",
        "//clockwork/scaffolding:offline_main",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
    ],
)

cc_library(
    name = "optionally_connected_system_lib",
    srcs = [
        "optionally_connected_system_exe.cc",
        "optionally_connected_system_exe.inl",
    ],
    hdrs = ["optionally_connected_system_exe.hh"],
    deps = [
        ":optionally_connected_cog",
        ":test_message",
        "//clockwork:repr_iface",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:casing",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
    ],
)

cc_library(
    name = "pub_sub",
    hdrs = ["pub_sub.hh"],
    deps = [
        ":tmp_shm_namespace",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:forward",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//clockwork/pinion:shm_subscriber",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:file",
        "//jewels/filesystem:mmap_region",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@catch2//:catch2_main",
    ],
)

merge_simplelaunch_config(
    name = "simcpu.textproto",
    srcs = [
        "optional_connected_test_system.optionally_connected_system.SimCpu_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.pinion.tests.support.optional_connected_test_system.optionally_connected_system.proc.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_channel_allocations.csv",
        "optional_connected_test_system.optionally_connected_system.SimCpu_channel_spy_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_event_logger_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_metrics_channel_metadata_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_signal_metadata_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.SimCpu_telemetry_logger_config.tachyon",
        "optional_connected_test_system.optionally_connected_system.diagnostics_database_config.tachyon",
        ":optionally_connected_system_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)

cc_library(
    name = "sockets",
    srcs = [
        "sockets.cc",
        "sockets.inl",
    ],
    hdrs = ["sockets.hh"],
    deps = [
        ":udp_payloads",
        "//clockwork/io:network_var_packet_clk_cc",
        "//clockwork/io:var_packet_clk_cc",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:publisher_handle",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/memory:pointers",
        "//jewels/networking:socket_address",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "test_message",
    srcs = [
        "test_message.cc",
        "test_message.inl",
    ],
    hdrs = ["test_message.hh"],
    data = [":test_message_clk"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_message_clk",
    srcs = ["test_message.clk"],
    outs = [
        "test_message.cc",
        "test_message.hh",
        "test_message.inl",
    ],
)

cc_library(
    name = "tmp_shm_namespace",
    srcs = ["tmp_shm_namespace.cc"],
    hdrs = ["tmp_shm_namespace.hh"],
    deps = [
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//jewels/filesystem:file",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/testing:tmp_directory_guard",
    ],
)

cc_library(
    name = "udp_payloads",
    srcs = ["udp_payloads.inl"],
    hdrs = ["udp_payloads.hh"],
    deps = [
        "//clockwork/io:network_var_packet_clk_cc",
        "//clockwork/io:var_packet_clk_cc",
        "//jewels/std:span",
    ],
)
