# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/demo_system:__subpackages__"],
)

clk(
    name = "perception_channel_policies_clk",
    srcs = ["perception_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":perception_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "perception_channels_clk",
    srcs = ["perception_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":perception_message_clk",
        "//clockwork/dial:approx_aligner_config_clk",
    ],
)

clk(
    name = "perception_clk",
    srcs = ["perception.clk"],
    outs = [
        "perception_clk_cc.cc",
        "perception_clk_cc.hh",
        "perception_clk_cc.inl",
        "perception_clk_cc_dial.cc",
        "perception_clk_cc_dial.hh",
        "perception_clk_cc_dial.inl",
        "perception_clk_exe.cc",
        "perception_clk_exe.hh",
        "perception_clk_exe.inl",
    ],
    cpp_deps = [
        ":perception_message_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_proto_conv",
        "//clockwork/examples/demo_system/camera:video_message_clk_cc",
        "//clockwork/examples/demo_system/lidar:lidar_message_clk_cc",
        "//clockwork/examples/demo_system/localization:pose_message_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    proto_deps = ["//clockwork/dial:approx_aligner_config_clk_proto"],
    deps = [
        ":perception_channels_clk",
        ":perception_message_clk",
        "//clockwork/dial:approx_aligner_config_clk",
        "//clockwork/examples/demo_system:cpu_domain_clk",
        "//clockwork/examples/demo_system/camera:video_channels_clk",
        "//clockwork/examples/demo_system/camera:video_message_clk",
        "//clockwork/examples/demo_system/lidar:lidar_channels_clk",
        "//clockwork/examples/demo_system/lidar:lidar_message_clk",
        "//clockwork/examples/demo_system/localization:localization_channels_clk",
        "//clockwork/examples/demo_system/localization:pose_message_clk",
    ],
)

cc_library(
    name = "perception_clk_cc_impl",
    srcs = ["perception_clk_cc_impl.cc"],
    data = ["//clockwork/examples/demo_system/perception/resources:approx_aligner_config.textproto"],
    deps = [
        ":perception_clk_cc_dial",
        ":perception_message_clk_cc",
        "//clockwork/dial:approx_aligner",
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/dial:approx_aligner_policies",
        "//clockwork/examples/demo_system/camera:video_message_clk_cc",
        "//clockwork/examples/demo_system/lidar:lidar_message_clk_cc",
        "//clockwork/examples/demo_system/localization:pose_message_clk_cc",
        "//clockwork/pinion:publishable",
        "//jewels/container:circular_buffer",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "@boost//:iterator",
    ],
)

clk(
    name = "perception_message_clk",
    srcs = ["perception_message.clk"],
    outs = [
        "perception_message_clk_cc.cc",
        "perception_message_clk_cc.hh",
        "perception_message_clk_cc.inl",
    ],
    generate = ["cpp"],
)
