# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@gazelle//:def.bzl", "gazelle_binary")
load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cc_plugin",
    srcs = ["extension.go"],
    data = [":third_party_mapping"],
    importpath = "github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin",
    visibility = ["//visibility:public"],
    deps = [
        "//tools/gazelle/cc_plugin/language",
        "@@gazelle+//language",
    ],
)

go_test(
    name = "cc_plugin_test",
    srcs = ["extension_test.go"],
    data = [
        ":gazelle_cc_test_binary",
        ":test_filemap",
    ],
    embed = [":cc_plugin"],
    rundir = ".",
    deps = [
        "@@gazelle+//testtools",
        "@com_github_stretchr_testify//require",
        "@org_skia_go_infra//bazel/go/bazel",
        "@org_skia_go_infra//go/testutils/unittest",
    ],
)

gazelle_binary(
    name = "gazelle_cc_test_binary",
    languages = [":cc_plugin"],
)

filegroup(
    name = "test_filemap",
    srcs = ["resources/test_filemap.json"],
)

filegroup(
    name = "third_party_mapping",
    srcs = ["resources/third_party_mapping.json"],
    visibility = ["//visibility:public"],
)
