// Copyright 2025 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

package language

import (
	"log"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/bazelbuild/buildtools/build"

	"github.com/emirpasic/gods/sets/treeset"
	godsutils "github.com/emirpasic/gods/utils"

	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/common"
	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/configurer"
	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/parsers"
	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/resolver"
)
const PyCCBindingRule = "py_cc_binding"

// CppLanguage implements the language.CppLanguage interface.
type CppLanguage struct {
	configurer.CppConfigurer
	resolver.CppResolver
}

// Kinds implements the language.CppLanguage interface.
//
// Interface documentation:
//
// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (l *CppLanguage) Kinds() map[string]rule.KindInfo {
	kindInfo := rule.KindInfo{
		// This extension generates content for deps, hdrs, and srcs, so that's why they are
		// specified here.
		ResolveAttrs: map[string]bool{"deps": true, "hdrs": true, "srcs": true},
		// NonEmptyAttrs must be non-nil, otherwise no rules will get deleted.
		// We don't have any fields that should prevent a rule from being deleted if the
		// underlying source file or header file is missing, so an empty map suffices.
		NonEmptyAttrs: map[string]bool{},
	}
	return map[string]rule.KindInfo{
		common.CCBinaryRule:  kindInfo,
		common.CCLibraryRule: kindInfo,
		common.CCTestRule:    kindInfo,
		// These are here so that we can correctly update the deps for a pre-existing target.
		PyCCBindingRule: kindInfo,
	}
}

// Loads implements the language.CppLanguage interface.
//
// Interface documentation:
//
// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (l *CppLanguage) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name: "@rules_cc//cc:defs.bzl",
			Symbols: []string{
				common.CCBinaryRule,
				common.CCLibraryRule,
				common.CCTestRule,
			},
		},
		{
			Name:    "//tools/rules:python.bzl",
			Symbols: []string{PyCCBindingRule},
		},
	}
}

// GenerateRules implements the language.CppLanguage interface.
//
// GenerateRules generates build rules for source files in a directory. GenerateRules is called in
// each directory where an update is requested in depth-first order.
//
// This method does not populate the deps argument of any generate rules. Dependencies are resolved
// in CppResolver.Resolve(), which happens after GenerateRules is called in each directory where an
// update is requested.
func (l *CppLanguage) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	allFiles := append(args.RegularFiles)
	rules := makeRulesFromFiles(allFiles)
	imports := getImportsFromRules(rules, args.Dir, l.ThirdPartyFileMap, l.ExternalRepos)

	var existingRules []*rule.Rule
	if args.File != nil {
		for _, preexistingRule := range args.File.Rules {
			for _, newRule := range rules {
				if preexistingRule.Name() == newRule.Name() && preexistingRule.Kind() != newRule.Kind() {
					// If a rule already exists with the name we want but a different kind, revert back to the
					// preexisting rule's kind.
					newRule.SetKind(preexistingRule.Kind())
					handleSharedLibraryRule(preexistingRule, newRule, formatSharedObjectName(newRule.Name()))
				} else if preexistingRule.Name() != newRule.Name() {
					sharedObjectName := formatSharedObjectName(newRule.Name())
					if preexistingRule.Name() == sharedObjectName {
						handleSharedLibraryRule(preexistingRule, newRule, sharedObjectName)
					}
				}
			}
		}

		existingRules = args.File.Rules
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
		Empty:   findEmptyRules(existingRules, rules),
	}
}

// handleSharedLibraryRule processes a preexisting rule of type CCBinaryRule with the "linkshared" attribute set to true.
// It copies non-generated attributes and ensures the rule's name adheres to the shared library naming convention
// (e.g., "lib<name>.so").
func handleSharedLibraryRule(preexistingRule, newRule *rule.Rule, sharedObjectName string) {
	if preexistingRule.Kind() == common.CCBinaryRule && attrBool(preexistingRule, "linkshared") {
		// Copy non-generated attributes from the preexisting rule to the new rule
		generatedAttrs := []string{"name", "srcs", "hdrs", "deps"}
		for _, attr := range preexistingRule.AttrKeys() {
			if !slices.Contains(generatedAttrs, attr) {
				newRule.SetAttr(attr, preexistingRule.Attr(attr))
			}
		}
		newRule.SetName(sharedObjectName)
	}
}

// formatSharedObjectName ensures the name follows the shared library naming convention (lib<name>.so).
func formatSharedObjectName(name string) string {
	prefix := "lib"
	suffix := ".so"

	// Add the "lib" prefix if it's missing
	if !strings.HasPrefix(name, prefix) {
		name = prefix + name
	}

	// Add the ".so" suffix if it's missing
	if !strings.HasSuffix(name, suffix) {
		name = name + suffix
	}

	return name
}

// attrBool retrieves a boolean-like attribute from a rule's attributes map.
// It checks if the attribute with the given key exists and interprets its value as a boolean.
// The function assumes that boolean values are represented as identifiers with the names True or False.
// If the attribute is not found or its value is not a recognized boolean identifier, the function defaults to returning false.
func attrBool(r *rule.Rule, key string) bool {
	attr := r.Attr(key)
	if attr == nil {
		return false
	}

	if ident, ok := attr.(*build.Ident); ok {
		if ident.Name == "True" {
			return true
		}
		if ident.Name == "False" {
			return false
		}
	}

	return false
}

// findEmptyRules returns any relevant rules which were in the rules from BUILD.bazel,
// but did not show up when we recreated all the rules from the source files. This means the
// underlying source files have been deleted or moved and the rules should as well.
func findEmptyRules(previous, new []*rule.Rule) []*rule.Rule {
	ruleCache := map[string]bool{}
	for _, r := range new {
		ruleCache[r.Name()] = true
	}
	allOuts := []string{}
	for _, r := range previous {
		if outs := r.AttrStrings("outs"); outs != nil {
			allOuts = append(allOuts, outs...)
		}
	}

	var empty []*rule.Rule
	for _, r := range previous {
		if r.Kind() != common.CCBinaryRule &&
			r.Kind() != common.CCLibraryRule &&
			r.Kind() != common.CCTestRule &&
			r.Kind() != PyCCBindingRule {
			continue
		}
		if _, ok := ruleCache[r.Name()]; !ok {
			// The rule wasn't created just now. See if its `srcs` come from another rule's `outs`.
			shouldKeepRule := false
			if srcs := r.AttrStrings("srcs"); srcs != nil {
				for _, src := range srcs {
					if slices.Contains(allOuts, src) {
						shouldKeepRule = true
					}
				}
			}
			if !shouldKeepRule {
				empty = append(empty, rule.NewRule(r.Kind(), r.Name()))
			}
		}
	}
	return empty
}

type ruleData struct {
	name string
	kind string
	srcs *treeset.Set
	hdrs *treeset.Set
}

// makeRulesFromFiles returns a single rule per filename stem, so
// foo.cc and foo.hh will be in a rule together.
func makeRulesFromFiles(names []string) []*rule.Rule {
	var rules = make(map[string]*ruleData)

	// Record the rule data in our own struct
	for _, name := range names {
		if !common.IsCppHeader(name) && !common.IsCppSource(name) {
			continue
		}
		stem := common.TrimCSuffix(name)

		// stem.cc.inl files should be merged into the stem target.
		if common.IsCppCcInl(name) {
			stem = common.GetCppCcInlStem(name)
		}

		rd, ok := rules[stem]
		if !ok {
			kind := common.CCLibraryRule
			if strings.HasSuffix(stem, "_test") {
				kind = common.CCTestRule
			} else if hasMainFunc(name) {
				kind = common.CCBinaryRule
			}
			data := ruleData{stem, kind, treeset.NewWith(godsutils.StringComparator), treeset.NewWith(godsutils.StringComparator)}
			rd = &data
			rules[stem] = rd
		}

		if common.IsCppHeader(name) {
			rd.hdrs.Add(name)
		} else {
			rd.srcs.Add(name)
		}
	}

	// Transfer that into a Gazelle rule struct, which internally stores attrs in
	// a way that they can't really be added to (which is why we collect beforehand).
	var rv []*rule.Rule
	for name, rd := range rules {
		r := rule.NewRule(rd.kind, name)
		if !rd.hdrs.Empty() {
			// convert hdrs.Values from interfaces to strings
			var hdrStrings []string
			for _, hdr := range rd.hdrs.Values() {
				hdrStrings = append(hdrStrings, hdr.(string))
			}
			r.SetAttr("hdrs", hdrStrings)
		}
		if !rd.srcs.Empty() {
			// convert srcs.Values from interfaces to strings
			var srcStrings []string
			for _, src := range rd.srcs.Values() {
				srcStrings = append(srcStrings, src.(string))
			}
			r.SetAttr("srcs", srcStrings)
		}
		rv = append(rv, r)
	}
	// Sort for determinism
	sort.Slice(rv, func(i, j int) bool {
		return rv[i].Name() < rv[j].Name()
	})
	return rv
}

// getImportsFromRules returns a list of common.ImportsParsedFromRuleSources, one per rule, that
// relate to the files that were listed via #include.
func getImportsFromRules(rules []*rule.Rule, dir string, thirdPartyMap []common.ThirdPartyMapItem, externalRepos []common.ExternalRepo) []interface{} {
	var rv []interface{}
	for _, r := range rules {
		var repoHeaders []common.Include
		var systemHeaders, thirdPartyHeaders []string
		hdrs := r.AttrStrings("hdrs")
		for _, hdr := range hdrs {
			rh, sh, tph := extractImportsFromCFile(filepath.Join(dir, hdr), externalRepos)
			repoHeaders = append(repoHeaders, rh...)
			systemHeaders = append(systemHeaders, sh...)
			thirdPartyHeaders = append(thirdPartyHeaders, tph...)
		}
		srcs := r.AttrStrings("srcs")
		for _, src := range srcs {
			rh, sh, tph := extractImportsFromCFile(filepath.Join(dir, src), externalRepos)
			repoHeaders = append(repoHeaders, rh...)
			systemHeaders = append(systemHeaders, sh...)
			thirdPartyHeaders = append(thirdPartyHeaders, tph...)
		}
		rv = append(rv, common.NewImports(repoHeaders, systemHeaders, thirdPartyHeaders, thirdPartyMap))
	}
	return rv
}

// extractImportsFromCFile opens ups the given file and parses the contents.
func extractImportsFromCFile(path string, externalRepos []common.ExternalRepo) ([]common.Include, []string, []string) {
	b, err := os.ReadFile(path)
	if err != nil {
		log.Panicf("Error reading file %q: %v", path, err)
	}
	return parsers.ParseCIncludes(string(b[:]), externalRepos)
}

func hasMainFunc(path string) bool {
	bytesContents, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	stringContents := string(bytesContents)

	searchStrings := []string{"int main(", "void main("}
	for _, ss := range searchStrings {
		if strings.Contains(stringContents, ss) {
			return true
		}
	}
	return false
}

// Fix implements the language.CppLanguage interface.
func (l *CppLanguage) Fix(*config.Config, *rule.File) {}

var _ language.Language = &CppLanguage{}
