// Copyright 2025-2026 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

package language

import (
	"testing"

	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/stretchr/testify/assert"

	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/common"
)

func TestMakeRulesFromFiles_UsesSuffixToSetAttributes(t *testing.T) {
	fileNames := []string{"alpha.h", "alpha.cpp", "beta.H", "beta.cc", "gamma.hh", "delta.cxx",
		"gamma.c", "delta.hpp", "epsilon.h", "zeta.cpp", "SkTypes.h", "SkUtils.cpp"}

	rules := makeRulesFromFiles(fileNames)

	assertRulesMatch(t, []*rule.Rule{
		library("alpha", "alpha.h", "alpha.cpp"),
		library("beta", "beta.H", "beta.cc"),
		library("gamma", "gamma.hh", "gamma.c"),
		library("delta", "delta.hpp", "delta.cxx"),
		library("epsilon", "epsilon.h", ""),
		library("zeta", "", "zeta.cpp"),
		library("SkTypes", "SkTypes.h", ""),
		library("SkUtils", "", "SkUtils.cpp"),
	}, rules)
}

func TestFindEmptyRules_Success(t *testing.T) {
	rulesInExistingBuildFile := []*rule.Rule{
		library("alpha", "alpha.h", "alpha.cpp"),
		library("SkTypes", "SkTypes.h", ""),
		library("SkUtils", "", "SkUtils.cpp"),
	}

	rulesFromSourceFiles := []*rule.Rule{
		library("Alpha", "Alpha.h", "Alpha.cpp"),
		library("SkTypes", "SkTypes.h", ""),
	}

	actualEmpty := findEmptyRules(rulesInExistingBuildFile, rulesFromSourceFiles)

	// The returned rules just have the kind and name set
	assertRulesMatch(t, []*rule.Rule{
		rule.NewRule(common.CCLibraryRule, "alpha"),
		rule.NewRule(common.CCLibraryRule, "SkUtils"),
	}, actualEmpty)
}

func TestReconcileGeneratedRules_ReportsExistingCrossLanguageCollision(t *testing.T) {
	t.Parallel()
	generatedRule := rule.NewRule(common.CCBinaryRule, "mtls_client")
	generatedRule.SetAttr("srcs", []string{"mtls_client.cc"})
	existingRule := rule.NewRule("go_binary", "mtls_client")
	existingRule.SetAttr("srcs", []string{"main.go"})

	err := (&CppLanguage{}).reconcileGeneratedRules(
		"services/mtls/cmd/mtls_client",
		[]*rule.Rule{existingRule},
		nil,
		[]*rule.Rule{generatedRule})

	assert.ErrorContains(
		t,
		err,
		"Gazelle would generate cc_binary //services/mtls/cmd/mtls_client:mtls_client from srcs [\"mtls_client.cc\"] and hdrs [], but an existing BUILD rule of kind go_binary already uses that name")
	assert.Equal(t, common.CCBinaryRule, generatedRule.Kind())
}

func TestReconcileGeneratedRules_PreservesSupportedCustomRuleKind(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		kind string
		srcs []string
	}{
		{kind: PyCCBindingRule},
		{kind: "cc_gpu_orin_test", srcs: []string{"custom_test.cc"}},
	} {
		generatedRule := rule.NewRule(common.CCTestRule, "custom_test")
		generatedRule.SetAttr("srcs", []string{"custom_test.cc"})
		existingRule := rule.NewRule(test.kind, "custom_test")
		existingRule.SetAttr("srcs", test.srcs)

		err := (&CppLanguage{}).reconcileGeneratedRules(
			"tests",
			[]*rule.Rule{existingRule},
			nil,
			[]*rule.Rule{generatedRule})

		assert.NoError(t, err)
		assert.Equal(t, test.kind, generatedRule.Kind())
	}
}

func TestReconcileGeneratedRules_ReportsOtherGeneratedRuleCollision(t *testing.T) {
	t.Parallel()
	generatedRule := rule.NewRule(common.CCBinaryRule, "tool")
	generatedRule.SetAttr("srcs", []string{"tool.cc"})
	otherGeneratedRule := rule.NewRule("go_binary", "tool")

	err := (&CppLanguage{}).reconcileGeneratedRules(
		"cmd/tool",
		nil,
		[]*rule.Rule{otherGeneratedRule},
		[]*rule.Rule{generatedRule})

	assert.ErrorContains(
		t,
		err,
		"Gazelle would generate cc_binary //cmd/tool:tool from srcs [\"tool.cc\"] and hdrs [], but a rule generated by another language of kind go_binary already uses that name")
	assert.Equal(t, common.CCBinaryRule, generatedRule.Kind())
}

func library(name, header string, source string) *rule.Rule {
	r := rule.NewRule(common.CCLibraryRule, name)
	if header != "" {
		r.SetAttr("hdrs", []string{header})
	}
	if source != "" {
		r.SetAttr("srcs", []string{source})
	}
	return r
}

type ruleAttrs struct {
	name string
	hdrs []string
	srcs []string
}

func assertRulesMatch(t *testing.T, expected, actual []*rule.Rule) {
	var eRules []ruleAttrs
	for _, r := range expected {
		eRules = append(eRules, ruleAttrs{
			name: r.Name(),
			hdrs: r.AttrStrings("hdrs"),
			srcs: r.AttrStrings("srcs"),
		})
	}
	var aRules []ruleAttrs
	for _, r := range actual {
		aRules = append(aRules, ruleAttrs{
			name: r.Name(),
			hdrs: r.AttrStrings("hdrs"),
			srcs: r.AttrStrings("srcs"),
		})
	}
	// This assertion is easier to debug when the two variables do not match.
	assert.ElementsMatch(t, eRules, aRules)
	assert.ElementsMatch(t, expected, actual)
}
