# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")

package(default_visibility = ["//visibility:public"])

exports_files([
    "network_var_packet.clk",
    "var_packet.clk",
])

clk(
    name = "network_var_packet_clk",
    srcs = ["network_var_packet.clk"],
    outs = [
        "network_var_packet_clk_cc.cc",
        "network_var_packet_clk_cc.hh",
        "network_var_packet_clk_cc.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

clk(
    name = "var_packet_clk",
    srcs = ["var_packet.clk"],
    outs = [
        "var_packet_clk_cc.cc",
        "var_packet_clk_cc.hh",
        "var_packet_clk_cc.inl",
        "var_packet_clk_nb.cc",
        "var_packet_clk_nb.hh",
        "var_packet_clk_nb.inl",
    ],
    generate = [
        "cpp",
        "nanobind",
    ],
    minimize_builtin_deps = True,
)
