# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_cc_binding")

package(default_visibility = ["//visibility:public"])

exports_files([
    "network_var_packet.clk",
    "var_packet.clk",
])

cc_library(
    name = "network_var_packet",
    srcs = [
        "network_var_packet.cc",
        "network_var_packet.inl",
    ],
    hdrs = ["network_var_packet.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "network_var_packet_clk",
    srcs = ["network_var_packet.clk"],
    outs = [
        "network_var_packet.cc",
        "network_var_packet.hh",
        "network_var_packet.inl",
    ],
)

cc_library(
    name = "var_packet",
    srcs = [
        "var_packet.cc",
        "var_packet.inl",
    ],
    hdrs = ["var_packet.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//jewels/container/tap:var_array",
        "//jewels/meta:concepts",
        "//jewels/uuid",
    ],
)

clk(
    name = "var_packet_clk",
    srcs = ["var_packet.clk"],
    outs = [
        "var_packet.cc",
        "var_packet.hh",
        "var_packet.inl",
        "var_packet_clk_nb.cc",
        "var_packet_clk_nb.hh",
        "var_packet_clk_nb.inl",
    ],
)

py_cc_binding(
    name = "var_packet_clk_nb",
    srcs = [
        "var_packet_clk_nb.cc",
        "var_packet_clk_nb.hh",
        "var_packet_clk_nb.inl",
    ],
    py_deps = ["//jewels/nanobind/clk_bindings/common:common_py"],
    deps = [
        ":var_packet",
        "//jewels/nanobind:nb_byte_array",
        "//jewels/nanobind/clk_bindings/common:common_cc",
    ],
)
