# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

cc_test(
    name = "aligned_consumer_combo_test",
    srcs = ["aligned_consumer_combo_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc_test",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "aligned_consumer_csr_test",
    srcs = ["aligned_consumer_csr_test.cc"],
    data = [
        "//clockwork/dsl/composition/tests/support:aligned_consumer_system.aligned_consumer_system.AlignedConsumerTestCpu_channel_publisher_config.tachyon",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_system.aligned_consumer_system.AlignedConsumerTestCpu_telemetry_logger_config.tachyon",
        "//clockwork/dsl/composition/tests/support:clockwork.clockwork.dsl.composition.tests.support.aligned_consumer_system.aligned_consumer_system.proc.tachyon",
    ],
    deps = [
        "//clockwork/cog:include_common",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_boxes_clk_exe_lib",  # keep
        "//clockwork/scaffolding:offline_scaffolding",  # keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//jewels/callsig:outparam",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "aligned_consumer_unit_test",
    srcs = ["aligned_consumer_unit_test.cc"],
    deps = [
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/dial:msg_input",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "aligned_noinput_consumer_combo_test",
    srcs = ["aligned_noinput_consumer_combo_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc_test",
        "//clockwork/dsl/composition/tests/support:aligned_noinput_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "cog_metrics_signal_metadata_test",
    srcs = [
        "cog_metrics_signal_metadata_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/composition/tests/support:cog_metrics_signals_test_system_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:gen_signal_metadata_configs",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:cog_metrics_report_groups",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "combined_aligned_consumer_unit_test",
    srcs = ["combined_aligned_consumer_unit_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/common:cog_execution_error_clk_cc",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/composition/tests/support:combined_aligned_consumer_cog_clk_cc",
        "//clockwork/dsl/composition/tests/support:combined_aligned_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "data_source_test",
    srcs = [
        "data_source_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:clk_hellocog_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:gen_logger_configs",
        "//clockwork/dsl/composition:genpd",
        "//clockwork/dsl/composition:pdf",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/serialization:tachyon_reg",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "empty_aligned_consumer_unit_test",
    srcs = ["empty_aligned_consumer_unit_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/common:cog_execution_error_clk_cc",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:empty_aligned_consumer_cog_clk_cc",
        "//clockwork/dsl/composition/tests/support:empty_aligned_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "gen_channel_spy_config_test",
    srcs = [
        "gen_channel_spy_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:channel_spy_config",
        "//clockwork/dsl/composition:channel_spy_config_proto",
        "//clockwork/dsl/composition:gen_channel_spy_configs",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "gen_logger_config_test",
    srcs = [
        "gen_logger_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:test_logging_policy_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:gen_logger_configs",
        "//clockwork/dsl/composition:logger_config",
        "//clockwork/dsl/composition:logger_config_proto",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "gen_metrics_channel_metadata_config_test",
    srcs = [
        "gen_metrics_channel_metadata_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:constants",
        "//clockwork/dsl/composition:gen_metrics_channel_metadata_configs",
        "//clockwork/dsl/composition:metrics_channel_metadata_config",
        "//clockwork/dsl/composition:metrics_channel_metadata_config_proto",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "gen_multi_subscriber_config_test",
    srcs = [
        "gen_multi_subscriber_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:test_logging_policy_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:gen_multi_subscriber_configs",
        "//clockwork/dsl/composition:multi_subscriber_config",
        "//clockwork/dsl/composition:multi_subscriber_config_proto",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "gen_signal_metadata_configs_test",
    srcs = [
        "gen_signal_metadata_configs_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/composition/tests/support:signals_test_system_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:gen_signal_metadata_configs",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "gen_simplelaunch_config_test",
    srcs = [
        "gen_simplelaunch_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:test_logging_policy_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:launchgen",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "genpd_test",
    srcs = [
        "genpd_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/common:platform_diagnostics_config_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:clk_hellomod_clk",
        "//clockwork/dsl/tests/support:hellomod_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:channel_config",
        "//clockwork/dsl/composition:genpd",
        "//clockwork/dsl/composition:pdf",
        "//clockwork/dsl/composition:pdfproto",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "graphir_test",
    srcs = [
        "graphir_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:hellomod_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:graphir",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:udp",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "log_producer_test",
    srcs = [
        "log_producer_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/composition/tests/support:logsimsys_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:simple_launch_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:system_target",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "logger_config_test",
    srcs = [
        "logger_config_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/composition:logger_config",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
    ],
)

cc_test(
    name = "multiple_aligned_consumer_unit_test",
    srcs = ["multiple_aligned_consumer_unit_test.cc"],
    deps = [
        "//clockwork/cog:detail",
        "//clockwork/cog:include_common",
        "//clockwork/cog/wrappers:unit_test_cog",
        "//clockwork/dial:include_common",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk_cc",
        "//clockwork/dsl/composition/tests/support:multiple_aligned_consumer_cog_clk_cc",
        "//clockwork/dsl/composition/tests/support:multiple_aligned_consumer_cog_clk_cc_test",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_slot_ref",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "pdf_test",
    srcs = [
        "pdf_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:pdf",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "realtime_playback_config_test",
    srcs = [
        "realtime_playback_config_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/tests/support:hellomsg.clk",
        "//clockwork/dsl/tests/support:testpolicy.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/composition:realtime_playback_config",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:uuid_reg",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "realtime_playback_generation_test",
    srcs = [
        "realtime_playback_generation_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/composition/tests/support:realtime_playback_system_target_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:genpd",
        "//clockwork/dsl/composition:pdfproto",
        "//clockwork/dsl/composition:realtime_playback_generation",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:system_target",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "signals_system_startup_test",
    srcs = ["signals_system_startup_test.cc"],
    data = ["//clockwork/dsl/composition/tests/support:signals_test_system_target_clk"],
    deps = [
        "//clockwork/dsl/composition/tests/support:signals_test_system_lib",  #keep
        "//clockwork/scaffolding:offline_scaffolding",  #keep
        "//clockwork/test_tools:clockwork_system_runner",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/utility:fix_clockwork_path",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "system_test",
    srcs = [
        "system_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/composition/tests/support:aligned_consumer_aligner_clk",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_boxes_clk",
        "//clockwork/dsl/composition/tests/support:aligned_consumer_system_clk",
        "//clockwork/dsl/composition/tests/support:signals_test_system_clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
        "//clockwork/dsl/tests/support:hellomod_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/dsl/ir:uuid_reg",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "systemgen_test",
    srcs = [
        "systemgen_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/composition/tests/support:memory_resource_test_system_clk",
        "//clockwork/dsl/composition/tests/support:signals_test_system.clk",
        "//clockwork/dsl/composition/tests/support:signals_test_system_target.clk",
        "//clockwork/dsl/composition/tests/support:simplesys_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/bazel:simple_launch_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/composition:journal_topology",
        "//clockwork/dsl/composition:journal_topology_file_config",
        "//clockwork/dsl/composition:system",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/journal:journal_topology_py_library",
        "//clockwork/serialization/py:protocol",
        "@clockwork_pip//protobuf",
        "@clockwork_pip//pytest",
    ],
)
