# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/approx_aligner:__subpackages__"],
)

clk(
    name = "test_boxes_clk",
    srcs = ["test_boxes.clk"],
    outs = [
        "test_boxes_clk_exe.cc",
        "test_boxes_clk_exe.hh",
        "test_boxes_clk_exe.inl",
    ],
    cpp_deps = [
        ":test_cogs_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_proto_conv",
        "//clockwork/examples/approx_aligner:approx_aligner_cog_clk_cc",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = ["cpp_exe"],
    proto_deps = ["//clockwork/dial:approx_aligner_config_clk_proto"],
    deps = [
        ":test_cogs_clk",
        "//clockwork/dial:approx_aligner_config_clk",
        "//clockwork/examples/approx_aligner:approx_aligner_cog_clk",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk",
    ],
)

cc_library(
    name = "test_boxes_clk_exe_lib",
    srcs = [
        "test_boxes_clk_exe.cc",
        "test_boxes_clk_exe.inl",
    ],
    hdrs = ["test_boxes_clk_exe.hh"],
    deps = [
        ":test_cogs_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork:tags",
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/dial:approx_aligner_config_clk_proto_cc_library",
        "//clockwork/dial:approx_aligner_config_clk_proto_conv",
        "//clockwork/examples/approx_aligner:approx_aligner_cog_clk_cc",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk_cc",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:casing",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/uuid",
    ],
)

clk(
    name = "test_cogs_clk",
    srcs = ["test_cogs.clk"],
    outs = [
        "test_cogs_clk_cc.cc",
        "test_cogs_clk_cc.hh",
        "test_cogs_clk_cc.inl",
        "test_cogs_clk_cc_dial.cc",
        "test_cogs_clk_cc_dial.hh",
        "test_cogs_clk_cc_dial.inl",
    ],
    cpp_deps = [
        "//clockwork/dial:approx_aligner_config_clk_cc",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk_cc",
    ],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [
        "//clockwork/dial:approx_aligner_config_clk",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk",
    ],
)

cc_library(
    name = "test_cogs_clk_cc_impl",
    srcs = ["test_cogs_clk_cc_impl.cc"],
    deps = [
        ":test_cogs_clk_cc_dial",
        "//clockwork/dial:msg_input",
        "//clockwork/examples/approx_aligner:approx_aligner_msgs_clk_cc",
        "//clockwork/pinion:publishable",
        "//jewels/container:circular_buffer",
        "@catch2//:catch2_main",
    ],
)

clk(
    name = "test_system_clk",
    srcs = ["test_system.clk"],
    outs = [
        "clockwork.clockwork.examples.approx_aligner.tests.support.test_system.test_system.proc.tachyon",
        "test_system.test_system.TestCpu_channel_allocations.csv",
        "test_system.test_system.TestCpu_channel_spy_config.tachyon",
        "test_system.test_system.TestCpu_event_logger_config.tachyon",
        "test_system.test_system.TestCpu_metrics_channel_metadata_config.tachyon",
        "test_system.test_system.TestCpu_signal_metadata_config.tachyon",
        "test_system.test_system.TestCpu_simplelaunch_config.textproto",
        "test_system.test_system.TestCpu_telemetry_logger_config.tachyon",
        "test_system.test_system.diagnostics_database_config.tachyon",
        "test_system.test_system.logged_channel_metadata.pbbin",
    ],
    deps = [":test_boxes_clk"],
)

merge_simplelaunch_config(
    name = "testcpu.textproto",
    srcs = [
        "test_system.test_system.TestCpu_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.examples.approx_aligner.tests.support.test_system.test_system.proc.tachyon",
        "test_system.test_system.TestCpu_channel_allocations.csv",
        "test_system.test_system.TestCpu_channel_spy_config.tachyon",
        "test_system.test_system.TestCpu_event_logger_config.tachyon",
        "test_system.test_system.TestCpu_metrics_channel_metadata_config.tachyon",
        "test_system.test_system.TestCpu_signal_metadata_config.tachyon",
        "test_system.test_system.TestCpu_telemetry_logger_config.tachyon",
        "test_system.test_system.diagnostics_database_config.tachyon",
        ":test_boxes_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)
