# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "async_write_request_test",
    srcs = ["async_write_request_test.cc"],
    deps = [
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//jewels/aligner",
        "//jewels/container:at",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "async_writer_test",
    srcs = ["async_writer_test.cc"],
    deps = [
        "//clockwork/logging:log_error",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer_state",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "buffered_memory_reader_test",
    srcs = ["buffered_memory_reader_test.cc"],
    deps = [
        "//clockwork/logging/onboard:buffered_memory_reader",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/container:at",
        "//jewels/memory:memory_resource",
        "//jewels/testing:tmp_directory_guard",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "buffered_reader_test",
    srcs = ["buffered_reader_test.cc"],
    deps = [
        "//clockwork/logging:log_error",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/aligner",
        "//jewels/container:at",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "clockwork_message_handle_test",
    srcs = ["clockwork_message_handle_test.cc"],
    deps = [
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:buffer_index",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/std:span",
        "@boost//:iterator",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "clockwork_reader_test",
    srcs = ["clockwork_reader_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:null_message_handle",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//jewels/aligner",
        "//jewels/filesystem",
        "//jewels/filesystem:path",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "clockwork_writer_test",
    srcs = ["clockwork_writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:null_message_handle",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard:writer_state",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//jewels/aligner",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "log_compressed_message_test",
    srcs = ["log_compressed_message_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/filesystem:path",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "log_format_test",
    srcs = ["log_format_test.cc"],
    deps = [
        "//clockwork/logging/onboard:log_format",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "memory_reader_test",
    srcs = ["memory_reader_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_memory_reader",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "memory_writer_test",
    srcs = ["memory_writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:memory_writer",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "persistent_clockwork_reader_test",
    srcs = ["persistent_clockwork_reader_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:null_message_handle",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//jewels/filesystem:path",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "persistent_clockwork_writer_test",
    srcs = ["persistent_clockwork_writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:clockwork_message_handle",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:null_message_handle",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:slot",
        "//clockwork/pinion/tests/support:mock_buffer",
        "//jewels/aligner",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "persistent_reader_test",
    srcs = ["persistent_reader_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/filesystem:path",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "persistent_writer_test",
    srcs = ["persistent_writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/aligner",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "reader_test",
    srcs = ["reader_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:buffered_reader",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:reader",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/aligner",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:path",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:filesystem_wrapper",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
        "@fmt",
        "@gsl//:util",
    ],
)

cc_test(
    name = "writer_test",
    srcs = ["writer_test.cc"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/onboard:async_write_request",
        "//clockwork/logging/onboard:async_writer",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard:writer_state",
        "//clockwork/logging/onboard/tests/support:test_message_handle",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/aligner",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/shared_pool:shared_object_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)
