# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

package(
    default_testonly = True,
    default_visibility = ["//clockwork/tests:__subpackages__"],
)

exports_files([
    "test_system_init_config.textproto",
    "test_system_init_config.tachyon",
    "test_system_config.textproto",
    "snapshot_test_config.textproto",
    "restore_test_state.textproto",
    "restore_test_config.textproto",
])
