# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

py_test(
    name = "common_test",
    srcs = [
        "common_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/serialization/metadata:tachyon_model",
        "//clockwork/serialization/py:common",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_nb",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_py",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_nb",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_py",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "compatibility_test",
    srcs = [
        "compatibility_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/serialization/metadata:tachyon_model",
        "//clockwork/serialization/py:compatibility",
        "//clockwork/serialization/py:protocol",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_py",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_nb",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_py",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "create_upgrader_test",
    srcs = [
        "create_upgrader_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/metadata:tachyon_model",
        "//clockwork/serialization/py:create_upgrader",
        "//clockwork/serialization/py/tests/support:broken_schema_v1_clk_py",
        "//clockwork/serialization/py/tests/support:broken_schema_v2_clk_py",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_py",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_py",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tachyon_dyn_from_metadata_test",
    srcs = [
        "tachyon_dyn_from_metadata_test.py",
        ":__test__",
    ],
    data = ["//clockwork/dsl/tests/support:tapmsg_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/py:tachyon_dyn",
        "//clockwork/serialization/py:tachyon_dyn_from_metadata",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tachyon_dyn_init_values_test",
    srcs = [
        "tachyon_dyn_init_values_test.py",
        ":__test__",
    ],
    data = ["//jewels/units/clk:au_clk"],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tachyon_dyn_test",
    srcs = [
        "tachyon_dyn_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/dsl/tests/support:hellomsg_clk",
        "//clockwork/dsl/tests/support:tapmsg_clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/serialization:tachyon_reg",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tachyon_dyn_upgrade_soa_test",
    srcs = [
        "tachyon_dyn_upgrade_soa_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:schema",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "tachyon_dyn_upgrade_test",
    srcs = [
        "tachyon_dyn_upgrade_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:schema",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//pytest",
    ],
)
