# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "fake_cog",
    hdrs = ["fake_cog.hh"],
    deps = [
        "//clockwork/common:abstract_cog",
        "//clockwork/common:forward",
        "//jewels/callsig:outparam",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "fake_epoll_mananger",
    hdrs = ["fake_epoll_mananger.hh"],
    deps = [
        "//clockwork/common:abstract_epoll_manager",
        "//jewels/filesystem:error_code",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "test_cog",
    srcs = ["test_cog.cc"],
    hdrs = ["test_cog.hh"],
    visibility = ["//clockwork:__subpackages__"],
    deps = [
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:cog_envelope",
        "//jewels/callsig:outparam",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
    ],
)
