# Copyright 2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

cc_test(
    name = "bundle_converter_test",
    srcs = ["bundle_converter_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging:xxh3_checksum",
        "//clockwork/logging/onboard:clockwork_writer_policy",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/readers:abstract_log_reader",
        "//clockwork/logging/readers:log_reader_factory",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/realtime_playback:bundle_converter",
        "//clockwork/logging/realtime_playback:camera_conversion",
        "//clockwork/logging/realtime_playback:converter_request",
        "//clockwork/logging/realtime_playback:converter_setup",
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_cc",
        "//clockwork/logging/realtime_playback:realtime_playback_stream_kind_clk_cc",
        "//clockwork/logging/realtime_playback/v1:realtime_playback_converter_manifest_cc_library",
        "//clockwork/logging/tests/support:test_message_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:file",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
        "@protobuf",
    ],
)

cc_test(
    name = "converter_request_test",
    srcs = ["converter_request_test.cc"],
    deps = [
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/realtime_playback:converter_request",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "converter_setup_test",
    srcs = ["converter_setup_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/realtime_playback:converter_setup",
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_cc",
        "//clockwork/logging/realtime_playback:realtime_playback_stream_kind_clk_cc",
        "//clockwork/logging/tests/support:test_message_clk_cc",
        "//clockwork/serialization/cpp:tachyon_upgrader",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/filesystem:file",
        "//jewels/filesystem:path",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "initialization_converter_test",
    srcs = ["initialization_converter_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging/onboard:clockwork_writer_policy",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/readers:abstract_log_reader",
        "//clockwork/logging/readers:log_reader_factory",
        "//clockwork/logging/readers:serialization",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/realtime_playback:converter_request",
        "//clockwork/logging/realtime_playback:converter_setup",
        "//clockwork/logging/realtime_playback:initialization_converter",
        "//clockwork/logging/realtime_playback:initialization_writer",  # keep: Implements convert_initialization_logs declared by initialization_converter.
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_cc",
        "//clockwork/logging/tests/support:test_message_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "initialization_selection_test",
    srcs = ["initialization_selection_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging/onboard:clockwork_writer_policy",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/readers:serialization",
        "//clockwork/logging/realtime_playback:initialization_converter",
        "//clockwork/logging/tests/support:test_message_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "realtime_playback_conversion_config_test",
    srcs = [
        "realtime_playback_conversion_config_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/logging:channel_publisher_config_clk_py",
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_py",
        "//clockwork/logging/realtime_playback:realtime_playback_stream_kind_clk_py",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "regular_converter_test",
    srcs = ["regular_converter_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:decompress_option",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging/onboard:clockwork_writer_policy",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/readers:abstract_log_reader",
        "//clockwork/logging/readers:log_reader_factory",
        "//clockwork/logging/readers:serialization",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/realtime_playback:converter_request",
        "//clockwork/logging/realtime_playback:converter_setup",
        "//clockwork/logging/realtime_playback:realtime_playback_conversion_config_clk_cc",
        "//clockwork/logging/realtime_playback:realtime_playback_stream_kind_clk_cc",
        "//clockwork/logging/realtime_playback:regular_converter",
        "//clockwork/logging/tests/support:test_message_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_cc",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/std:expected",
        "//jewels/testing:tmp_directory_guard",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

py_test(
    name = "xxh3_checksum_test",
    srcs = [
        "xxh3_checksum_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/logging/realtime_playback:nb_xxh3_checksum",
    ],
)
