# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@fltk//:rules.bzl", "generate_parser")
load("//tools/rules:package.bzl", "package")
load("//tools/rules:python.bzl", "py_binary", "py_library")

package(
    default_visibility = ["//clockwork:__subpackages__"],
)

py_binary(
    name = "clkc",
    srcs = ["clkc.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//clockwork/dsl/bazel:extract_targets",
        "//clockwork/dsl/composition:systemgen",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:cpp_executable",
        "//clockwork/dsl/ir:cpp_target",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:nanobind_target",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:proto_target",
        "//clockwork/dsl/ir:py_target",
        "//clockwork/dsl/ir:system_target",
        "@clockwork_pip//click",
    ],
)

py_library(
    name = "clockwork_cst",
    srcs = [":generate_parser"],
    deps = ["@fltk"],
)

py_library(
    name = "clockwork_parser",
    srcs = [":generate_parser"],
    deps = [
        ":clockwork_cst",
        "@fltk",
    ],
)

py_library(
    name = "compiler_context",
    srcs = ["compiler_context.py"],
    visibility = ["//visibility:public"],
    deps = ["@clockwork_pip//typing_extensions"],
)

generate_parser(
    name = "generate_parser",
    src = "clockwork.fltkg",
    base_name = "clockwork",
    cst_mod_path = "clockwork.dsl.clockwork_cst",
)
