# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

clk(
    name = "channel_message_rates_clk",
    srcs = ["channel_message_rates.clk"],
    outs = [
        "channel_message_rates_clk_cc.cc",
        "channel_message_rates_clk_cc.hh",
        "channel_message_rates_clk_cc.inl",
        "channel_message_rates_clk_cc_types.cc",
        "channel_message_rates_clk_cc_types.hh",
        "channel_message_rates_clk_cc_types.inl",
    ],
    cpp_deps = [":rate_status_clk_cc"],
    generate = ["cpp"],
    deps = [
        ":rate_status_clk",
        "//clockwork/common:constants_clk",
    ],
)

clk(
    name = "channel_message_rates_config_clk",
    srcs = ["channel_message_rates_config.clk"],
    outs = [
        "channel_message_rates_config_clk_cc.cc",
        "channel_message_rates_config_clk_cc.hh",
        "channel_message_rates_config_clk_cc.inl",
        "channel_message_rates_config_clk_cc_types.cc",
        "channel_message_rates_config_clk_cc_types.hh",
        "channel_message_rates_config_clk_cc_types.inl",
        "channel_message_rates_config_clk_proto.proto",
        "channel_message_rates_config_clk_proto_conv.cc",
        "channel_message_rates_config_clk_proto_conv.hh",
        "channel_message_rates_config_clk_proto_conv.inl",
    ],
    generate = [
        "cpp",
        "proto",
        "proto_conv",
    ],
    deps = ["//clockwork/common:constants_clk"],
)

cc_library(
    name = "deterministic_log_writer",
    srcs = ["deterministic_log_writer.cc"],
    hdrs = ["deterministic_log_writer.hh"],
    deps = [
        ":persistent_log_entry",
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging/offboard:chunk_writer",
        "//clockwork/logging/offboard:types",
        "//clockwork/logging/offboard:writer",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/runners:channel_publisher",
        "//clockwork/runners:deterministic_channel_handler",
        "//jewels/container:compare",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "//jewels/uuid:uuid_hasher",
    ],
)

cc_library(
    name = "log_writer_base",
    srcs = ["log_writer_base.inl"],
    hdrs = ["log_writer_base.hh"],
    deps = [
        ":channel_message_rates_clk_cc",
        ":channel_message_rates_config_clk_cc",
        ":log_writer_state_clk_cc",
        ":message_rate_counter",
        ":rate_status_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:compression_type",
        "//clockwork/logging:lite_compressor_interface",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging/onboard:clockwork_writer_policy",
        "//clockwork/logging/onboard:types",
        "//clockwork/logging/onboard:writer",
        "//clockwork/logging/onboard:writer_state",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:abstract_channel_factory",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:buffer_layout",
        "//clockwork/pinion:channel_config_clk_cc",
        "//clockwork/pinion:channel_observer",
        "//clockwork/pinion:channel_observer_client",
        "//clockwork/pinion:meta_channel_factory",
        "//clockwork/pinion:slot_ref",
        "//clockwork/runners:epoll_manager",
        "//clockwork/scaffolding:channels",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/log_cerr",
        "//jewels/math:constants",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@fmt",
    ],
)

clk(
    name = "log_writer_state_clk",
    srcs = ["log_writer_state.clk"],
    outs = [
        "log_writer_state_clk_cc.cc",
        "log_writer_state_clk_cc.hh",
        "log_writer_state_clk_cc.inl",
        "log_writer_state_clk_cc_types.cc",
        "log_writer_state_clk_cc_types.hh",
        "log_writer_state_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)

cc_library(
    name = "logger",
    srcs = ["logger.cc"],
    hdrs = ["logger.hh"],
    deps = [
        ":channel_message_rates_clk_cc",
        ":channel_message_rates_config_clk_cc",
        ":log_writer_state_clk_cc",
        ":logger_config_clk_cc",
        ":logger_status_clk_cc",
        ":message_writer",
        "//clockwork:repr_iface",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging/onboard:writer",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
        "@fmt",
    ],
)

clk(
    name = "logger_channel_policies_clk",
    srcs = ["logger_channel_policies.clk"],
    generate = ["none"],
    deps = [
        ":logger_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "logger_channels_clk",
    srcs = ["logger_channels.clk"],
    generate = ["none"],
    deps = [
        ":channel_message_rates_clk",
        ":logger_config_clk",
        ":logger_status_clk",
    ],
)

clk(
    name = "logger_clk",
    srcs = ["logger.clk"],
    outs = [
        "logger_clk_cc.cc",
        "logger_clk_cc.hh",
        "logger_clk_cc.inl",
        "logger_clk_cc_cog.cc",
        "logger_clk_cc_cog.hh",
        "logger_clk_cc_cog.inl",
        "logger_clk_cc_dial.cc",
        "logger_clk_cc_dial.hh",
        "logger_clk_cc_dial.inl",
        "logger_clk_cc_types.cc",
        "logger_clk_cc_types.hh",
        "logger_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":channel_message_rates_clk_cc",
        ":channel_message_rates_config_clk_cc",
        ":logger_cog_state",
        ":logger_config_clk_cc",
        ":logger_status_clk_cc",
        "//clockwork/logging:log_writer_config_clk_cc",
    ],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [
        ":channel_message_rates_clk",
        ":channel_message_rates_config_clk",
        ":logger_config_clk",
        ":logger_status_clk",
        "//clockwork/logging:log_writer_config_clk",
    ],
)

cc_library(
    name = "logger_clk_cc_impl",
    srcs = ["logger_clk_cc_impl.cc"],
    deps = [
        ":channel_message_rates_clk_cc",
        ":logger",
        ":logger_clk_cc_dial",
        ":logger_config_clk_cc",
        ":logger_status_clk_cc",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/uuid",
    ],
)

cc_library(
    name = "logger_cog_state",
    hdrs = ["logger_cog_state.hh"],
    deps = [
        ":logger",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
    ],
)

clk(
    name = "logger_config_clk",
    srcs = ["logger_config.clk"],
    outs = [
        "logger_config_clk_cc.cc",
        "logger_config_clk_cc.hh",
        "logger_config_clk_cc.inl",
        "logger_config_clk_cc_types.cc",
        "logger_config_clk_cc_types.hh",
        "logger_config_clk_cc_types.inl",
        "logger_config_clk_proto.proto",
        "logger_config_clk_proto_conv.cc",
        "logger_config_clk_proto_conv.hh",
        "logger_config_clk_proto_conv.inl",
    ],
    generate = [
        "cpp",
        "proto",
        "proto_conv",
    ],
)

clk(
    name = "logger_status_clk",
    srcs = ["logger_status.clk"],
    outs = [
        "logger_status_clk_cc.cc",
        "logger_status_clk_cc.hh",
        "logger_status_clk_cc.inl",
        "logger_status_clk_cc_types.cc",
        "logger_status_clk_cc_types.hh",
        "logger_status_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":log_writer_state_clk_cc",
        "//clockwork/logging:log_uuid_tag_clk_cc",
    ],
    generate = ["cpp"],
    deps = [
        ":log_writer_state_clk",
        "//clockwork/common:constants_clk",
        "//clockwork/logging:log_uuid_tag_clk",
    ],
)

cc_library(
    name = "message_rate_counter",
    srcs = ["message_rate_counter.cc"],
    hdrs = ["message_rate_counter.hh"],
    deps = [
        ":channel_message_rates_config_clk_cc",
        ":rate_filter",
        "//clockwork:repr_iface",
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "message_writer",
    srcs = ["message_writer.cc"],
    hdrs = ["message_writer.hh"],
    deps = [
        ":channel_message_rates_config_clk_cc",
        ":log_writer_base",
        ":log_writer_state_clk_cc",
        ":logger_config_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging/onboard:writer",
        "//clockwork/pinion:slot_ref",
        "//jewels/container:compare",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/shared_pool:ref_counted_pool",
        "//jewels/shared_pool:shared_buffer_pool",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "@fmt",
    ],
)

cc_library(
    name = "persistent_log_entry",
    hdrs = ["persistent_log_entry.hh"],
    deps = ["//clockwork/logging:schema_encoding_clk_cc"],
)

cc_library(
    name = "rate_filter",
    srcs = ["rate_filter.cc"],
    hdrs = ["rate_filter.hh"],
    deps = [
        "//jewels/memory:memory_resource",
        "//jewels/time:sync_time",
    ],
)

clk(
    name = "rate_status_clk",
    srcs = ["rate_status.clk"],
    outs = [
        "rate_status_clk_cc.cc",
        "rate_status_clk_cc.hh",
        "rate_status_clk_cc.inl",
        "rate_status_clk_cc_types.cc",
        "rate_status_clk_cc_types.hh",
        "rate_status_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)
