# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config", "simplelaunch_runner")
load("//tools/rules:cc.bzl", "cc_library")

simplelaunch_runner(
    name = "helloworld",
    config = ":democpu.textproto",
)

clk(
    name = "cogs_clk",
    srcs = ["cogs.clk"],
    outs = [
        "cogs_clk_cc.cc",
        "cogs_clk_cc.hh",
        "cogs_clk_cc.inl",
        "cogs_clk_cc_cog.cc",
        "cogs_clk_cc_cog.hh",
        "cogs_clk_cc_cog.inl",
        "cogs_clk_cc_dial.cc",
        "cogs_clk_cc_dial.hh",
        "cogs_clk_cc_dial.inl",
        "cogs_clk_cc_types.cc",
        "cogs_clk_cc_types.hh",
        "cogs_clk_cc_types.inl",
        "cogs_clk_exe.cc",
        "cogs_clk_exe.hh",
        "cogs_clk_exe.inl",
    ],
    cpp_deps = [
        ":helloworld_state_clk_cc",
        ":schema_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [
        ":helloworld_state_clk",
        ":schema_clk",
    ],
)

cc_library(
    name = "cogs_clk_cc_impl",
    srcs = ["cogs_clk_cc_impl.cc"],
    deps = [
        ":cogs_clk_cc_dial",
        ":helloworld_state_clk_cc",
        ":schema_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/log_cerr",
        "//jewels/uuid",
    ],
)

merge_simplelaunch_config(
    name = "democpu.textproto",
    srcs = [
        "system.producer_consumer.DemoCpu_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.examples.helloworld.system.producer_consumer.consumer_process.tachyon",
        "clockwork.clockwork.examples.helloworld.system.producer_consumer.producer_process.tachyon",
        "system.producer_consumer.DemoCpu_channel_allocations.csv",
        "system.producer_consumer.DemoCpu_channel_spy_config.tachyon",
        "system.producer_consumer.DemoCpu_event_logger_config.tachyon",
        "system.producer_consumer.DemoCpu_journal_topology.tachyon",
        "system.producer_consumer.DemoCpu_metrics_channel_metadata_config.tachyon",
        "system.producer_consumer.DemoCpu_signal_metadata_config.tachyon",
        "system.producer_consumer.DemoCpu_system_metadata.tachyon",
        "system.producer_consumer.DemoCpu_telemetry_logger_config.tachyon",
        "system.producer_consumer.diagnostics_database_config.tachyon",
        ":cogs_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)

clk(
    name = "helloworld_state_clk",
    srcs = ["helloworld_state.clk"],
    outs = [
        "helloworld_state_clk_cc.cc",
        "helloworld_state_clk_cc.hh",
        "helloworld_state_clk_cc.inl",
        "helloworld_state_clk_cc_types.cc",
        "helloworld_state_clk_cc_types.hh",
        "helloworld_state_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)

clk(
    name = "schema_clk",
    srcs = ["schema.clk"],
    outs = [
        "schema_clk_cc.cc",
        "schema_clk_cc.hh",
        "schema_clk_cc.inl",
        "schema_clk_cc_types.cc",
        "schema_clk_cc_types.hh",
        "schema_clk_cc_types.inl",
    ],
    generate = ["cpp"],
)

clk(
    name = "system_clk",
    srcs = ["system.clk"],
    outs = [
        "clockwork.clockwork.examples.helloworld.system.producer_consumer.consumer_process.tachyon",
        "clockwork.clockwork.examples.helloworld.system.producer_consumer.producer_process.tachyon",
        "system.producer_consumer.DemoCpu_channel_allocations.csv",
        "system.producer_consumer.DemoCpu_channel_spy_config.tachyon",
        "system.producer_consumer.DemoCpu_event_logger_config.tachyon",
        "system.producer_consumer.DemoCpu_journal_topology.tachyon",
        "system.producer_consumer.DemoCpu_metrics_channel_metadata_config.tachyon",
        "system.producer_consumer.DemoCpu_signal_metadata_config.tachyon",
        "system.producer_consumer.DemoCpu_simplelaunch_config.textproto",
        "system.producer_consumer.DemoCpu_system_metadata.tachyon",
        "system.producer_consumer.DemoCpu_telemetry_logger_config.tachyon",
        "system.producer_consumer.diagnostics_database_config.tachyon",
        "system.producer_consumer.logged_channel_metadata.pbbin",
    ],
    deps = [":cogs_clk"],
)
