# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@aspect_rules_py//py:defs.bzl", "py_pytest_main")
load("//tools/rules:cc.bzl", "cc_test")
load("//tools/rules:python.bzl", "py_test")

package(default_testonly = True)

py_pytest_main(
    name = "__test__",
    deps = ["@clockwork_pip//pytest"],
)

cc_test(
    name = "clk_au_test",
    srcs = ["clk_au_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/dsl/tests/support:msg_with_au",
        "@au",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "compiler_context_test",
    srcs = [
        "compiler_context_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "@clockwork_pip//typing_extensions",
    ],
)

py_test(
    name = "compiler_context_text",
    srcs = [
        "compiler_context_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "formatter_test",
    srcs = [
        "formatter_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:fmt_lib",
    ],
)

cc_test(
    name = "hello_udp_not_var_packet_test",
    srcs = ["hello_udp_not_var_packet_test.cc"],
    deps = [
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/dsl/tests/support:hello_udp_not_var_packet",
        "//clockwork/pinion:incoming_udp",
        "//clockwork/pinion:outgoing_udp",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "hello_udp_test",
    srcs = ["hello_udp_test.cc"],
    deps = [
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/dsl/tests/support:hello_udp",
        "//clockwork/io:var_packet_clk_cc",
        "//clockwork/pinion:bidirectional_udp",
        "//clockwork/pinion:incoming_udp",
        "//clockwork/pinion:outgoing_udp",
        "//jewels/filesystem:error_code",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/networking:sock_opt",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "hellocog_test",
    srcs = ["hellocog_test.cc"],
    deps = [
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/dsl/tests/support:hellocog",
        "//clockwork/dsl/tests/support:hellocog_impl",  #keep
        "//clockwork/runners:online_cog_queue",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/uuid",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "hellomsg_test",
    srcs = ["hellomsg_test.cc"],
    deps = [
        "//clockwork/dsl/tests/support:hello_msg_onboard",
        "@catch2//:catch2_main",
    ],
)

py_test(
    name = "nanobinding_function_calls_test",
    srcs = [
        "nanobinding_function_calls_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/tests/support:nanobindable_messages_clk_nb",
        "//clockwork/dsl/tests/support:nb_function_calls",
    ],
)

py_test(
    name = "nanobinding_message_test",
    srcs = [
        "nanobinding_message_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/tests/support:nanobindable_messages_clk_nb",
        "//jewels/nanobind:nb_sync_time",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "signal_registry_test",
    srcs = [
        "signal_registry_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//std:signals.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:signal_registry",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "signal_subscript_policy_test",
    srcs = [
        "signal_subscript_policy_test.py",
        ":__test__",
    ],
    data = [
        "//clockwork/diagnostics:report.clk",
        "//clockwork/dsl/cog:common_cog_event_metrics.clk",
        "//clockwork/dsl/cog:common_cog_telemetry_metrics.clk",
        "//clockwork/dsl/cog:ten_nanosecond.clk",
        "//clockwork/dsl/tests/support:test_signals.clk",
        "//std:signals.clk",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:signal_registry",
        "@clockwork_pip//pytest",
    ],
)

py_test(
    name = "signal_test",
    srcs = [
        "signal_test.py",
        ":__test__",
    ],
    main = ":__test__.py",
    deps = [
        ":__test__",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:expr",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:signal",
        "@clockwork_pip//pytest",
    ],
)

cc_test(
    name = "tapmsg_test",
    srcs = ["tapmsg_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/dsl/tests/support:tapmsg",
        "//jewels/container/tap:optional",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "taptags_test",
    srcs = ["taptags_test.cc"],
    deps = [
        "//clockwork/dsl/tests/support:taptags_clk_cc",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "tensor_test",
    srcs = ["tensor_test.cc"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/dsl/tests/support:tensor_msg_clk_cc",
        "//jewels/container/tap:tensor",
        "@catch2//:catch2_main",
    ],
)
