# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_library")

cc_library(
    name = "bitset",
    srcs = ["bitset.inl"],
    hdrs = ["bitset.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
    ],
)

cc_library(
    name = "constants",
    hdrs = ["constants.hh"],
    visibility = ["//jewels/container/tap/tests:__pkg__"],
)

cc_library(
    name = "optional",
    srcs = ["optional.inl"],
    hdrs = ["optional.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":constants",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/memory:aligned_storage",
        "//jewels/meta:concepts",
        "//jewels/std:span",
    ],
)

cc_library(
    name = "protobuf_to_tap",
    srcs = [
        "protobuf_to_tap.cc",
        "protobuf_to_tap.inl",
    ],
    hdrs = ["protobuf_to_tap.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":optional",
        ":var_array",
        ":var_string",
        "//jewels/container:at",
        "//jewels/log_cerr",
        "//jewels/meta:concepts",
        "//jewels/std:expected",
        "//jewels/time:conversions",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@protobuf",
    ],
)

py_library(
    name = "py_var_array",
    srcs = ["py_var_array.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":value_serdes",
        "//jewels/memory:py_bytes",
        "@clockwork_pip//typing_extensions",
    ],
)

cc_library(
    name = "soa",
    srcs = ["soa.inl"],
    hdrs = ["soa.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "@boost.iterator",
    ],
)

cc_library(
    name = "tap_to_protobuf",
    srcs = [
        "tap_to_protobuf.cc",
        "tap_to_protobuf.inl",
    ],
    hdrs = ["tap_to_protobuf.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":var_array",
        ":var_string",
        "//jewels/time:conversions",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@protobuf",
    ],
)

cc_library(
    name = "tensor",
    srcs = ["tensor.inl"],
    hdrs = ["tensor.hh"],
    visibility = ["//visibility:public"],
    deps = ["//jewels/meta:integer_sequence"],
)

py_library(
    name = "value_serdes",
    srcs = ["value_serdes.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/memory:py_bytes",
        "@clockwork_pip//typing_extensions",
    ],
)

cc_library(
    name = "var_array",
    srcs = ["var_array.inl"],
    hdrs = ["var_array.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":constants",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/memory:aligned_storage",
        "//jewels/meta:concepts",
        "//jewels/std:expected",
        "@fmt",
    ],
)

cc_library(
    name = "var_string",
    srcs = ["var_string.inl"],
    hdrs = ["var_string.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":var_array",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
    ],
)
