// Copyright 2025-2026 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

#include "jewels/filesystem/path.hh"
#include "jewels/testing/tmp_directory_guard.hh"

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h> // IWYU pragma: keep

#include <new>
#include <string>

// NOLINTNEXTLINE(readability-function-cognitive-complexity) code is generated by a macro
NB_MODULE(nb_tmp_directory_guard, mod)
{
  namespace nb = ::nanobind;
  nb::set_leak_warnings(false);

  mod.doc() = "Test temporary directory guard nanobind wrapper";

  nb::class_<jewels::testing::TmpDirectoryGuard>(mod, "TmpDirectoryGuard")
    .def(
      "__init__",
      [](jewels::testing::TmpDirectoryGuard* ptr) { new (ptr) jewels::testing::TmpDirectoryGuard{}; },
      "Create a test directory that is deleted automatically.")
    .def_prop_ro(
      "path",
      [](jewels::testing::TmpDirectoryGuard& obj) -> std::string { return std::string{obj.get_path().c_str()}; },
      "Get the temp directory path string.");
}
