# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "test_log_reader",
    srcs = ["test_log_reader.cc"],
    hdrs = ["test_log_reader.hh"],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/logging:channel_type",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_interval",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/readers:abstract_log_reader",
        "//clockwork/logging/readers:types",
        "//clockwork/logging/tests/support:test_message",
        "//jewels/std:expected",
        "@catch2//:catch2_main",
    ],
)

cc_library(
    name = "test_offboard_log_writer",
    srcs = ["test_offboard_log_writer.cc"],
    hdrs = ["test_offboard_log_writer.hh"],
    deps = [
        "//clockwork/logging:channel_type",
        "//clockwork/logging:lite_compressor",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:message_encoding",
        "//clockwork/logging:schema_encoding",
        "//clockwork/logging/offboard:types",
        "//clockwork/logging/offboard:writer",
        "//clockwork/logging/offboard/tests/support:test_support",
        "//clockwork/logging/onboard/tests/support:test_support",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
    ],
)
