# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")

clk(
    name = "au_clk",
    srcs = ["au.clk"],
    outs = [
        "au_clk_cc.cc",
        "au_clk_cc.hh",
        "au_clk_cc.inl",
    ],
    cpp_deps = [
        "//jewels/units:degrees",
        "//jewels/units:density",
        "//jewels/units:earth",
        "//jewels/units:feet",
        "//jewels/units:hertz",
        "//jewels/units:kilograms",
        "//jewels/units:kinematics",
        "//jewels/units:meters",
        "//jewels/units:newtons",
        "//jewels/units:pounds_mass",
        "//jewels/units:radians",
        "//jewels/units:seconds",
    ],
    generate = ["cpp"],
    visibility = ["//visibility:public"],
)
