// Copyright 2025 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

package language

import (
	"log"
	"os"
	"path/filepath"
	"slices"
	"sort"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/rule"

	"github.com/emirpasic/gods/sets/treeset"
	godsutils "github.com/emirpasic/gods/utils"

	"github.com/stackav-oss/clockwork/tools/gazelle/clk_plugin/common"
	"github.com/stackav-oss/clockwork/tools/gazelle/clk_plugin/configurer"
	"github.com/stackav-oss/clockwork/tools/gazelle/clk_plugin/parsers"
	"github.com/stackav-oss/clockwork/tools/gazelle/clk_plugin/resolver"
)

// ClkLanguage implements the language.ClkLanguage interface.
type ClkLanguage struct {
	configurer.ClkConfigurer
	resolver.ClkResolver
}

// Kinds implements the language.Language interface.
//
// Interface documentation:
//
// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (l *ClkLanguage) Kinds() map[string]rule.KindInfo {
	kindInfo := rule.KindInfo{
		// This extension generates content for the fields specified here.
		ResolveAttrs: map[string]bool{
			"generate":       true,
			"outs":           true,
			"deps":           true,
			"cpp_deps":       true,
			"cpp_exe_deps":   true,
			"go_import_path": true,
			"proto_deps":     true,
			"py_deps":        true,
			"srcs":           true,
		},
		// NonEmptyAttrs must be non-nil, otherwise no rules will get deleted.
		// We don't have any fields that should prevent a rule from being deleted if the
		// underlying source file or header file is missing, so an empty map suffices.
		NonEmptyAttrs: map[string]bool{},
	}
	return map[string]rule.KindInfo{
		common.ClkRule: kindInfo,
	}
}

// Loads implements the language.ClkLanguage interface.
//
// Interface documentation:
//
// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (l *ClkLanguage) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name: common.GetClockworkLabelString("//clockwork:rules.bzl", l.InClockworkRepo),
			Symbols: []string{
				common.ClkRule,
			},
		},
	}
}

// GenerateRules implements the language.ClkLanguage interface.
//
// GenerateRules generates build rules for source files in a directory. GenerateRules is called in
// each directory where an update is requested in depth-first order.
//
// This method does not populate the deps argument of any generate rules. Dependencies are resolved
// in ClkResolver.Resolve(), which happens after GenerateRules is called in each directory where an
// update is requested.
func (l *ClkLanguage) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	allFiles := append(args.RegularFiles)
	// allClkRules is the rules for every .clk file in the directory
	allClkRules := makeRulesFromFiles(allFiles)
	// clkRules is the rules for the .clk files in the directory that have a generate attribute
	clkRules, imports := getImportsFromRules(allClkRules, args.Dir, l.InClockworkRepo)

	var existingRules []*rule.Rule
	if args.File != nil {
		existingRules = args.File.Rules
	}

	return language.GenerateResult{
		Gen:     clkRules,
		Imports: imports,
		Empty:   findEmptyRules(existingRules, allClkRules),
	}
}

// findEmptyRules returns any relevant rules which were in the rules from BUILD.bazel,
// but did not show up when we recreated all the rules from the source files. This means the
// underlying source files have been deleted or moved and the rules should as well.
func findEmptyRules(prevRules []*rule.Rule, newRules []*rule.Rule) []*rule.Rule {
	ruleCache := map[string]bool{}
	for _, r := range newRules {
		ruleCache[r.Name()] = true
	}
	allOuts := []string{}
	for _, r := range prevRules {
		if outs := r.AttrStrings("outs"); outs != nil {
			allOuts = append(allOuts, outs...)
		}
	}

	var empty []*rule.Rule
	for _, r := range prevRules {
		if r.Kind() != common.ClkRule {
			continue
		}
		if generate := r.AttrStrings("generate"); len(generate) == 0 {
			// Existing rules without a generate attribute are handled by clk-deps
			continue
		}
		if _, ok := ruleCache[r.Name()]; !ok {
			// This is checking to see if the source file that would have generated this rule
			// is listed as an output of another rule in the directory. If so we don't want to
			// delete the rule just because the file doesn't exist.
			shouldKeepRule := false
			if srcs := r.AttrStrings("srcs"); srcs != nil {
				for _, src := range srcs {
					if slices.Contains(allOuts, src) {
						shouldKeepRule = true
					}
				}
			}
			if !shouldKeepRule {
				empty = append(empty, rule.NewRule(r.Kind(), r.Name()))
			}
		}
	}
	return empty
}

type ruleData struct {
	name string
	kind string
	srcs *treeset.Set
	hdrs *treeset.Set
}

// makeRulesFromFiles returns a single rule per filename
func makeRulesFromFiles(names []string) []*rule.Rule {
	var rules = make(map[string]*ruleData)

	for _, name := range names {
		if !common.IsClkSource(name) {
			continue
		}
		ruleName := common.GetClkRuleName(name)
		rData, ok := rules[ruleName]
		if !ok {
			data := ruleData{ruleName, common.ClkRule, treeset.NewWith(godsutils.StringComparator), treeset.NewWith(godsutils.StringComparator)}
			rData = &data
			rules[ruleName] = rData
		}
		rData.srcs.Add(name)
	}

	// Transfer that into a Gazelle rule struct, which internally stores attrs in
	// a way that they can't really be added to (which is why we collect beforehand).
	var rulesResult []*rule.Rule
	for name, ruleData := range rules {
		newRule := rule.NewRule(ruleData.kind, name)
		if !ruleData.srcs.Empty() {
			// convert srcs.Values from interfaces to strings
			var srcStrings []string
			for _, src := range ruleData.srcs.Values() {
				srcStrings = append(srcStrings, src.(string))
			}
			newRule.SetAttr("srcs", srcStrings)
		}
		rulesResult = append(rulesResult, newRule)
	}
	// Sort for determinism
	sort.Slice(rulesResult, func(i, j int) bool {
		return rulesResult[i].Name() < rulesResult[j].Name()
	})
	return rulesResult
}

// getImportsFromRules returns a list of the rules for clockwork files that contain a generate attribute,
// and a list of the import results containing the dependencies for each rule.
func getImportsFromRules(rules []*rule.Rule, dir string, inClockworkRepo bool) ([]*rule.Rule, []interface{}) {
	var importsResult []interface{}
	clkRulesResult := []*rule.Rule{}
	for _, r := range rules {
		srcs := r.AttrStrings("srcs")
		for _, src := range srcs {
			imports := extractImportsFromClkFile(filepath.Join(dir, src), inClockworkRepo)
			if imports.GetClkGenerate() {
				common.SetGenerateAttr(r, imports.GetClkGenerates())
				clkRulesResult = append(clkRulesResult, r)
				importsResult = append(importsResult, imports)
			}
		}
	}
	return clkRulesResult, importsResult
}

// extractImportsFromClkFile opens ups the given file and parses the contents.
func extractImportsFromClkFile(path string, inClockworkRepo bool) common.ImportsParsedFromRuleSources {
	fileBytes, err := os.ReadFile(path)
	if err != nil {
		log.Panicf("Error reading file %q: %v", path, err)
	}
	return parsers.ParseClkFile(string(fileBytes[:]), inClockworkRepo)
}

// Fix implements the language.Language interface.
func (l *ClkLanguage) Fix(*config.Config, *rule.File) {}

var _ language.Language = &ClkLanguage{}
