# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "md5_test",
    srcs = ["md5_test.cc"],
    deps = [
        "//jewels/hash:md5",
        "@catch2//:catch2_main",
        "@openssl//:ssl",
    ],
)

cc_test(
    name = "sha1_test",
    srcs = ["sha1_test.cc"],
    deps = [
        "//jewels/hash:sha1",
        "@catch2//:catch2_main",
        "@fmt",
    ],
)
