# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "test_log_writer_config",
    srcs = ["test_log_writer_config.cc"],
    hdrs = ["test_log_writer_config.hh"],
    data = [
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk",
    ],
    deps = [
        "//clockwork:repr_iface",
        "//clockwork/common:process_description_clk_cc",
        "//clockwork/logging:channel_publisher_config_clk_cc",
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_uuid",
        "//clockwork/logging:log_writer_config_clk_cc",
        "//clockwork/logging:message_encoding_clk_cc",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging/writers:channel_message_rates_config_clk_cc",
        "//clockwork/logging/writers:logger_config_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v1_clk_cc",
        "//clockwork/serialization/py/tests/support:simple_schema_v2_clk_cc",
        "//clockwork/tools/metrics_channel_metadata:metrics_channel_metadata_config_clk_cc",
        "//jewels/container:compare",
        "//jewels/container/tap:var_array",
        "//jewels/container/tap:var_string",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@gsl//:util",
    ],
)

cc_library(
    name = "test_publisher",
    srcs = ["test_publisher.cc"],
    hdrs = ["test_publisher.hh"],
    deps = [
        "//clockwork/logging:log_timestamp",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:error",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_publisher",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
    ],
)
