# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:python.bzl", "py_library")

package(default_visibility = ["//clockwork:__subpackages__"])

py_library(
    name = "bridgegen",
    srcs = ["bridgegen.py"],
    deps = [
        ":graphir",
        ":pdf",
        ":platform_diagnostics_config",
        ":str_manip",
        ":system",
        ":tcp_bridge_config",
        ":tcp_bridge_config_proto",
        "//clockwork/dsl/ir:uuid_reg",
    ],
)

py_library(
    name = "channel_spy_config",
    srcs = ["channel_spy_config.py"],
    data = [
        "//clockwork/common:constants.clk",
        "//clockwork/common:process_description.clk",
        "//clockwork/tools/channel_spy:channel_spy_config.clk",
    ],
    deps = [
        ":channel_spy_config_proto",
        ":constants",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "channel_spy_config_proto",
    srcs = ["channel_spy_config_proto.py"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "constants",
    srcs = ["constants.py"],
)

py_library(
    name = "diagnostics_config",
    srcs = ["diagnostics_config.py"],
    deps = [
        ":diagnostics_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "diagnostics_config_proto",
    srcs = ["diagnostics_config_proto.py"],
    data = [
        "//clockwork/diagnostics:database_config.clk",
        "//clockwork/diagnostics:report.clk",
    ],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "gen_channel_allocation_report",
    srcs = ["gen_channel_allocation_report.py"],
    visibility = ["//:__subpackages__"],
    deps = [":system"],
)

py_library(
    name = "gen_channel_spy_configs",
    srcs = ["gen_channel_spy_configs.py"],
    deps = [
        ":channel_spy_config",
        ":channel_spy_config_proto",
        ":system",
        "//clockwork/dsl:compiler_context",
        "//clockwork/serialization/metadata:tachyon",
    ],
)

py_library(
    name = "gen_diagnostics_configs",
    srcs = ["gen_diagnostics_configs.py"],
    deps = [
        ":diagnostics_config",
        ":diagnostics_config_proto",
        ":system",
        "//clockwork/dsl/ir:diagnostics",
        "//clockwork/dsl/ir:uuid_reg",
    ],
)

py_library(
    name = "gen_logger_configs",
    srcs = ["gen_logger_configs.py"],
    deps = [
        ":logger_config",
        ":logger_config_proto",
        ":publisher_config",
        ":publisher_config_proto",
        ":system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/serialization:tachyon_reg",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/metadata:tachyon_model_py_library",
    ],
)

py_library(
    name = "gen_metrics_channel_metadata_configs",
    srcs = ["gen_metrics_channel_metadata_configs.py"],
    deps = [
        ":metrics_channel_metadata_config",
        ":metrics_channel_metadata_config_proto",
        ":system",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/serialization/metadata:tachyon",
    ],
)

py_library(
    name = "gen_multi_subscriber_configs",
    srcs = ["gen_multi_subscriber_configs.py"],
    deps = [
        ":multi_subscriber_config",
        ":multi_subscriber_config_proto",
        ":pdf",
        ":system",
    ],
)

py_library(
    name = "gen_signal_metadata_configs",
    srcs = ["gen_signal_metadata_configs.py"],
    deps = [
        ":signal_metadata_config",
        ":signal_metadata_config_proto",
        ":system",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:report_group",
        "//clockwork/dsl/ir:signal",
        "//clockwork/dsl/ir:signal_registry",
        "//clockwork/dsl/ir:uuid_reg",
    ],
)

py_library(
    name = "genpd",
    srcs = ["genpd.py"],
    deps = [
        ":pdf",
        ":pdfproto",
        ":system",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:cog_components",
        "//clockwork/dsl/ir:diagnostics",
        "//clockwork/dsl/ir:extern_type",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "//clockwork/dsl/ir:uuid_reg",
        "//clockwork/dsl/serialization:tachyon_layout_reg",
    ],
)

py_library(
    name = "graphir",
    srcs = ["graphir.py"],
    deps = [
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:audio",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:diagnostics",
        "//clockwork/dsl/ir:extern_type",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "//clockwork/dsl/serialization:tachyon_reg",
        "@clockwork_pip//typing_extensions",
    ],
)

py_library(
    name = "launchgen",
    srcs = ["launchgen.py"],
    deps = [
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:path_resolver",
        "//jewels/simplelaunch/v1:config_py_library",
        "@clockwork_pip//protobuf",
    ],
)

py_library(
    name = "logger_config",
    srcs = ["logger_config.py"],
    data = [
        "//clockwork/common:constants.clk",
        "//clockwork/logging:channel_policy.clk",
        "//clockwork/logging:channel_type.clk",
        "//clockwork/logging:log_uuid_tag.clk",
        "//clockwork/logging:log_writer_config.clk",
        "//clockwork/logging:message_encoding.clk",
        "//clockwork/logging:schema_encoding.clk",
    ],
    deps = [
        ":constants",
        ":logger_config_proto",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//typing_extensions",
    ],
)

py_library(
    name = "logger_config_proto",
    srcs = ["logger_config_proto.py"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "metrics_channel_metadata_config",
    srcs = ["metrics_channel_metadata_config.py"],
    data = [
        "//clockwork/common:constants.clk",
        "//clockwork/common:process_description.clk",
        "//clockwork/tools/metrics_channel_metadata:metrics_channel_metadata_config.clk",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":constants",
        ":metrics_channel_metadata_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "metrics_channel_metadata_config_proto",
    srcs = ["metrics_channel_metadata_config_proto.py"],
    visibility = ["//visibility:public"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "multi_subscriber_config",
    srcs = ["multi_subscriber_config.py"],
    data = ["//clockwork/common:multi_subscriber_config.clk"],
    deps = [
        ":multi_subscriber_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "multi_subscriber_config_proto",
    srcs = ["multi_subscriber_config_proto.py"],
    deps = [
        ":pdfproto",
        "//clockwork/serialization/py:protocol",
    ],
)

py_library(
    name = "pdf",
    srcs = ["pdf.py"],
    data = ["//clockwork/common:process_description.clk"],
    deps = [
        ":pdfproto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "pdfproto",
    srcs = ["pdfproto.py"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "platform_diagnostics_config",
    srcs = ["platform_diagnostics_config.py"],
    data = ["//clockwork/common:platform_diagnostics_config.clk"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":platform_diagnostics_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "platform_diagnostics_config_proto",
    srcs = ["platform_diagnostics_config_proto.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":pdfproto",
        "//clockwork/serialization/py:protocol",
    ],
)

py_library(
    name = "publisher_config",
    srcs = ["publisher_config.py"],
    data = [
        "//clockwork/common:constants.clk",
        "//clockwork/logging:channel_publisher_config.clk",
    ],
    deps = [
        ":constants",
        ":publisher_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "publisher_config_proto",
    srcs = ["publisher_config_proto.py"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "signal_metadata_config",
    srcs = ["signal_metadata_config.py"],
    data = [
        "//clockwork/common:constants.clk",
        "//clockwork/common:process_description.clk",
        "//clockwork/common:signal_metadata_config.clk",
        "//clockwork/logging:channel_policy.clk",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":constants",
        ":signal_metadata_config_proto",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
        "@clockwork_pip//typing_extensions",
    ],
)

py_library(
    name = "signal_metadata_config_proto",
    srcs = ["signal_metadata_config_proto.py"],
    visibility = ["//visibility:public"],
    deps = ["//clockwork/serialization/py:protocol"],
)

py_library(
    name = "snapshot_config",
    srcs = ["snapshot_config.py"],
    data = ["@clockwork//std:snapshot.clk"],
    deps = [
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer_registry",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "@clockwork_pip//typing_extensions",
    ],
)

py_library(
    name = "str_manip",
    srcs = ["str_manip.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "system",
    srcs = ["system.py"],
    deps = [
        ":graphir",
        ":logger_config",
        ":logger_config_proto",
        ":snapshot_config",
        ":str_manip",
        "//clockwork/dsl:compiler_context",
        "//clockwork/dsl/ir:audio",
        "//clockwork/dsl/ir:box",
        "//clockwork/dsl/ir:clkbuiltins",
        "//clockwork/dsl/ir:clkenum",
        "//clockwork/dsl/ir:cog",
        "//clockwork/dsl/ir:diagnostics",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:node",
        "//clockwork/dsl/ir:policy",
        "//clockwork/dsl/ir:primitive",
        "//clockwork/dsl/ir:pubsub",
        "//clockwork/dsl/ir:report_group",
        "//clockwork/dsl/ir:representation",
        "//clockwork/dsl/ir:schema_reg",
        "//clockwork/dsl/ir:typesys",
        "//clockwork/dsl/ir:udp",
        "//clockwork/dsl/ir:units",
        "//clockwork/dsl/ir:uuid_reg",
    ],
)

py_library(
    name = "systemgen",
    srcs = ["systemgen.py"],
    deps = [
        ":bridgegen",
        ":diagnostics_config",
        ":gen_channel_allocation_report",
        ":gen_channel_spy_configs",
        ":gen_diagnostics_configs",
        ":gen_logger_configs",
        ":gen_metrics_channel_metadata_configs",
        ":gen_multi_subscriber_configs",
        ":gen_signal_metadata_configs",
        ":genpd",
        ":launchgen",
        ":logger_config",
        ":pdf",
        ":signal_metadata_config",
        ":system",
        "//clockwork/dsl/bazel:simple_launch_targets",
        "//clockwork/dsl/bazel:targets",
        "//clockwork/dsl/ir:hardware",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/dsl/ir:path_resolver",
        "//clockwork/dsl/ir:system_target",
        "//clockwork/serialization/py:protocol",
        "//jewels/simplelaunch/v1:config_py_library",
        "@clockwork_pip//typing_extensions",
    ],
)

py_library(
    name = "tcp_bridge_config",
    srcs = ["tcp_bridge_config.py"],
    data = [
        "//clockwork/common:process_description.clk",
        "//clockwork/pinion:tcp_bridge_config.clk",
    ],
    deps = [
        ":tcp_bridge_config_proto",
        "//clockwork/dsl/ir:compiler",
        "//clockwork/dsl/ir:importer",
        "//clockwork/dsl/ir:module_id",
        "//clockwork/serialization/py:tachyon_dyn",
    ],
)

py_library(
    name = "tcp_bridge_config_proto",
    srcs = ["tcp_bridge_config_proto.py"],
    deps = [
        ":pdfproto",
        ":platform_diagnostics_config_proto",
        "//clockwork/serialization/py:protocol",
    ],
)
