// Copyright 2025 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

package resolver

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"

	"go.skia.org/infra/go/util"

	"github.com/stackav-oss/clockwork/tools/gazelle/cc_plugin/common"
)

const (
	// gazelleExtensionName is the extension name passed to Gazelle.
	//
	// This name can be used to enable or disable this Gazelle extension via the --lang flag, e.g.
	//
	//     $ bazel run gazelle -- update --lang go,cc
	gazelleExtensionName = "cc"

	// If a third_party dep's dependency starts with this string, it means it's actually a system header and we should skip it.
	systemHeaderSentinel = "SYSTEM HEADER"
)

// CppResolver implements the resolve.Resolver and resolve.CrossResolver interfaces.
//
// Interface documentation:
//
// CppResolver is an interface that language extensions can implement to resolve
// dependencies in rules they generate.
type CppResolver struct{}

// Name implements the resolve.Resolver interface.
//
// Interface documentation:
//
// Name returns the name of the language. This should be a prefix of the
// kinds of rules generated by the language, e.g., "go" for the Go extension
// since it generates "go_library" rules.
func (rslv *CppResolver) Name() string {
	return gazelleExtensionName
}

// Imports implements the resolve.Resolver interface.
func (rslv *CppResolver) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	if r.Kind() == "py_cc_binding" {
		// Python imports with dots, so add a dotted import path here
		// e.g. //foo/bar:lib -> foo.bar.lib
		imp := strings.ReplaceAll(f.Pkg, "/", ".") + "." + r.Name()

		return []resolve.ImportSpec{{
			Lang: "py",
			Imp:  imp,
		}}
	}
	return nil
}

// Embeds implements the resolve.Resolver interface.
func (rslv *CppResolver) Embeds(*rule.Rule, label.Label) []label.Label { return nil }

// Resolve implements the resolve.Resolver interface.
//
// Resolve takes a (rule, ImportsParsedFromRuleSources) pair generated by Language.GenerateRules()
// and resolves the rule's dependencies based on its imports. It populates the rule's deps argument
// with the result of mapping each import to the label of a rule that provides the import. It does
// so by using the convention that each cc_library target which this rule depends on will
// expose a similarly named file. For example, needing "src/foo/Bar.h" assumes that a rule with
// label "//src/foo:Bar" exists.
//
// Gazelle calls this method once for each (rule, ImportsParsedFromRuleSources) pair generated by
// successive calls to Language.GenerateRules().
func (rslv *CppResolver) Resolve(_ *config.Config, _ *resolve.RuleIndex, _ *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
	importsFromRuleSources, ok := imports.(common.ImportsParsedFromRuleSources)
	if !ok {
		rule_add := ""
		if r != nil {
			rule_add = fmt.Sprintf(" from '%s' as a '%s'", r.AttrStrings("srcs"), r.Kind())
		}
		log.Printf("\n\nGot an unexpected type '%T' resolving imports for %s%s!\n\n"+
			"This is usually caused by a cross-language name collision for files. e.g., my_test.cc and my_test.py.\n"+
			"An easy fix is to rename one of them so their expected target names are different. e.g., my_test.cc -> my_cc_test.cc\n\n", imports, from.String(), rule_add)
		os.Exit(1)
	}
	var deps []label.Label
	// Assume that anything in repoIncludes is a target in the repo.
	// Anything in thirdPartyIncludes should be in our thirdPartyMap.
	// Anything in systemIncludes we just ignore.
	for _, include := range importsFromRuleSources.GetRepoIncludes() {
		// Change stem.cc.inl to stem.cc to find the right dep target
		if common.IsCppCcInl(include.IncludePath) {
			include.IncludePath = common.GetCppCcInlStem(include.IncludePath) + ".cc"
		}
		newLabel := resolveDepsForCImport(include, from.String())
		if newLabel.Repo == "" {
			newLabel.Repo = from.Repo
		}
		deps = append(deps, newLabel)
	}
	for _, importPath := range importsFromRuleSources.GetThirdPartyIncludes() {
		if d, ok := importsFromRuleSources.FindThirdPartyDep(importPath); ok {
			if strings.HasPrefix(d, systemHeaderSentinel) {
				continue
			}
			deps = append(deps, thirdPartyDep(d))
		} else {
			log.Printf("\n\nCould not find a Bazel target that provides the header %s (included in %s).\n"+
				"Most likely this is due to one of the following issues:\n\n"+
				" 1. Is it a first-party (Stack AV) header?\n"+
				"    If so, you need to include it using a full repo-relative path and use quotes instead of angle brackets.\n\n"+
				" 2. Are you adding a new third-party dependency?\n"+
				"   If so, the header you are using needs to be added to the third-party library mapping in tools/gazelle/cc_plugin/resources/third_party_mapping.json.", importPath, from.String())
			os.Exit(1)
		}
	}
	setDeps(r, from, deps)
}

// CrossResolve attempts to resolve an import string to a rule for languages
// other than the implementing extension. lang is the language of the rule
// with the dependency.
func (rslv *CppResolver) CrossResolve(c *config.Config, ix *resolve.RuleIndex, imp resolve.ImportSpec, lang string) []resolve.FindResult {
	if lang == "py" {
		// We receive import paths that aren't otherwise matched, and they can come in two forms:
		// - path.to.cc_binding
		// - path.to.cc_binding.Symbol
		// (it could also be that this isn't actually a cc binding)
		modulePaths := []string{imp.Imp}
		if strings.Contains(imp.Imp, ".") {
			modulePaths = append(modulePaths, imp.Imp[:strings.LastIndex(imp.Imp, ".")])
		}
		for _, modulePath := range modulePaths {
			importSpec := resolve.ImportSpec{
				Lang: "py",
				Imp:  modulePath,
			}
			result := ix.FindRulesByImportWithConfig(c, importSpec, "cc")
			if len(result) > 0 {
				return result
			}
		}
	}
	return nil
}

// thirdPartyDep parses a label string into a proper Label.
func thirdPartyDep(d string) label.Label {
	lbl, err := label.Parse(d)
	if err != nil {
		log.Fatalf("Invalid third_party dep %s - %s", d, err)
	}
	return lbl
}

// setDeps sets the dependencies of a rule.
func setDeps(r *rule.Rule, thisLabel label.Label, deps []label.Label) {
	const depsAttr = "deps"
	r.DelAttr(depsAttr)

	var depsAsStrings []string
	for _, dep := range deps {
		// Filter out self-imports, e.g. when the .cpp file includes the .h file.
		if thisLabel.Equal(dep) {
			continue
		}
		// Try to use a relative include if possible
		dep = dep.Rel(thisLabel.Repo, thisLabel.Pkg)
		depsAsStrings = append(depsAsStrings, dep.String())
	}

	if len(depsAsStrings) > 0 {
		depsAsStrings = util.SSliceDedup(depsAsStrings)
		sort.Strings(depsAsStrings)
		r.SetAttr(depsAttr, depsAsStrings)
	}
}

// resolveDepsForCImport takes a given path to a file and assumes that it is available by a rule
// with the same name, except the file extension is removed.
// For example, the file "alpha/beta/gamma/Delta.h" is assumed to be in the package
// "alpha/beta/gamma" with a rule called "Delta".
func resolveDepsForCImport(include common.Include, targetContainingImport string) label.Label {
	var importPath = include.IncludePath
	idx := strings.LastIndex(importPath, "/")
	var pkg, r string
	if idx < 0 {
		pkg = ""
		r = importPath
	} else {
		pkg = importPath[:idx]
		r = importPath[idx+1:]
	}

	// Protobuf libs have a deterministic name
	if strings.HasSuffix(r, ".grpc.pb.h") {
		r = r[:len(r)-len(".grpc.pb.h")]
		return label.New(include.Repo, pkg, r+"_grpc_cc_library")
	}
	if strings.HasSuffix(r, ".pb.h") {
		r = r[:len(r)-len(".pb.h")]
		if strings.HasSuffix(pkg, "/nanopb") {
			// A nanopb library has an extra path component. Remove it and attach it to the target name instead.
			pkg = strings.Split(pkg, "/nanopb")[0]
			return label.New(include.Repo, pkg, r+"_nanopb_cc_library")
		}
		return label.New(include.Repo, pkg, r+"_cc_library")
	}

	return label.New(include.Repo, pkg, common.TrimCSuffix(r))
}

var _ resolve.Resolver = &CppResolver{}
var _ resolve.CrossResolver = &CppResolver{}
