# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/demo_system:__subpackages__"],
)

clk(
    name = "imu_channel_policies_clk",
    srcs = ["imu_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":imu_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "imu_channels_clk",
    srcs = ["imu_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [":imu_message_clk"],
)

clk(
    name = "imu_clk",
    srcs = ["imu.clk"],
    outs = [
        "imu_clk_cc.cc",
        "imu_clk_cc.hh",
        "imu_clk_cc.inl",
        "imu_clk_cc_dial.cc",
        "imu_clk_cc_dial.hh",
        "imu_clk_cc_dial.inl",
        "imu_clk_exe.cc",
        "imu_clk_exe.hh",
        "imu_clk_exe.inl",
    ],
    cpp_deps = [":imu_message_clk_cc"],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [
        ":imu_channels_clk",
        ":imu_message_clk",
        "//clockwork/examples/demo_system:cpu_domain_clk",
    ],
)

cc_library(
    name = "imu_clk_cc_impl",
    srcs = ["imu_clk_cc_impl.cc"],
    deps = [
        ":imu_clk_cc_dial",
        ":imu_message_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/pinion:publishable",
    ],
)

clk(
    name = "imu_message_clk",
    srcs = ["imu_message.clk"],
    outs = [
        "imu_message_clk_cc.cc",
        "imu_message_clk_cc.hh",
        "imu_message_clk_cc.inl",
    ],
    generate = ["cpp"],
)
