// Copyright 2025-2026 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

// Package common contains any code used by two or more packages. It avoid circular dependencies.
package common

import (
	"slices"
	"strings"

	"go.skia.org/infra/go/util"

	"github.com/bazelbuild/bazel-gazelle/rule"
)

const ClkRule = "clk"

const ClkCppTarget = "cpp"
const ClkCppCogTarget = "cpp_cog"
const ClkCppTestCogTarget = "cpp_test_cog"
const ClkCppAlignerTarget = "cpp_aligner"
const ClkCppComboTestTarget = "cpp_combo_test"
const ClkCppExeTarget = "cpp_exe"
const ClkPyTarget = "py"
const ClkPyCogTarget = "py_cog"
const ClkPyExeTarget = "py_exe"
const ClkNanobindTarget = "nanobind"
const ClkProtoTarget = "proto"
const ClkGoProtoTarget = "go_proto"
const ClkProtoConvTarget = "proto_conv"

var AllGenerateTargets = []string{
	ClkCppTarget,
	ClkCppCogTarget,
	ClkCppTestCogTarget,
	ClkCppAlignerTarget,
	ClkCppComboTestTarget,
	ClkCppExeTarget,
	ClkPyTarget,
	ClkPyCogTarget,
	ClkPyExeTarget,
	ClkNanobindTarget,
	ClkProtoTarget,
	ClkGoProtoTarget,
	ClkProtoConvTarget,
}

var AllUseTargets = []string{
	ClkCppTarget,
	ClkPyTarget,
	ClkNanobindTarget,
	ClkProtoTarget,
	ClkProtoConvTarget,
	ClkPyCogTarget,
}

const ClkFileSuffix = ".clk"
const ClkRuleSuffix = "_clk"
const ClkCppRuleSuffix = "_cc"
const ClkNanobindRuleSuffix = "_nb"
const ClkProtoRuleSuffix = "_proto"
const ClkProtoConvRuleSuffix = "_proto_conv"
const ClkPyRuleSuffix = "_py"
const ClkPyDialRuleSuffix = "_py_dial"
const ClkPyImplRuleSuffix = "_py_impl"

const cppProtoHdrSuffix = ".pb.h"
const cppProtoRuleSuffix = "_cc_library"

// An import parsed from a clk use statement
type ClkImport struct {
	Repo       string
	ImportPath string
}

// ImportsParsedFromRuleSources is the "imports" interface returned by Language.GenerateRules(), and
// passed by Gazelle to Resolver.Resolve().
type ImportsParsedFromRuleSources interface {
	// GetClkGenerate returns the clockwork generate value
	GetClkGenerate() bool
	// GetClkGenerate returns the targets generated by the rule
	GetClkGenerates() []string
	// GetClkImports returns the imports for any clockwork targets
	GetClkImports() []ClkImport
	// GetCppImports returns the imports for cpp targets
	GetCppImports() []ClkImport
	// GetProtoImports returns the imports for proto targets
	GetProtoImports() []ClkImport
	// GetPyImports returns the imports for py targets
	GetPyImports() []ClkImport
	// GetCppExeImports() returns the imports for cpp_exe targets
	GetCppExeImports() []ClkImport
	// GetGoProtoImportPath returns the go protobuf import path or empty string if not set
	GetGoProtoImportPath() string
}

// importsParsedFromRuleSourcesImpl implements the common.ImportsParsedFromRuleSources interface.
type importsParsedFromRuleSourcesImpl struct {
	clkGenerate       bool
	clkGenerates      []string
	clkImports        []ClkImport
	cppImports        []ClkImport
	protoImports      []ClkImport
	pyImports         []ClkImport
	cppExeImports     []ClkImport
	goProtoImportPath string
}

func (i importsParsedFromRuleSourcesImpl) GetClkGenerate() bool {
	return i.clkGenerate
}

func (i importsParsedFromRuleSourcesImpl) GetClkGenerates() []string {
	return i.clkGenerates
}

func (i importsParsedFromRuleSourcesImpl) GetClkImports() []ClkImport {
	return i.clkImports
}

func (i importsParsedFromRuleSourcesImpl) GetCppImports() []ClkImport {
	return i.cppImports
}

func (i importsParsedFromRuleSourcesImpl) GetProtoImports() []ClkImport {
	return i.protoImports
}

func (i importsParsedFromRuleSourcesImpl) GetPyImports() []ClkImport {
	return i.pyImports
}

func (i importsParsedFromRuleSourcesImpl) GetCppExeImports() []ClkImport {
	return i.cppExeImports
}

func (i importsParsedFromRuleSourcesImpl) GetGoProtoImportPath() string {
	return i.goProtoImportPath
}

func NewImports(
	clkGenerate bool,
	clkGenerates []string,
	clkImports []ClkImport,
	cppImports []ClkImport,
	protoImports []ClkImport,
	pyImports []ClkImport,
	cppExeImports []ClkImport,
	goProtoImportPath string) ImportsParsedFromRuleSources {
	return importsParsedFromRuleSourcesImpl{
		clkGenerate:       clkGenerate,
		clkGenerates:      clkGenerates,
		clkImports:        clkImports,
		cppImports:        cppImports,
		protoImports:      protoImports,
		pyImports:         pyImports,
		cppExeImports:     cppExeImports,
		goProtoImportPath: goProtoImportPath,
	}
}

var _ ImportsParsedFromRuleSources = importsParsedFromRuleSourcesImpl{}

// GetClkRuleName returns the rule name for a clockwork source file
func GetClkRuleName(name string) string {
	return strings.TrimSuffix(name, getSuffix(name)) + ClkRuleSuffix
}

// GetClkCppRuleName returns the rule name for a clockwork cpp target
func GetClkCppRuleName(name string) string {
	return GetClkRuleName(name) + ClkCppRuleSuffix
}

// GetClkNanobindRuleName returns the rule name for a clockwork nanobind target
func GetClkNanobindRuleName(name string) string {
	return GetClkRuleName(name) + ClkNanobindRuleSuffix
}

// GetClkProtoRuleName returns the rule name for a clockwork proto target
func GetClkProtoRuleName(name string) string {
	return GetClkRuleName(name) + ClkProtoRuleSuffix
}

// GetClkProtoConvRuleName returns the rule name for a clockwork proto_conv target
func GetClkProtoConvRuleName(name string) string {
	return GetClkRuleName(name) + ClkProtoConvRuleSuffix
}

// GetClkPyRuleName returns the rule name for a clockwork py target
func GetClkPyRuleName(name string) string {
	return GetClkRuleName(name) + ClkPyRuleSuffix
}

// GetClkPyImplRuleName returns the rule name for a clockwork py cog implementation target
func GetClkPyImplRuleName(name string) string {
	return GetClkRuleName(name) + ClkPyImplRuleSuffix
}

// GetClkPyDialRuleName returns the rule name for a clockwork py cog dial target
func GetClkPyDialRuleName(name string) string {
	return GetClkRuleName(name) + ClkPyDialRuleSuffix
}

// GetCppHdrRuleName returns the rule name for a cpp header
func GetCppHdrRuleName(name string) string {
	name = strings.Join(strings.Split(name, "/"), "::")
	if strings.HasSuffix(name, cppProtoHdrSuffix) {
		return strings.TrimSuffix(name, cppProtoHdrSuffix) + cppProtoRuleSuffix
	}
	return strings.TrimSuffix(name, getSuffix(name))
}

// IsClkSource returns true if the given file name ends with ".clk"
func IsClkSource(name string) bool {
	suffix := getSuffix(name)
	return suffix == ClkFileSuffix
}

func getSuffix(name string) string {
	idx := strings.LastIndex(name, ".")
	if idx < 0 {
		return ""
	}
	return name[idx:]
}

const clkRepo = "clockwork"

// GetClockworkLabelString gets a label for an object in the clockwork repo given
// a label string. It will prepend @clockwork to the label string if we are not
// building in the clockwork repo.
func GetClockworkLabelString(labelStr string, inClockworkRepo bool) string {
	if !inClockworkRepo {
		return "@" + clkRepo + labelStr
	}
	return labelStr
}

// GetClockworkTargetString gets an import string for a target in the clockwork repo given
// an import string. It will prepend @clockwork:: to the target string if "clockwork" is
// in the external repos.
func GetClockworkTargetString(labelStr string, inClockworkRepo bool) string {
	if !inClockworkRepo {
		return "@" + clkRepo + "::" + labelStr
	}
	return labelStr
}

// Create a list of strings from a set of strings
func SortedStringsFromStringSet(stringSet map[string]bool) []string {
	result := []string{}
	for str := range stringSet {
		result = append(result, str)
	}
	slices.Sort(result)
	return result
}

// Create a list of ClkImport from a set of strings
func SortedClkImportsFromStringSet(stringSet map[string]bool) []ClkImport {
	result := []ClkImport{}
	for str := range stringSet {
		if strings.HasPrefix(str, "@") {
			str = strings.TrimPrefix(str, "@")
			parts := strings.Split(str, "::")
			repo := parts[0]
			importPath := ""
			if len(parts) > 1 {
				importPath = strings.Join(parts[1:], "::")
			}
			result = append(result, ClkImport{Repo: repo, ImportPath: importPath})
		} else {
			result = append(result, ClkImport{Repo: "", ImportPath: str})
		}
	}
	slices.SortFunc(result, func(a, b ClkImport) int {
		cmpResult := strings.Compare(a.Repo, b.Repo)
		if cmpResult != 0 {
			return cmpResult
		}
		return strings.Compare(a.ImportPath, b.ImportPath)
	})
	return result
}

// Set the generate attribute from the generate strings
func SetGenerateAttr(r *rule.Rule, generates []string) {
	const generatesAttr = "generate"
	r.DelAttr(generatesAttr)
	if len(generates) != 0 {
		generates = util.SSliceDedup(generates)
		slices.Sort(generates)
	} else {
		generates = []string{"none"}
	}
	r.SetAttr(generatesAttr, generates)
}
