# Autogenerated .pyi file for nb_log_writer_impl.

# This has to be here because it depends on aws_init.so in the @clockwork bazel workspace,
# which the nanobind stub generator has issues with.
#
# TODO(OI-3058): autogenerate this once cross-workspace shared libraries in nanobindings work properly.

from collections.abc import Sequence

import clockwork.logging.readers.nb_types

def copy_log(
    source_uri: str,
    dest_uri: str,
    maybe_desired_channels: Sequence[str] | None = None,
    maybe_excluded_channels: Sequence[str] | None = None,
    maybe_log_interval: clockwork.logging.readers.nb_types.RelativeInterval | None = None,
    writer_config_str: str = "",
    no_deep_copy: bool = False,
) -> None:
    """Copy a source log to a new log in the offboard log format.

    Arguments:
        source_uri: Source log URI.
        dest_uri: Destination log URI.
        maybe_desired_channels: Optional set of desired channels.
        maybe_excluded_channels: Optional set of excluded channels.
        maybe_log_interval: Optional relative log interval.
        writer_config_str: Writer config protobuf string.
        no_deep_copy: Don't deep copy log unions, just copy the log_union.pbtxt file.
    """  # noqa: PYI021 (Nanobind stubs need docstrings)
