# Autogenerated .pyi file for nb_log_writer_impl.

# This has to be here because it depends on aws_init.so in the @clockwork bazel workspace,
# which the nanobind stub generator has issues with.
#
# TODO(OI-3058): autogenerate this once cross-workspace shared libraries in nanobindings work properly.

from typing import Annotated

import clockwork.logging.readers.nb_types
from numpy.typing import ArrayLike

class LogWriter:
    def __init__(self) -> None:
        """Constructor."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def open(self, out_uri: str, config: str) -> None:
        """Open the log."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def close(self) -> None:
        """Close the log."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def create_channel(
        self,
        channel_name: str,
        message_encoding: str,
        channel_type: str,
        schema_name: str,
        schema_encoding: str,
        schema_definition: bytes,
    ) -> None:
        """Create a logged channel."""  # noqa: PYI021 (Nanobind stubs need docstrings)

    def write(
        self,
        channel_name: str,
        sequence_number: int,
        log_time: clockwork.logging.readers.nb_types.LogTimestamp,
        transmit_time: clockwork.logging.readers.nb_types.LogTimestamp,
        header: Annotated[ArrayLike, dict(dtype="uint8", shape=(None), writable=False)],  # noqa: C408 (false positive)
        data: Annotated[ArrayLike, dict(dtype="uint8", shape=(None), writable=False)],  # noqa: C408 (false positive)
    ) -> None:
        """Write a message to the log."""  # noqa: PYI021 (Nanobind stubs need docstrings)
