# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

cc_library(
    name = "at",
    hdrs = ["at.hh"],
    visibility = ["//visibility:public"],
    deps = ["@gsl//:util"],
)

cc_library(
    name = "bounded_string",
    srcs = ["bounded_string.inl"],
    hdrs = ["bounded_string.hh"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "circular_buffer",
    srcs = ["circular_buffer.inl"],
    hdrs = ["circular_buffer.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":circular_buffer_state_clk_cc",
        "//clockwork:repr_iface",
        "//jewels/memory:aligned_storage",
        "//jewels/memory:memory_resource",
        "//jewels/meta:call",
        "//jewels/meta:type_traits",
        "//jewels/std:expected",
        "@boost.iterator",
        "@wise_enum",
    ],
)

clk(
    name = "circular_buffer_state_clk",
    srcs = ["circular_buffer_state.clk"],
    outs = [
        "circular_buffer_state_clk_cc.cc",
        "circular_buffer_state_clk_cc.hh",
        "circular_buffer_state_clk_cc.inl",
        "circular_buffer_state_clk_cc_types.cc",
        "circular_buffer_state_clk_cc_types.hh",
        "circular_buffer_state_clk_cc_types.inl",
        "circular_buffer_state_clk_nb.cc",
        "circular_buffer_state_clk_nb.hh",
        "circular_buffer_state_clk_nb.inl",
        "circular_buffer_state_clk_proto.proto",
        "circular_buffer_state_clk_proto_conv.cc",
        "circular_buffer_state_clk_proto_conv.hh",
        "circular_buffer_state_clk_proto_conv.inl",
    ],
    generate = [
        "cpp",
        "nanobind",
        "proto",
        "proto_conv",
    ],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "compare",
    srcs = ["compare.inl"],
    hdrs = ["compare.hh"],
    visibility = ["//visibility:public"],
)
