"""Starlark protoc plugins.

Inspired by the examples from stackb's rules_proto at https://github.com/stackb/rules_proto/blob/master/example/golden/testdata/starlark_java/lib/plugins.star
This file is written in Starlark but is not used by Bazel.
"""

def _configure_nolint(ctx):
    """_configure_nolint creates a PluginConfiguration describing the nolint plugin.

    Args:
        ctx (protoc.PluginContext): The context object.
    Returns:
        config (PluginConfiguration): The configured PluginConfiguration object.
    """
    config = protoc.PluginConfiguration(
        label = "@clockwork//tools/gazelle:protoc-gen-nolint",
        # This plugin currently only modifies existing files that were generated by other plugins, it does not generate any outputs of its own
        outputs = [],
        options = ctx.plugin_config.options,
    )

    return config

protoc.Plugin(
    name = "protoc-gen-nolint",
    configure = _configure_nolint,
)
