# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

cc_library(
    name = "lock_provider",
    srcs = ["lock_provider.inl"],
    hdrs = ["lock_provider.hh"],
    visibility = ["//jewels/shared_pool:__subpackages__"],
)

cc_library(
    name = "reference_counter",
    srcs = ["reference_counter.inl"],
    hdrs = ["reference_counter.hh"],
    visibility = ["//jewels/shared_pool:__subpackages__"],
)
