# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("@rules_multirun//:defs.bzl", "command")
load("//clockwork:rules.bzl", "clk")
load("//jewels/simplelaunch:rules.bzl", "merge_simplelaunch_config")
load("//tools/rules:cc.bzl", "cc_binary", "cc_library")

package(
    default_visibility = ["//clockwork:__subpackages__"],
)

clk(
    name = "example_cogs_clk",
    srcs = ["example_cogs.clk"],
    outs = [
        "example_cogs_clk_cc.cc",
        "example_cogs_clk_cc.hh",
        "example_cogs_clk_cc.inl",
        "example_cogs_clk_cc_cog.cc",
        "example_cogs_clk_cc_cog.hh",
        "example_cogs_clk_cc_cog.inl",
        "example_cogs_clk_cc_dial.cc",
        "example_cogs_clk_cc_dial.hh",
        "example_cogs_clk_cc_dial.inl",
        "example_cogs_clk_cc_types.cc",
        "example_cogs_clk_cc_types.hh",
        "example_cogs_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":test_message_clk_cc",
        "//clockwork/logging/log_playback:end_of_log_clk_cc",
    ],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [
        ":test_message_clk",
        "//clockwork/logging/log_playback:end_of_log_clk",
    ],
)

cc_library(
    name = "example_cogs_clk_cc_impl",
    srcs = ["example_cogs_clk_cc_impl.cc"],
    deps = [
        ":example_cogs_clk_cc_dial",
        ":test_message_clk_cc",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/container/tap:var_string",
        "//jewels/log_cerr",
        "//jewels/memory:aligned_storage",
        "//jewels/uuid",
    ],
)

cc_binary(
    name = "log_gen",
    srcs = ["log_gen.cc"],
    deps = [
        ":test_message_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging/offboard:types",
        "//clockwork/logging/offboard:writer",
        "//jewels/container/tap:var_string",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pointers",
        "//jewels/std:span",
        "//jewels/time:conversions",
        "//jewels/time:sync_time",
        "@fmt",
    ],
)

clk(
    name = "log_runner_example_clk",
    srcs = ["log_runner_example.clk"],
    outs = [
        "log_runner_example_clk_exe.cc",
        "log_runner_example_clk_exe.hh",
        "log_runner_example_clk_exe.inl",
    ],
    cpp_deps = [
        ":example_cogs_clk_cc",
        ":test_message_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:offline_main"],
    generate = ["cpp_exe"],
    deps = [
        ":example_cogs_clk",
        ":test_message_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging/log_playback:end_of_log_channel_clk",
    ],
)

cc_library(
    name = "log_runner_example_lib",
    srcs = [
        "log_runner_example_clk_exe.cc",
        "log_runner_example_clk_exe.hh",
        "log_runner_example_clk_exe.inl",
    ],
    deps = [
        ":example_cogs_clk_cc",
        ":test_message_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/scaffolding:abstract_casing",
        "//clockwork/scaffolding:casing",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
    ],
)

clk(
    name = "log_runner_example_system_clk",
    srcs = ["log_runner_example_system.clk"],
    outs = [
        "clockwork.clockwork.examples.log_runner.log_runner_example_system.log_runner_example_system.proc.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_allocations.csv",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_publisher_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_spy_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_event_logger_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_journal_topology.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_metrics_channel_metadata_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_signal_metadata_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_simplelaunch_config.textproto",
        "log_runner_example_system.log_runner_example_system.SimCpu_system_metadata.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_telemetry_logger_config.tachyon",
        "log_runner_example_system.log_runner_example_system.diagnostics_database_config.tachyon",
        "log_runner_example_system.log_runner_example_system.logged_channel_metadata.pbbin",
    ],
    deps = [":log_runner_example_clk"],
)

# Convenience target to avoid passing around the long path to config file every time
command(
    name = "run_example_system",
    arguments = [
        "--deterministic-runner",
        "--input-log-uri",
        "/tmp/test_log/log_runner/publisher/",
        "--channel-publisher-config",
        "clockwork/examples/log_runner/log_runner_example_system.log_runner_example_system.SimCpu_channel_publisher_config.tachyon",
        "--output-log-uri",
        "/tmp/test_log/log_runner/log_writer/",
        "--log-writer-config",
        "clockwork/examples/log_runner/log_runner_example_system.log_runner_example_system.SimCpu_telemetry_logger_config.tachyon",
        "clockwork/examples/log_runner/clockwork.clockwork.examples.log_runner.log_runner_example_system.log_runner_example_system.proc.tachyon",
    ],
    command = "//clockwork/examples/log_runner:log_runner_example_clk_exe",
    data = [":simcpu.textproto"],
)

merge_simplelaunch_config(
    name = "simcpu.textproto",
    srcs = [
        "log_runner_example_system.log_runner_example_system.SimCpu_simplelaunch_config.textproto",
        "@clockwork//clockwork/launch:clockwork_prelaunch.textproto",
    ],
    data = [
        "clockwork.clockwork.examples.log_runner.log_runner_example_system.log_runner_example_system.proc.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_allocations.csv",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_publisher_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_channel_spy_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_event_logger_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_journal_topology.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_metrics_channel_metadata_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_signal_metadata_config.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_system_metadata.tachyon",
        "log_runner_example_system.log_runner_example_system.SimCpu_telemetry_logger_config.tachyon",
        "log_runner_example_system.log_runner_example_system.diagnostics_database_config.tachyon",
        ":log_runner_example_clk_exe",
        "@clockwork//clockwork/pinion:tcp_bridge_main",
    ],
)

clk(
    name = "test_message_clk",
    srcs = ["test_message.clk"],
    outs = [
        "test_message_clk_cc.cc",
        "test_message_clk_cc.hh",
        "test_message_clk_cc.inl",
        "test_message_clk_cc_types.cc",
        "test_message_clk_cc_types.hh",
        "test_message_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    visibility = ["//visibility:public"],
)
