# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_test")

package(default_testonly = True)

cc_test(
    name = "cog_conditions_test",
    srcs = ["cog_conditions_test.cc"],
    deps = [
        "//clockwork/cog:cog_conditions",
        "//clockwork/cog:input_condition",
        "//clockwork/common:process_description",
        "//clockwork/dial:cond_messages_present",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_configs_test",
    srcs = ["cog_configs_test.cc"],
    deps = [
        "//clockwork/cog:cog_configs",
        "//clockwork/common:process_description",
        "//jewels/container:compare",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_inputs_test",
    srcs = ["cog_inputs_test.cc"],
    deps = [
        "//clockwork/cog:cog_conditions",
        "//clockwork/cog:cog_inputs",
        "//clockwork/cog:input_condition",
        "//clockwork/common:process_description",
        "//clockwork/dial:cond_messages_present",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/container:circular_buffer",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_memory_resources_test",
    srcs = ["cog_memory_resources_test.cc"],
    deps = [
        "//clockwork/cog:cog_memory_resources",
        "//clockwork/common:process_description",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_passthrough_observer_test",
    srcs = ["cog_passthrough_observer_test.cc"],
    deps = [
        "//clockwork/cog:cog_passthrough_observer",
        "//jewels/memory:pointers",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "cog_publishers_test",
    srcs = ["cog_publishers_test.cc"],
    deps = [
        "//clockwork/cog:cog_publishers",
        "//clockwork/common:process_description",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_state_test",
    srcs = ["cog_state_test.cc"],
    deps = [
        "//clockwork/cog:cog_state",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "cog_states_test",
    srcs = ["cog_states_test.cc"],
    deps = [
        "//clockwork/cog:cog_state",
        "//clockwork/cog:cog_states",
        "//clockwork/common:process_description",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "cog_statistics_test",
    srcs = ["cog_statistics_test.cc"],
    deps = [
        "//clockwork/cog:cog_statistics",
        "//clockwork/dsl/cog:ten_nanosecond_type",
        "//jewels/memory:memory_resource",
        "//jewels/time:conversions",
        "//jewels/time:sync_time",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "cog_timers_test",
    srcs = ["cog_timers_test.cc"],
    deps = [
        "//clockwork/cog:cog_timers",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:process_description",
        "//clockwork/dial:cond_time_since_last_exec",
        "//clockwork/pinion:observer",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "input_condition_test",
    srcs = ["input_condition_test.cc"],
    deps = [
        "//clockwork/cog:input_condition",
        "//clockwork/common:process_description",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "input_view_test",
    srcs = ["input_view_test.cc"],
    deps = [
        "//clockwork/cog:input_view",
        "//clockwork/common:process_description",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/container:circular_buffer",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "multiple_shared_state_test",
    srcs = ["multiple_shared_state_test.cc"],
    deps = [
        "//clockwork/cog:cog_state",
        "//clockwork/cog:cog_states",
        "//clockwork/cog:detail",
        "//clockwork/cog:simple_cog",
        "//clockwork/cog/tests/support:fake_cog",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:process_description",
        "//clockwork/runners:online_cog_queue",
        "//clockwork/runners:online_runner",
        "//clockwork/runners:thread_pool",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "multiple_subscriber_test",
    srcs = ["multiple_subscriber_test.cc"],
    deps = [
        "//clockwork/cog:cog_conditions",
        "//clockwork/cog:cog_inputs",
        "//clockwork/cog:cog_publishers",
        "//clockwork/cog:cog_state",
        "//clockwork/cog:cog_states",
        "//clockwork/cog:cog_statistics",
        "//clockwork/cog:cog_timers",
        "//clockwork/cog:detail",
        "//clockwork/cog:input_condition",
        "//clockwork/cog:simple_cog",
        "//clockwork/cog/tests/support:fake_cog",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:process_description",
        "//clockwork/dial:cond_messages_present",
        "//clockwork/dial:cond_time_since_last_exec",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:error",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//clockwork/runners:epoll_manager",
        "//clockwork/runners:online_cog_queue",
        "//clockwork/runners:online_runner",
        "//clockwork/runners:thread_pool",
        "//clockwork/runners:timerfd_timer",
        "//jewels/container:circular_buffer",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "simple_cog_test",
    srcs = ["simple_cog_test.cc"],
    deps = [
        "//clockwork/cog:cog_conditions",
        "//clockwork/cog:cog_configs",
        "//clockwork/cog:cog_diagnostics",
        "//clockwork/cog:cog_infra_diagnostics",
        "//clockwork/cog:cog_inputs",
        "//clockwork/cog:cog_memory_resources",
        "//clockwork/cog:cog_publishers",
        "//clockwork/cog:cog_state",
        "//clockwork/cog:cog_states",
        "//clockwork/cog:cog_statistics",
        "//clockwork/cog:cog_timers",
        "//clockwork/cog:detail",
        "//clockwork/cog:input_condition",
        "//clockwork/cog:simple_cog",
        "//clockwork/cog/tests/support:fake_cog",
        "//clockwork/cog/tests/support:test_cog_event_metrics_cpp",
        "//clockwork/cog/tests/support:test_cog_telemetry_metrics_cpp",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:abstract_cog_queue",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:cog_envelope",
        "//clockwork/common:cog_execution_error",
        "//clockwork/common:process_description",
        "//clockwork/diagnostics:report",
        "//clockwork/diagnostics:report_definitions",
        "//clockwork/diagnostics:reporter",
        "//clockwork/dial:cond_messages_present",
        "//clockwork/dial:cond_time_since_last_exec",
        "//clockwork/dial:msg_input",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:error",
        "//clockwork/pinion:in_memory_channel",
        "//clockwork/pinion:observer",
        "//clockwork/pinion:publisher_handle",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pmr_unique_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@boost//:iterator",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "single_shared_state_test",
    srcs = ["single_shared_state_test.cc"],
    deps = [
        "//clockwork/cog:cog_state",
        "//clockwork/cog:cog_states",
        "//clockwork/cog:simple_cog",
        "//clockwork/cog/tests/support:fake_cog",
        "//clockwork/common:abstract_cog",
        "//clockwork/common:process_description",
        "//clockwork/runners:online_cog_queue",
        "//clockwork/runners:online_runner",
        "//clockwork/runners:thread_pool",
        "//jewels/container:compare",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)

cc_test(
    name = "time_since_last_exec_handler_test",
    srcs = ["time_since_last_exec_handler_test.cc"],
    deps = [
        "//clockwork/cog:time_since_last_exec_handler",
        "//clockwork/common:abstract_timer",
        "//clockwork/common:process_description",
        "//clockwork/pinion:observer",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "//jewels/uuid",
        "@catch2//:catch2_main",
        "@gsl//:util",
    ],
)
