# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")
load("//tools/rules:python.bzl", "py_binary", "py_cc_binding", "py_library")

package(default_visibility = ["//visibility:public"])

exports_files(["channel_spy_config.clk"])

cc_library(
    name = "channel_spy",
    srcs = [
        "channel_spy.cc",
        "channel_spy.inl",
    ],
    hdrs = ["channel_spy.hh"],
    deps = [
        ":channel_spy_config_clk_cc",
        ":channel_spy_subscriber",
        ":types",
        "//clockwork:repr_iface",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "//jewels/uuid",
        "@fmt",
    ],
)

py_binary(
    name = "channel_spy_cli",
    srcs = ["channel_spy_cli.py"],
    deps = [
        ":py_channel_spy",
        "@clockwork_pip//click",
        "@clockwork_pip//typing_extensions",
    ],
)

clk(
    name = "channel_spy_config_clk",
    srcs = ["channel_spy_config.clk"],
    outs = [
        "channel_spy_config_clk_cc.cc",
        "channel_spy_config_clk_cc.hh",
        "channel_spy_config_clk_cc.inl",
    ],
    cpp_deps = ["//clockwork/common:process_description_clk_cc"],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    deps = [
        "//clockwork/common:constants_clk",
        "//clockwork/common:process_description_clk",
    ],
)

clk(
    name = "channel_spy_config_init_clk",
    srcs = ["channel_spy_config_init.clk"],
    outs = [
        "channel_spy_config_init_clk_cc.cc",
        "channel_spy_config_init_clk_cc.hh",
        "channel_spy_config_init_clk_cc.inl",
        "channel_spy_config_init_clk_cc_dial.cc",
        "channel_spy_config_init_clk_cc_dial.hh",
        "channel_spy_config_init_clk_cc_dial.inl",
        "channel_spy_config_init_clk_exe.cc",
        "channel_spy_config_init_clk_exe.hh",
        "channel_spy_config_init_clk_exe.inl",
    ],
    cpp_deps = [":channel_spy_config_clk_cc"],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [":channel_spy_config_clk"],
)

cc_library(
    name = "channel_spy_config_init_clk_cc_impl",
    srcs = ["channel_spy_config_init_clk_cc_impl.cc"],
    deps = [
        ":channel_spy",
        ":channel_spy_config_clk_cc",
        ":channel_spy_config_init_clk_cc_dial",
        "//jewels/container:compare",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/filesystem:path",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@fmt",
    ],
)

cc_library(
    name = "channel_spy_subscriber",
    srcs = [
        "channel_spy_subscriber.cc",
        "channel_spy_subscriber.inl",
    ],
    hdrs = ["channel_spy_subscriber.hh"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":types",
        "//clockwork:repr_iface",
        "//clockwork/pinion:buffer",
        "//clockwork/pinion:shm_channel",
        "//clockwork/pinion:shm_channel_factory",
        "//clockwork/pinion:shm_subscriber",
        "//clockwork/pinion:slot",
        "//clockwork/pinion:slot_ref",
        "//clockwork/pinion:subscriber_handle",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@fmt",
    ],
)

py_cc_binding(
    name = "nb_channel_spy",
    srcs = ["nb_channel_spy.cc"],
    imports = ["../../.."],
    deps = [
        ":channel_spy",
        ":channel_spy_config_clk_cc",
        ":types",
        "//clockwork/pinion:slot_ref",
        "@nanobind",
        "@python_3_10//:python_headers",
    ],
)

py_library(
    name = "py_channel_spy",
    srcs = ["py_channel_spy.py"],
    deps = [
        ":nb_channel_spy",
        "//clockwork/dsl:compiler_context",
        "//clockwork/serialization/metadata:tachyon",
        "//clockwork/serialization/py:protocol",
        "//clockwork/serialization/py:tachyon_dyn_from_metadata",
        "@clockwork_pip//typing_extensions",
    ],
)

cc_library(
    name = "types",
    srcs = ["types.cc"],
    hdrs = ["types.hh"],
    deps = [
        "//clockwork/pinion:slot_ref",
        "//jewels/memory:pointers",
    ],
)
