# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "test_message_handle",
    srcs = ["test_message_handle.inl"],
    hdrs = ["test_message_handle.hh"],
)

cc_library(
    name = "test_support",
    srcs = ["test_support.cc"],
    hdrs = ["test_support.hh"],
    deps = [
        "//clockwork/logging:channel_type_clk_cc",
        "//clockwork/logging:log_error",
        "//clockwork/logging:log_timestamp",
        "//clockwork/logging:nolint_helper",
        "//clockwork/logging:schema_encoding_clk_cc",
        "//clockwork/logging:xxh3_checksum",
        "//clockwork/logging:zstd_helper",
        "//clockwork/logging/onboard:log_format",
        "//clockwork/logging/onboard:types",
        "//jewels/container:at",
        "//jewels/filesystem",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file_descriptor",
        "//jewels/log_cerr",
        "//jewels/memory:default_memory_resource",
        "//jewels/memory:memory_resource",
        "//jewels/std:expected",
        "@fmt",
    ],
)
