# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//clockwork/examples/demo_system:__subpackages__"],
)

clk(
    name = "lidar_channel_policies_clk",
    srcs = ["lidar_channel_policies.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [
        ":lidar_channels_clk",
        "//clockwork/logging:channel_policy_clk",
        "//clockwork/logging:channel_type_clk",
    ],
)

clk(
    name = "lidar_channels_clk",
    srcs = ["lidar_channels.clk"],
    generate = ["none"],
    visibility = ["//visibility:public"],
    deps = [":lidar_message_clk"],
)

clk(
    name = "lidar_clk",
    srcs = ["lidar.clk"],
    outs = [
        "lidar_clk_cc.cc",
        "lidar_clk_cc.hh",
        "lidar_clk_cc.inl",
        "lidar_clk_cc_cog.cc",
        "lidar_clk_cc_cog.hh",
        "lidar_clk_cc_cog.inl",
        "lidar_clk_cc_dial.cc",
        "lidar_clk_cc_dial.hh",
        "lidar_clk_cc_dial.inl",
        "lidar_clk_cc_types.cc",
        "lidar_clk_cc_types.hh",
        "lidar_clk_cc_types.inl",
        "lidar_clk_exe.cc",
        "lidar_clk_exe.hh",
        "lidar_clk_exe.inl",
    ],
    cpp_deps = [
        ":lidar_message_clk_cc",
        ":lidar_state_clk_cc",
        "//clockwork/examples/demo_system/localization:pose_message_clk_cc",
    ],
    cpp_exe_deps = ["//clockwork/scaffolding:online_main"],
    generate = [
        "cpp",
        "cpp_cog",
        "cpp_exe",
    ],
    deps = [
        ":lidar_channels_clk",
        ":lidar_message_clk",
        ":lidar_state_clk",
        "//clockwork/examples/demo_system:cpu_domain_clk",
        "//clockwork/examples/demo_system/localization:localization_channels_clk",
        "//clockwork/examples/demo_system/localization:pose_message_clk",
    ],
)

cc_library(
    name = "lidar_clk_cc_impl",
    srcs = ["lidar_clk_cc_impl.cc"],
    deps = [
        ":lidar_clk_cc_dial",
        ":lidar_message_clk_cc",
        ":lidar_state_clk_cc",
        "//clockwork/dial:msg_input",
        "//clockwork/examples/demo_system/localization:pose_filter",
        "//clockwork/examples/demo_system/localization:pose_message_clk_cc",
        "//clockwork/memory:start_lifetime_as",
        "//clockwork/pinion:publishable",
        "//clockwork/pinion:slot",
        "//jewels/container/tap:var_array",
        "//jewels/math:constants",
        "//jewels/memory:aligned_storage",
        "//jewels/memory:memory_resource",
        "//jewels/uuid",
    ],
)

clk(
    name = "lidar_message_clk",
    srcs = ["lidar_message.clk"],
    outs = [
        "lidar_message_clk_cc.cc",
        "lidar_message_clk_cc.hh",
        "lidar_message_clk_cc.inl",
        "lidar_message_clk_cc_types.cc",
        "lidar_message_clk_cc_types.hh",
        "lidar_message_clk_cc_types.inl",
    ],
    cpp_deps = ["//clockwork/examples/demo_system/localization:pose_message_clk_cc"],
    generate = ["cpp"],
    deps = ["//clockwork/examples/demo_system/localization:pose_message_clk"],
)

clk(
    name = "lidar_state_clk",
    srcs = ["lidar_state.clk"],
    outs = [
        "lidar_state_clk_cc.cc",
        "lidar_state_clk_cc.hh",
        "lidar_state_clk_cc.inl",
        "lidar_state_clk_cc_types.cc",
        "lidar_state_clk_cc_types.hh",
        "lidar_state_clk_cc_types.inl",
    ],
    cpp_deps = [":lidar_message_clk_cc"],
    generate = ["cpp"],
    deps = [":lidar_message_clk"],
)
