// Copyright 2025-2026 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "clockwork/common/abstract_timer.hh"
#include "clockwork/common/cog_execution_error_clk_cc.hh"
#include "clockwork/common/forward.hh"
#include "clockwork/pinion/observer.hh"
#include "jewels/callsig/outcome.hh"
#include "jewels/callsig/outparam.hh"
#include "jewels/memory/pointers.hh"
#include "jewels/std/expected.hh"
#include "jewels/time/sync_time.hh"

#include <wise_enum.h>

#include <cstdint>
#include <memory>
#include <mutex>
#include <optional>
#include <string_view>

namespace clockwork
{

WISE_ENUM_CLASS((CogExecutionMode, uint8_t), online, deterministic);

/// Result of preparing a Cog for execution.
WISE_ENUM_CLASS(
  (CogPrepareResult, uint8_t), ready, not_ready, states_lock_contention, reentry_lock_contention, publisher_throttled);

/// Callsig outcome for Cog preparation. `ready` is the only successful result.
using CogPrepareOutcome = jewels::Outcome<CogPrepareResult, CogPrepareResult::ready>;
///
/// Parameter struct passed to all Cog executions.
///
struct CogExecuteParams
{
  ///
  /// The timestamp of the start of the execution.
  ///
  jewels::time::SyncTime start_time = {};

  ///
  /// The Execution mode of the cog.
  ///
  CogExecutionMode execution_mode = CogExecutionMode::online;
};

struct CogConfig
{
  jewels::memory::ObjectPtr<AbstractCog> cog;
};

///
/// The AbstractCog is the top public interface around a user defined function.
/// Implementations of a Cog are, usually, automatically generated by the Clockwork
/// DSL and provided as input to a Clockwork Runner to execute as part of the system.
///
class AbstractCog
{
public:
  ///
  /// Constructor.
  /// @param[in] queue The queue to use when the cog is ready to execute.
  ///
  explicit AbstractCog(jewels::memory::ObjectPtr<AbstractCogQueue> queue);

  ///
  /// Destructor.
  ///
  virtual ~AbstractCog();

  AbstractCog(const AbstractCog&) = delete;
  AbstractCog& operator=(const AbstractCog&) = delete;
  AbstractCog(AbstractCog&&) = delete;
  AbstractCog& operator=(AbstractCog&&) = delete;

  ///
  /// Get the cog name.
  /// @return The name of the cog.
  ///
  [[nodiscard]] virtual std::string_view get_name() const = 0;

  ///
  /// Prime the cog. Perform any required startup tasks (i.e. prime timers).
  /// @return Unexpected if any required handles are unset
  ///
  [[nodiscard]] virtual jewels::expected<void, jewels::MonoError> prime(jewels::time::SyncTime start_time) = 0;

  ///
  /// Perform any necessary action to prepare this Cog for execution.
  /// E.g. Acquire any necessary locks (e.g. shared state mutexes).
  /// @note Every successful call to prepare_for_execution __must__ be followed
  ///   by a call to execute.
  /// @param[out] throttled_until_out The publisher eligibility deadline when publisher throttled.
  /// @param[in] current_time The current synchronized time.
  /// @return The preparation result.
  ///
  virtual CogPrepareOutcome prepare_for_execution(
    jewels::Out<jewels::time::SyncTime> throttled_until_out, jewels::time::SyncTime current_time) = 0;

  /// Check whether this Cog requires a private publisher-throttle timer.
  /// @return True for Cogs with at least one rate-limited publisher.
  [[nodiscard]] virtual bool has_rate_limited_publishers() const;

  /// Install the private publisher-throttle timer.
  /// @param[in] timer The timer instance supplied by runner scaffolding.
  /// @return Success if the timer was installed.
  jewels::BinaryOutcome set_publisher_throttle_timer(std::shared_ptr<AbstractTimer> timer);

  /// Arm the private publisher-throttle timer for an absolute deadline.
  /// Repeated requests for the current deadline are inert.
  /// @param[in] throttled_until The next publisher eligibility deadline.
  /// @return Success if the timer is armed for the requested deadline.
  jewels::BinaryOutcome arm_publisher_throttle_timer(jewels::time::SyncTime throttled_until);

  ///
  /// Execute the cog and unlock any shared resources.
  /// @pre prepare_for_execution() was called and returned ready.
  /// @param[in] params Execution parameters (start time, etc).
  /// @return true if the Cog executed successfully.
  ///
  [[nodiscard]] virtual jewels::expected<void, CogExecutionError> execute(CogExecuteParams params) = 0;

protected:
  ///
  /// Notify the queue that the cog has completed and it should re-process its queue.
  ///
  void notify_ready_queue();

  ///
  /// Add this cog to the ready cog queue.
  ///
  void add_to_ready_queue(jewels::time::SyncTime ready_time);

private:
  ///
  /// Ready cog queue.  The cog is responsible to pushing itself onto the queue
  /// whenever it is ready to execute.
  ///
  jewels::memory::ObjectPtr<AbstractCogQueue> queue_;

  /// Protects the private publisher-throttle timer state.
  mutable std::mutex publisher_throttle_timer_mutex_;

  /// Private timer used only to wake the scheduler after publisher throttling.
  std::shared_ptr<AbstractTimer> publisher_throttle_timer_;

  /// Observer that forwards the private timer notification to the ready queue.
  std::shared_ptr<pinion::Observer> publisher_throttle_timer_observer_;

  /// Currently armed publisher-throttle deadline.
  std::optional<jewels::time::SyncTime> publisher_throttle_timer_deadline_;
};

} // namespace clockwork
