// Copyright 2025 Stack AV Co.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "clockwork/common/cog_execution_error_clk_cc.hh"
#include "clockwork/common/forward.hh"
#include "jewels/memory/pointers.hh"
#include "jewels/std/expected.hh"
#include "jewels/time/sync_time.hh"

#include <wise_enum.h>

#include <cstdint>
#include <string_view>

namespace clockwork
{

WISE_ENUM_CLASS((CogExecutionMode, uint8_t), online, deterministic);
///
/// Parameter struct passed to all Cog executions.
///
struct CogExecuteParams
{
  ///
  /// The timestamp of the start of the execution.
  ///
  jewels::time::SyncTime start_time = {};

  ///
  /// The Execution mode of the cog.
  ///
  CogExecutionMode execution_mode = CogExecutionMode::online;
};

struct CogConfig
{
  jewels::memory::ObjectPtr<AbstractCog> cog;
};

///
/// The AbstractCog is the top public interface around a user defined function.
/// Implementations of a Cog are, usually, automatically generated by the Clockwork
/// DSL and provided as input to a Clockwork Runner to execute as part of the system.
///
class AbstractCog
{
public:
  ///
  /// Constructor.
  /// @param[in] queue The queue to use when the cog is ready to execute.
  ///
  explicit AbstractCog(jewels::memory::ObjectPtr<AbstractCogQueue> queue);

  ///
  /// Destructor.
  ///
  virtual ~AbstractCog();

  AbstractCog(const AbstractCog&) = delete;
  AbstractCog& operator=(const AbstractCog&) = delete;
  AbstractCog(AbstractCog&&) = delete;
  AbstractCog& operator=(AbstractCog&&) = delete;

  ///
  /// Get the cog name.
  /// @return The name of the cog.
  ///
  [[nodiscard]] virtual std::string_view get_name() const = 0;

  ///
  /// Prime the cog. Perform any required startup tasks (i.e. prime timers).
  /// @return Unexpected if any required handles are unset
  ///
  [[nodiscard]] virtual jewels::expected<void, jewels::MonoError> prime(jewels::time::SyncTime start_time) = 0;

  ///
  /// Perform any necessary action to prepare this Cog for execution.
  /// E.g. Acquire any necessary locks (e.g. shared state mutexes).
  /// @note Every successful call to prepare_for_execution __must__ be followed
  ///   by a call to execute.
  /// @return true if the Cog is is ready to be executed.
  ///
  [[nodiscard]] virtual jewels::expected<void, CogExecutionError>
  prepare_for_execution(jewels::time::SyncTime current_time) = 0;

  ///
  /// Execute the cog and unlock any shared resources.
  /// @pre prepare_for_execution() was called and returned true.
  /// @param[in] params Execution parameters (start time, etc).
  /// @return true if the Cog executed successfully.
  ///
  [[nodiscard]] virtual jewels::expected<void, CogExecutionError> execute(CogExecuteParams params) = 0;

protected:
  ///
  /// Notify the queue that the cog has completed and it should re-process its queue.
  ///
  void notify_ready_queue();

  ///
  /// Add this cog to the ready cog queue.
  ///
  void add_to_ready_queue(jewels::time::SyncTime ready_time);

private:
  ///
  /// Ready cog queue.  The cog is responsible to pushing itself onto the queue
  /// whenever it is ready to execute.
  ///
  jewels::memory::ObjectPtr<AbstractCogQueue> queue_;
};

} // namespace clockwork
