# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//clockwork:__subpackages__"])

exports_files([
    "process_description.clk",
    "multi_subscriber_config.clk",
    "platform_diagnostics_config.clk",
    "signal_metadata_config.clk",
    "simplelaunch_runner_config.clk",
])

cc_library(
    name = "abstract_cog",
    srcs = ["abstract_cog.cc"],
    hdrs = ["abstract_cog.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":abstract_cog_queue",
        ":abstract_timer",
        ":cog_envelope",
        ":cog_execution_error_clk_cc",
        ":forward",
        "//clockwork/pinion:observer",
        "//jewels/callsig:outcome",
        "//jewels/callsig:outparam",
        "//jewels/memory:pointers",
        "//jewels/std:expected",
        "//jewels/time:sync_time",
        "@wise_enum",
    ],
)

cc_library(
    name = "abstract_cog_queue",
    srcs = ["abstract_cog_queue.cc"],
    hdrs = ["abstract_cog_queue.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":forward",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "abstract_epoll_manager",
    srcs = ["abstract_epoll_manager.cc"],
    hdrs = ["abstract_epoll_manager.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//jewels/filesystem:error_code",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/std:expected",
    ],
)

cc_library(
    name = "abstract_timer",
    srcs = ["abstract_timer.cc"],
    hdrs = ["abstract_timer.hh"],
    deps = [
        ":abstract_epoll_manager",
        "//clockwork/pinion:observer",
        "//jewels/time:sync_time",
    ],
)

cc_library(
    name = "cog_envelope",
    srcs = ["cog_envelope.cc"],
    hdrs = ["cog_envelope.hh"],
    deps = [
        ":forward",
        "//jewels/memory:pointers",
        "//jewels/time:sync_time",
    ],
)

clk(
    name = "cog_execution_error_clk",
    srcs = ["cog_execution_error.clk"],
    outs = [
        "cog_execution_error_clk_cc.cc",
        "cog_execution_error_clk_cc.hh",
        "cog_execution_error_clk_cc.inl",
        "cog_execution_error_clk_cc_types.cc",
        "cog_execution_error_clk_cc_types.hh",
        "cog_execution_error_clk_cc_types.inl",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
)

clk(
    name = "cog_gpu_assignment_config_clk",
    srcs = ["cog_gpu_assignment_config.clk"],
    outs = [
        "cog_gpu_assignment_config_clk_cc.cc",
        "cog_gpu_assignment_config_clk_cc.hh",
        "cog_gpu_assignment_config_clk_cc.inl",
        "cog_gpu_assignment_config_clk_cc_types.cc",
        "cog_gpu_assignment_config_clk_cc_types.hh",
        "cog_gpu_assignment_config_clk_cc_types.inl",
        "cog_gpu_assignment_config_clk_py.py",
    ],
    cpp_deps = [":process_description_clk_cc"],
    generate = [
        "cpp",
        "py",
    ],
    minimize_builtin_deps = True,
    py_deps = [":process_description_clk_py"],
    visibility = ["//visibility:public"],
    deps = [":process_description_clk"],
)

clk(
    name = "constants_clk",
    srcs = ["constants.clk"],
    outs = [
        "constants_clk_cc.cc",
        "constants_clk_cc.hh",
        "constants_clk_cc.inl",
        "constants_clk_cc_types.cc",
        "constants_clk_cc_types.hh",
        "constants_clk_cc_types.inl",
        "constants_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "exec_tools",
    srcs = [
        "exec_tools.cc",
        "exec_tools.inl",
    ],
    hdrs = ["exec_tools.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":process_description_clk_cc",
        "//clockwork:repr_iface",
        "//clockwork/pinion:abstract_channel",
        "//clockwork/pinion:abstract_channel_factory",
        "//clockwork/pinion:channel_config_clk_cc",
        "//clockwork/pinion:meta_channel_factory",
        "//clockwork/runners:channel_publisher",
        "//clockwork/runners:deterministic_channel_handler",
        "//jewels/container:compare",
        "//jewels/filesystem:error_code",
        "//jewels/filesystem:file",
        "//jewels/log_cerr",
        "//jewels/memory:memory_resource",
        "//jewels/memory:pmr_shared_ptr",
        "//jewels/memory:pointers",
        "//jewels/meta:concepts",
        "//jewels/std:expected",
        "//jewels/std:span",
        "//jewels/time:sync_time",
        "@tclap",
        "@wise_enum",
    ],
)

cc_library(
    name = "forward",
    hdrs = ["forward.hh"],
    visibility = ["//visibility:public"],
)

clk(
    name = "multi_subscriber_config_clk",
    srcs = ["multi_subscriber_config.clk"],
    outs = [
        "multi_subscriber_config_clk_cc.cc",
        "multi_subscriber_config_clk_cc.hh",
        "multi_subscriber_config_clk_cc.inl",
        "multi_subscriber_config_clk_cc_types.cc",
        "multi_subscriber_config_clk_cc_types.hh",
        "multi_subscriber_config_clk_cc_types.inl",
    ],
    cpp_deps = [":process_description_clk_cc"],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
    deps = [":process_description_clk"],
)

clk(
    name = "platform_diagnostics_config_clk",
    srcs = ["platform_diagnostics_config.clk"],
    outs = [
        "platform_diagnostics_config_clk_cc.cc",
        "platform_diagnostics_config_clk_cc.hh",
        "platform_diagnostics_config_clk_cc.inl",
        "platform_diagnostics_config_clk_cc_types.cc",
        "platform_diagnostics_config_clk_cc_types.hh",
        "platform_diagnostics_config_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":process_description_clk_cc",
        "//clockwork/diagnostics:report_clk_cc",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
    deps = [
        ":constants_clk",
        ":process_description_clk",
        "//clockwork/diagnostics:report_clk",
    ],
)

clk(
    name = "process_description_clk",
    srcs = ["process_description.clk"],
    outs = [
        "process_description_clk_cc.cc",
        "process_description_clk_cc.hh",
        "process_description_clk_cc.inl",
        "process_description_clk_cc_types.cc",
        "process_description_clk_cc_types.hh",
        "process_description_clk_cc_types.inl",
        "process_description_clk_py.py",
    ],
    cpp_deps = ["//clockwork/pinion:channel_config_clk_cc"],
    generate = [
        "cpp",
        "py",
    ],
    minimize_builtin_deps = True,
    py_deps = ["//clockwork/pinion:channel_config_clk_py"],
    visibility = ["//visibility:public"],
    deps = [
        ":constants_clk",
        "//clockwork/pinion:channel_config_clk",
    ],
)

clk(
    name = "signal_metadata_config_clk",
    srcs = ["signal_metadata_config.clk"],
    outs = [
        "signal_metadata_config_clk_cc.cc",
        "signal_metadata_config_clk_cc.hh",
        "signal_metadata_config_clk_cc.inl",
        "signal_metadata_config_clk_cc_types.cc",
        "signal_metadata_config_clk_cc_types.hh",
        "signal_metadata_config_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":constants_clk_cc",
        ":process_description_clk_cc",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
    deps = [
        ":constants_clk",
        ":process_description_clk",
    ],
)

clk(
    name = "simplelaunch_runner_config_clk",
    srcs = ["simplelaunch_runner_config.clk"],
    outs = [
        "simplelaunch_runner_config_clk_cc.cc",
        "simplelaunch_runner_config_clk_cc.hh",
        "simplelaunch_runner_config_clk_cc.inl",
        "simplelaunch_runner_config_clk_cc_types.cc",
        "simplelaunch_runner_config_clk_cc_types.hh",
        "simplelaunch_runner_config_clk_cc_types.inl",
    ],
    cpp_deps = [
        ":platform_diagnostics_config_clk_cc",
        ":process_description_clk_cc",
    ],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
    deps = [
        ":constants_clk",
        ":platform_diagnostics_config_clk",
        ":process_description_clk",
    ],
)

clk(
    name = "system_metadata_clk",
    srcs = ["system_metadata.clk"],
    outs = [
        "system_metadata_clk_cc.cc",
        "system_metadata_clk_cc.hh",
        "system_metadata_clk_cc.inl",
        "system_metadata_clk_cc_types.cc",
        "system_metadata_clk_cc_types.hh",
        "system_metadata_clk_cc_types.inl",
        "system_metadata_clk_py.py",
    ],
    generate = [
        "cpp",
        "py",
    ],
    minimize_builtin_deps = True,
    visibility = ["//visibility:public"],
)
