# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")

package(default_testonly = True)

clk(
    name = "broken_schema_v1_clk",
    srcs = ["broken_schema_v1.clk"],
    outs = [
        "broken_schema_v1_clk_cc.cc",
        "broken_schema_v1_clk_cc.hh",
        "broken_schema_v1_clk_cc.inl",
        "broken_schema_v1_clk_nb.cc",
        "broken_schema_v1_clk_nb.hh",
        "broken_schema_v1_clk_nb.inl",
        "broken_schema_v1_clk_py.py",
    ],
    generate = [
        "cpp",
        "nanobind",
        "py",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "broken_schema_v2_clk",
    srcs = ["broken_schema_v2.clk"],
    outs = [
        "broken_schema_v2_clk_cc.cc",
        "broken_schema_v2_clk_cc.hh",
        "broken_schema_v2_clk_cc.inl",
        "broken_schema_v2_clk_nb.cc",
        "broken_schema_v2_clk_nb.hh",
        "broken_schema_v2_clk_nb.inl",
        "broken_schema_v2_clk_py.py",
    ],
    generate = [
        "cpp",
        "nanobind",
        "py",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "simple_schema_v1_clk",
    srcs = ["simple_schema_v1.clk"],
    outs = [
        "simple_schema_v1_clk_cc.cc",
        "simple_schema_v1_clk_cc.hh",
        "simple_schema_v1_clk_cc.inl",
        "simple_schema_v1_clk_nb.cc",
        "simple_schema_v1_clk_nb.hh",
        "simple_schema_v1_clk_nb.inl",
        "simple_schema_v1_clk_py.py",
    ],
    generate = [
        "cpp",
        "nanobind",
        "py",
    ],
    visibility = ["//visibility:public"],
)

clk(
    name = "simple_schema_v2_clk",
    srcs = ["simple_schema_v2.clk"],
    outs = [
        "simple_schema_v2_clk_cc.cc",
        "simple_schema_v2_clk_cc.hh",
        "simple_schema_v2_clk_cc.inl",
        "simple_schema_v2_clk_nb.cc",
        "simple_schema_v2_clk_nb.hh",
        "simple_schema_v2_clk_nb.inl",
        "simple_schema_v2_clk_py.py",
    ],
    generate = [
        "cpp",
        "nanobind",
        "py",
    ],
    visibility = ["//visibility:public"],
)
