# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Target types for C++."""

from collections.abc import Iterable, MutableSequence, Sequence
from dataclasses import dataclass
from pathlib import Path

from clockwork.dsl.bazel.targets import Label, Target
from typing_extensions import override


@dataclass
class CcLibrary(Target):
    """A cc_library target."""

    hdrs: Sequence[Path]
    srcs: Sequence[Path]
    deps: MutableSequence[Label]
    data: Sequence[Path | Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return [*self.hdrs, *self.srcs]


@dataclass
class CcBinary(Target):
    """A cc_binary target."""

    srcs: Sequence[Path]
    deps: Sequence[Label]
    data: Sequence[Path | Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return self.srcs


@dataclass
class CcBinaryWithEmbeddedPy(Target):
    """A cc_binary_with_embedded_py target."""

    srcs: Sequence[Path]
    deps: Sequence[Label]
    data: Sequence[Path | Label]
    py_deps: Sequence[Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return self.srcs
