# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Bazel target types output by nanobind_target."""

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

from clockwork.dsl.bazel.targets import Label, Target
from typing_extensions import override


@dataclass
class PyCcBinding(Target):
    """A py_cc_binding target."""

    srcs: Sequence[Path]
    deps: Sequence[Label]
    py_deps: Sequence[Label]
    data: Sequence[Path | Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return self.srcs
