# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Target types for Protobuf."""

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final, TypeAlias

from clockwork.dsl.bazel.targets import Label, Target
from clockwork.dsl.serialization.protobuf import ProtobufDep
from typing_extensions import override


@dataclass
class ProtoLibrary(Target):
    """A proto_library target."""

    srcs: Sequence[Path]
    deps: Sequence[Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return self.srcs


@dataclass
class ProtoCompile(Target):
    """A proto_compile target."""

    output_mappings: Sequence[Label]
    outputs: Sequence[Label]
    plugins: Sequence[Label]
    proto: Label


@dataclass
class ProtoCcLibrary(Target):
    """A proto_cc_library target."""

    hdrs: Sequence[Label]
    srcs: Sequence[Label]
    deps: Sequence[Label]


@dataclass
class ProtoPyLibrary(Target):
    """A proto_py_library target."""

    srcs: Sequence[Label]
    deps: Sequence[Label]
    data: Sequence[Label]


@dataclass
class ProtoGoLibrary(Target):
    """A proto_go_library target."""

    srcs: Sequence[Label]
    deps: Sequence[Label]
    importpath: Label


AnyProto: Final[TypeAlias] = ProtoLibrary | ProtoCompile | ProtoCcLibrary | ProtoPyLibrary

PROTOBUF_PATH: Final = Path("google/protobuf")


def assert_path_is_proto(path: Path) -> None:
    """Assert that the path is a proto file."""
    if path.suffix != ".proto":
        msg = f"Unable to convert path with extension '{path.suffix}' to a proto_library Label."
        raise ValueError(msg)


class PathToProto:
    """Class to generate bazel Labels relative to the given target."""

    def __init__(self, target: ProtobufDep) -> None:
        """Constructor."""
        self.target = target

    def _make_label(self, dep: ProtobufDep, suffix: str) -> Label:
        """Create a label from the given dep, adding a repo prefix if it differs from the PathToProto's target."""
        assert_path_is_proto(dep.path)
        repo = f"@{dep.module_id.repo}" if dep.module_id.repo != self.target.module_id.repo else ""
        return Label(value=f"{repo}//{dep.path.parent}:{dep.path.stem}{suffix}")

    def to_proto_library(self, dep: ProtobufDep) -> Label:
        """Convert path to a proto_compile label."""
        if dep.path.parent == PROTOBUF_PATH:
            assert_path_is_proto(dep.path)
            return Label(value=f"@protobuf//:{dep.path.stem}_proto")
        return self._make_label(dep, "")

    def to_proto_compile(self, dep: ProtobufDep) -> Label:
        """Convert path to a proto_compile label."""
        return self._make_label(dep, "_compile")

    def to_proto_cc_library(self, dep: ProtobufDep) -> Label:
        """Convert path to a proto_cc_library label."""
        return self._make_label(dep, "_cc_library")

    def to_cc_hdr(self, dep: ProtobufDep) -> Label:
        """Convert path to a .h label."""
        return self._make_label(dep, ".pb.h")

    def to_cc_src(self, dep: ProtobufDep) -> Label:
        """Convert path to a .cc label."""
        return self._make_label(dep, ".pb.cc")

    def to_proto_py_library(self, dep: ProtobufDep) -> Label:
        """Convert path to a proto_py_library label."""
        return self._make_label(dep, "_py_library")

    def to_py(self, dep: ProtobufDep) -> Label:
        """Convert path to a .py label."""
        return self._make_label(dep, "_pb2.py")

    def to_pyi(self, dep: ProtobufDep) -> Label:
        """Convert path to a .pyi label."""
        return self._make_label(dep, "_pb2.pyi")

    def to_proto_go_library(self, dep: ProtobufDep) -> Label:
        """Convert path to a proto_go_library label."""
        return self._make_label(dep, "_go_library")

    def to_go(self, dep: ProtobufDep) -> Label:
        """Convert path to a .go label."""
        return self._make_label(dep, ".pb.go")
