# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Target types for Python."""

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

from clockwork.dsl.bazel.targets import Label, Target
from typing_extensions import override


@dataclass
class PyLibrary(Target):
    """A py_library target."""

    srcs: Sequence[Path]
    deps: Sequence[Label]
    data: Sequence[Path | Label]

    @property
    @override
    def generated_files(self) -> Iterable[Path]:
        """List the files generated by the corresponding clk module."""
        return self.srcs
