# Copyright 2025-2026 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Target types for C++."""

from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from itertools import chain
from pathlib import Path

from clockwork.dsl.bazel.targets import Label, Target
from typing_extensions import override


@dataclass
class MergeSimplelaunchConfig(Target):
    """A merge_simplelaunch_config target."""

    srcs: Sequence[Path | Label]
    data: Sequence[Path | Label]

    @property
    @override
    def generated_files(self) -> Iterator[Path]:
        """List the files generated by the corresponding clk module."""
        for value in chain(self.srcs, self.data):
            if isinstance(value, Path):
                yield value


def config_name_from_domain_node_name(domain_node_name: str) -> str:
    """Domain simplelaunch node name to name of simple launch config.."""
    return domain_node_name + ".textproto"
