# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

"""Base bazel target type."""

from __future__ import annotations

from dataclasses import dataclass, fields
from typing import TYPE_CHECKING

from clockwork.dsl.ir.module_id import CLK_REPO
from pydantic.alias_generators import to_snake
from typing_extensions import override

if TYPE_CHECKING:
    from collections.abc import Iterable
    from pathlib import Path


def get_bazel_label_for_python_type(py_type: str) -> Label | None:
    """Get the bazel label for a python type.

    A fully qualified python type has at least a module and a type name,
    like "my_mod.MyType", or "my_path.my_mod.MyType". If the path is too short
    return None because we don't want to add a dependency for that.

    The label for "my_mod.MyType" is "//:my_mod".
    The label for "my_path.my_mod.MyType" is "//my_path:my_mod".

    Arguments:
        py_type: Qualified python type string.

    Returns:
        Bazel label or None if the the string isn't qualified.
    """
    module_parts = py_type.split(".")
    minimum_label_type_parts = 2
    if len(module_parts) < minimum_label_type_parts:
        return None
    return Label("//" + "/".join(module_parts[:-2]) + ":" + module_parts[-2])


def get_bazel_label_for_clk_label(current_repo: str, clk_label: str) -> Label:
    """Get the bazel label for a label in the clockwork repo.

    If the current_repo is the clockwork repo then this just returns the clockwork label.
    If the current_repo is not the clockwork repo then prepend "@clockwork" to the label.

    Arguments:
        current_repo: Current repository.
        clk_label: Label in the clockwork repository.

    Returns:
        Bazel label for use in the current repo.
    """
    if clk_label.startswith("@"):
        return Label(clk_label)
    if current_repo == CLK_REPO:
        return Label(clk_label)
    return Label(f"@{CLK_REPO}{clk_label}")


@dataclass
class Target:
    """Base type for all bazel target types."""

    name: str

    @property
    def generated_files(self) -> Iterable[Path] | None:
        """For a target, list the files generated by the corresponding clk module."""
        return None

    @property
    def kind(self) -> str:
        """Get the rule kind of this target."""
        return to_snake(self.__class__.__name__)

    @override
    def __str__(self) -> str:
        """Create a string representation of the object."""
        string = f"{self.kind}(\n"
        for field in fields(self):
            value = getattr(self, field.name)
            if isinstance(value, list):
                if not value:
                    continue
                value_str: list[str] | str = [str(i) for i in value]
            elif isinstance(value, bool):
                value_str = str(value)
            else:
                value_str = f"'{value}'"

            string += f"\t{field.name} = {value_str},\n"
        string += ")"
        return string


@dataclass(eq=True, frozen=True, order=True)
class Label:
    """A bazel label."""

    value: str

    @property
    def name(self) -> Label:
        """Get the relative label."""
        if (loc := self.value.find(":")) < 0:
            return self
        return Label(value=self.value[loc + 1 :])

    @override
    def __str__(self) -> str:
        """Create a string representation of the object."""
        return self.value
