# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//clockwork:rules.bzl", "clk")
load("//tools/rules:cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

exports_files(["metrics_channel_metadata_config.clk"])

clk(
    name = "metrics_channel_metadata_config_clk",
    srcs = ["metrics_channel_metadata_config.clk"],
    outs = [
        "metrics_channel_metadata_config_clk_cc.cc",
        "metrics_channel_metadata_config_clk_cc.hh",
        "metrics_channel_metadata_config_clk_cc.inl",
    ],
    cpp_deps = ["//clockwork/common:process_description_clk_cc"],
    generate = ["cpp"],
    minimize_builtin_deps = True,
    deps = [
        "//clockwork/common:constants_clk",
        "//clockwork/common:process_description_clk",
    ],
)

clk(
    name = "metrics_channel_metadata_init_clk",
    srcs = ["metrics_channel_metadata_init.clk"],
    outs = [
        "metrics_channel_metadata_init_clk_cc.cc",
        "metrics_channel_metadata_init_clk_cc.hh",
        "metrics_channel_metadata_init_clk_cc.inl",
        "metrics_channel_metadata_init_clk_cc_dial.cc",
        "metrics_channel_metadata_init_clk_cc_dial.hh",
        "metrics_channel_metadata_init_clk_cc_dial.inl",
    ],
    cpp_deps = [":metrics_channel_metadata_config_clk_cc"],
    generate = [
        "cpp",
        "cpp_cog",
    ],
    deps = [":metrics_channel_metadata_config_clk"],
)

cc_library(
    name = "metrics_channel_metadata_init_clk_cc_impl",
    srcs = ["metrics_channel_metadata_init_clk_cc_impl.cc"],
    deps = [
        ":metrics_channel_metadata_config_clk_cc",
        ":metrics_channel_metadata_init_clk_cc_dial",
        "//clockwork/pinion:publishable",
        "//jewels/container/tap:var_array",
    ],
)
