# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

load("//tools/rules:cc.bzl", "cc_library")

cc_library(
    name = "conversions",
    hdrs = ["conversions.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":sync_time",
        "//jewels/units:seconds",
        "@au",
    ],
)

cc_library(
    name = "sync_time",
    hdrs = ["sync_time.hh"],
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)
